/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
/**
 * Enum containing the actions that can be performed against a resource. Group operations are included.
 */
export const ACLAction = {
    Create: "create",
    Delete: "delete",
    Read: "read",
    Update: "update",
    List: "list",
};
/** @internal */
export const ACLAction$inboundSchema = z
    .nativeEnum(ACLAction);
/** @internal */
export const ACLAction$outboundSchema = ACLAction$inboundSchema;
//# sourceMappingURL=aclaction.js.map