/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
export const SDKKeyType = {
    Server: "server",
    Mobile: "mobile",
    Client: "client",
};
/** @internal */
export const SDKKeyType$inboundSchema = z
    .nativeEnum(SDKKeyType);
/** @internal */
export const SDKKeyType$outboundSchema = SDKKeyType$inboundSchema;
/** @internal */
export const CreateSDKKeyRequestBody$inboundSchema = z.object({
    sdkKeyType: SDKKeyType$inboundSchema,
    environment: types.string(),
    label: types.optional(types.string()),
});
/** @internal */
export const CreateSDKKeyRequestBody$outboundSchema = z.object({
    sdkKeyType: SDKKeyType$outboundSchema,
    environment: z.string(),
    label: z.string().optional(),
});
export function createSDKKeyRequestBodyToJSON(createSDKKeyRequestBody) {
    return JSON.stringify(CreateSDKKeyRequestBody$outboundSchema.parse(createSDKKeyRequestBody));
}
export function createSDKKeyRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CreateSDKKeyRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CreateSDKKeyRequestBody' from JSON`);
}
/** @internal */
export const CreateSDKKeyRequest$inboundSchema = z.object({
    projectIdOrName: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
    RequestBody: types.optional(z.lazy(() => CreateSDKKeyRequestBody$inboundSchema)),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const CreateSDKKeyRequest$outboundSchema = z.object({
    projectIdOrName: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
    requestBody: z.lazy(() => CreateSDKKeyRequestBody$outboundSchema).optional(),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function createSDKKeyRequestToJSON(createSDKKeyRequest) {
    return JSON.stringify(CreateSDKKeyRequest$outboundSchema.parse(createSDKKeyRequest));
}
export function createSDKKeyRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CreateSDKKeyRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CreateSDKKeyRequest' from JSON`);
}
//# sourceMappingURL=createsdkkeyop.js.map