/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
/** @internal */
export const Event2$inboundSchema = z
    .object({
    type: types.literal("resource.updated"),
    productId: types.optional(types.string()),
    resourceId: types.string(),
});
/** @internal */
export const Event2$outboundSchema = z.object({
    type: z.literal("resource.updated"),
    productId: z.string().optional(),
    resourceId: z.string(),
});
export function event2ToJSON(event2) {
    return JSON.stringify(Event2$outboundSchema.parse(event2));
}
export function event2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => Event2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'Event2' from JSON`);
}
/** @internal */
export const Event1$inboundSchema = z
    .object({
    type: types.literal("installation.updated"),
    billingPlanId: types.optional(types.string()),
});
/** @internal */
export const Event1$outboundSchema = z.object({
    type: z.literal("installation.updated"),
    billingPlanId: z.string().optional(),
});
export function event1ToJSON(event1) {
    return JSON.stringify(Event1$outboundSchema.parse(event1));
}
export function event1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => Event1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'Event1' from JSON`);
}
/** @internal */
export const CreateEventEvent$inboundSchema = z.union([
    z.lazy(() => Event1$inboundSchema),
    z.lazy(() => Event2$inboundSchema),
]);
/** @internal */
export const CreateEventEvent$outboundSchema = z.union([
    z.lazy(() => Event1$outboundSchema),
    z.lazy(() => Event2$outboundSchema),
]);
export function createEventEventToJSON(createEventEvent) {
    return JSON.stringify(CreateEventEvent$outboundSchema.parse(createEventEvent));
}
export function createEventEventFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CreateEventEvent$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CreateEventEvent' from JSON`);
}
/** @internal */
export const CreateEventRequestBody$inboundSchema = z.object({
    event: z.union([
        z.lazy(() => Event1$inboundSchema),
        z.lazy(() => Event2$inboundSchema),
    ]),
});
/** @internal */
export const CreateEventRequestBody$outboundSchema = z.object({
    event: z.union([
        z.lazy(() => Event1$outboundSchema),
        z.lazy(() => Event2$outboundSchema),
    ]),
});
export function createEventRequestBodyToJSON(createEventRequestBody) {
    return JSON.stringify(CreateEventRequestBody$outboundSchema.parse(createEventRequestBody));
}
export function createEventRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CreateEventRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CreateEventRequestBody' from JSON`);
}
/** @internal */
export const CreateEventRequest$inboundSchema = z.object({
    integrationConfigurationId: types.string(),
    RequestBody: z.lazy(() => CreateEventRequestBody$inboundSchema),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const CreateEventRequest$outboundSchema = z.object({
    integrationConfigurationId: z.string(),
    requestBody: z.lazy(() => CreateEventRequestBody$outboundSchema),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function createEventRequestToJSON(createEventRequest) {
    return JSON.stringify(CreateEventRequest$outboundSchema.parse(createEventRequest));
}
export function createEventRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CreateEventRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CreateEventRequest' from JSON`);
}
//# sourceMappingURL=createeventop.js.map