/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
/**
 * The project role that will be added to this Access Group.
 */
export const CreateAccessGroupProjectRole = {
    Admin: "ADMIN",
    ProjectViewer: "PROJECT_VIEWER",
    ProjectDeveloper: "PROJECT_DEVELOPER",
};
export const CreateAccessGroupProjectAccessGroupsRole = {
    Admin: "ADMIN",
    ProjectDeveloper: "PROJECT_DEVELOPER",
    ProjectViewer: "PROJECT_VIEWER",
    ProjectGuest: "PROJECT_GUEST",
};
/** @internal */
export const CreateAccessGroupProjectRole$inboundSchema = z.nativeEnum(CreateAccessGroupProjectRole);
/** @internal */
export const CreateAccessGroupProjectRole$outboundSchema = CreateAccessGroupProjectRole$inboundSchema;
/** @internal */
export const CreateAccessGroupProjectRequestBody$inboundSchema = z.object({
    projectId: types.string(),
    role: CreateAccessGroupProjectRole$inboundSchema,
});
/** @internal */
export const CreateAccessGroupProjectRequestBody$outboundSchema = z.object({
    projectId: z.string(),
    role: CreateAccessGroupProjectRole$outboundSchema,
});
export function createAccessGroupProjectRequestBodyToJSON(createAccessGroupProjectRequestBody) {
    return JSON.stringify(CreateAccessGroupProjectRequestBody$outboundSchema.parse(createAccessGroupProjectRequestBody));
}
export function createAccessGroupProjectRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CreateAccessGroupProjectRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CreateAccessGroupProjectRequestBody' from JSON`);
}
/** @internal */
export const CreateAccessGroupProjectRequest$inboundSchema = z.object({
    accessGroupIdOrName: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
    RequestBody: z.lazy(() => CreateAccessGroupProjectRequestBody$inboundSchema),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const CreateAccessGroupProjectRequest$outboundSchema = z.object({
    accessGroupIdOrName: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
    requestBody: z.lazy(() => CreateAccessGroupProjectRequestBody$outboundSchema),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function createAccessGroupProjectRequestToJSON(createAccessGroupProjectRequest) {
    return JSON.stringify(CreateAccessGroupProjectRequest$outboundSchema.parse(createAccessGroupProjectRequest));
}
export function createAccessGroupProjectRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CreateAccessGroupProjectRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CreateAccessGroupProjectRequest' from JSON`);
}
/** @internal */
export const CreateAccessGroupProjectAccessGroupsRole$inboundSchema = z
    .nativeEnum(CreateAccessGroupProjectAccessGroupsRole);
/** @internal */
export const CreateAccessGroupProjectAccessGroupsRole$outboundSchema = CreateAccessGroupProjectAccessGroupsRole$inboundSchema;
/** @internal */
export const CreateAccessGroupProjectResponseBody$inboundSchema = z.object({
    teamId: types.string(),
    accessGroupId: types.string(),
    projectId: types.string(),
    role: CreateAccessGroupProjectAccessGroupsRole$inboundSchema,
    createdAt: types.string(),
    updatedAt: types.string(),
});
/** @internal */
export const CreateAccessGroupProjectResponseBody$outboundSchema = z.object({
    teamId: z.string(),
    accessGroupId: z.string(),
    projectId: z.string(),
    role: CreateAccessGroupProjectAccessGroupsRole$outboundSchema,
    createdAt: z.string(),
    updatedAt: z.string(),
});
export function createAccessGroupProjectResponseBodyToJSON(createAccessGroupProjectResponseBody) {
    return JSON.stringify(CreateAccessGroupProjectResponseBody$outboundSchema.parse(createAccessGroupProjectResponseBody));
}
export function createAccessGroupProjectResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CreateAccessGroupProjectResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CreateAccessGroupProjectResponseBody' from JSON`);
}
//# sourceMappingURL=createaccessgroupprojectop.js.map