/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
export const DangerouslyDeleteByTagsTarget = {
    Production: "production",
    Preview: "preview",
};
/** @internal */
export const DangerouslyDeleteByTagsTags$inboundSchema = smartUnion([z.array(types.string()), types.string()]);
/** @internal */
export const DangerouslyDeleteByTagsTags$outboundSchema = smartUnion([z.array(z.string()), z.string()]);
export function dangerouslyDeleteByTagsTagsToJSON(dangerouslyDeleteByTagsTags) {
    return JSON.stringify(DangerouslyDeleteByTagsTags$outboundSchema.parse(dangerouslyDeleteByTagsTags));
}
export function dangerouslyDeleteByTagsTagsFromJSON(jsonString) {
    return safeParse(jsonString, (x) => DangerouslyDeleteByTagsTags$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DangerouslyDeleteByTagsTags' from JSON`);
}
/** @internal */
export const DangerouslyDeleteByTagsTarget$inboundSchema = z.nativeEnum(DangerouslyDeleteByTagsTarget);
/** @internal */
export const DangerouslyDeleteByTagsTarget$outboundSchema = DangerouslyDeleteByTagsTarget$inboundSchema;
/** @internal */
export const DangerouslyDeleteByTagsRequestBody$inboundSchema = z.object({
    revalidationDeadlineSeconds: types.optional(types.number()),
    tags: smartUnion([z.array(types.string()), types.string()]),
    target: types.optional(DangerouslyDeleteByTagsTarget$inboundSchema),
});
/** @internal */
export const DangerouslyDeleteByTagsRequestBody$outboundSchema = z.object({
    revalidationDeadlineSeconds: z.number().optional(),
    tags: smartUnion([z.array(z.string()), z.string()]),
    target: DangerouslyDeleteByTagsTarget$outboundSchema.optional(),
});
export function dangerouslyDeleteByTagsRequestBodyToJSON(dangerouslyDeleteByTagsRequestBody) {
    return JSON.stringify(DangerouslyDeleteByTagsRequestBody$outboundSchema.parse(dangerouslyDeleteByTagsRequestBody));
}
export function dangerouslyDeleteByTagsRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => DangerouslyDeleteByTagsRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DangerouslyDeleteByTagsRequestBody' from JSON`);
}
/** @internal */
export const DangerouslyDeleteByTagsRequest$inboundSchema = z.object({
    projectIdOrName: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
    RequestBody: types.optional(z.lazy(() => DangerouslyDeleteByTagsRequestBody$inboundSchema)),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const DangerouslyDeleteByTagsRequest$outboundSchema = z.object({
    projectIdOrName: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
    requestBody: z.lazy(() => DangerouslyDeleteByTagsRequestBody$outboundSchema)
        .optional(),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function dangerouslyDeleteByTagsRequestToJSON(dangerouslyDeleteByTagsRequest) {
    return JSON.stringify(DangerouslyDeleteByTagsRequest$outboundSchema.parse(dangerouslyDeleteByTagsRequest));
}
export function dangerouslyDeleteByTagsRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => DangerouslyDeleteByTagsRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DangerouslyDeleteByTagsRequest' from JSON`);
}
//# sourceMappingURL=dangerouslydeletebytagsop.js.map