/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
/** @internal */
export const DeleteFlagSegmentRequest$inboundSchema = z.object({
    projectIdOrName: types.string(),
    segmentIdOrSlug: types.string(),
    withMetadata: types.boolean().default(false),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
});
/** @internal */
export const DeleteFlagSegmentRequest$outboundSchema = z.object({
    projectIdOrName: z.string(),
    segmentIdOrSlug: z.string(),
    withMetadata: z.boolean().default(false),
    teamId: z.string().optional(),
    slug: z.string().optional(),
});
export function deleteFlagSegmentRequestToJSON(deleteFlagSegmentRequest) {
    return JSON.stringify(DeleteFlagSegmentRequest$outboundSchema.parse(deleteFlagSegmentRequest));
}
export function deleteFlagSegmentRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => DeleteFlagSegmentRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DeleteFlagSegmentRequest' from JSON`);
}
//# sourceMappingURL=deleteflagsegmentop.js.map