/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
/** @internal */
export const DeleteDrainRequest$inboundSchema = z.object({
    id: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
});
/** @internal */
export const DeleteDrainRequest$outboundSchema = z.object({
    id: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
});
export function deleteDrainRequestToJSON(deleteDrainRequest) {
    return JSON.stringify(DeleteDrainRequest$outboundSchema.parse(deleteDrainRequest));
}
export function deleteDrainRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => DeleteDrainRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DeleteDrainRequest' from JSON`);
}
//# sourceMappingURL=deletedrainop.js.map