/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
export const EditProjectEnvTarget = {
    Production: "production",
    Preview: "preview",
    Development: "development",
};
/**
 * The type of environment variable
 */
export const EditProjectEnvType = {
    System: "system",
    Secret: "secret",
    Encrypted: "encrypted",
    Plain: "plain",
    Sensitive: "sensitive",
};
export const EditProjectEnvProjectsType = {
    Secret: "secret",
    System: "system",
    Encrypted: "encrypted",
    Plain: "plain",
    Sensitive: "sensitive",
};
export const EditProjectEnvTarget2 = {
    Production: "production",
    Preview: "preview",
    Development: "development",
};
export const EditProjectEnvTarget1 = {
    Production: "production",
    Preview: "preview",
    Development: "development",
};
export const EditProjectEnvProjectsResponseType = {
    FlagsSecret: "flags-secret",
};
/** @internal */
export const EditProjectEnvTarget$inboundSchema = z.nativeEnum(EditProjectEnvTarget);
/** @internal */
export const EditProjectEnvTarget$outboundSchema = EditProjectEnvTarget$inboundSchema;
/** @internal */
export const EditProjectEnvType$inboundSchema = z.nativeEnum(EditProjectEnvType);
/** @internal */
export const EditProjectEnvType$outboundSchema = EditProjectEnvType$inboundSchema;
/** @internal */
export const EditProjectEnvRequestBody$inboundSchema = z.object({
    key: types.optional(types.string()),
    target: types.optional(z.array(EditProjectEnvTarget$inboundSchema)),
    gitBranch: z.nullable(types.string()).optional(),
    type: types.optional(EditProjectEnvType$inboundSchema),
    value: types.optional(types.string()),
    customEnvironmentIds: types.optional(z.array(types.string())),
    comment: types.optional(types.string()),
});
/** @internal */
export const EditProjectEnvRequestBody$outboundSchema = z.object({
    key: z.string().optional(),
    target: z.array(EditProjectEnvTarget$outboundSchema).optional(),
    gitBranch: z.nullable(z.string()).optional(),
    type: EditProjectEnvType$outboundSchema.optional(),
    value: z.string().optional(),
    customEnvironmentIds: z.array(z.string()).optional(),
    comment: z.string().optional(),
});
export function editProjectEnvRequestBodyToJSON(editProjectEnvRequestBody) {
    return JSON.stringify(EditProjectEnvRequestBody$outboundSchema.parse(editProjectEnvRequestBody));
}
export function editProjectEnvRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => EditProjectEnvRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'EditProjectEnvRequestBody' from JSON`);
}
/** @internal */
export const EditProjectEnvRequest$inboundSchema = z.object({
    idOrName: types.string(),
    id: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
    RequestBody: z.lazy(() => EditProjectEnvRequestBody$inboundSchema),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const EditProjectEnvRequest$outboundSchema = z.object({
    idOrName: z.string(),
    id: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
    requestBody: z.lazy(() => EditProjectEnvRequestBody$outboundSchema),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function editProjectEnvRequestToJSON(editProjectEnvRequest) {
    return JSON.stringify(EditProjectEnvRequest$outboundSchema.parse(editProjectEnvRequest));
}
export function editProjectEnvRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => EditProjectEnvRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'EditProjectEnvRequest' from JSON`);
}
/** @internal */
export const EditProjectEnvProjectsType$inboundSchema = z.nativeEnum(EditProjectEnvProjectsType);
/** @internal */
export const EditProjectEnvProjectsType$outboundSchema = EditProjectEnvProjectsType$inboundSchema;
/** @internal */
export const EditProjectEnvTarget2$inboundSchema = z.nativeEnum(EditProjectEnvTarget2);
/** @internal */
export const EditProjectEnvTarget2$outboundSchema = EditProjectEnvTarget2$inboundSchema;
/** @internal */
export const EditProjectEnvTarget1$inboundSchema = z.nativeEnum(EditProjectEnvTarget1);
/** @internal */
export const EditProjectEnvTarget1$outboundSchema = EditProjectEnvTarget1$inboundSchema;
/** @internal */
export const EditProjectEnvProjectsTarget$inboundSchema = smartUnion([
    z.array(EditProjectEnvTarget1$inboundSchema),
    EditProjectEnvTarget2$inboundSchema,
]);
/** @internal */
export const EditProjectEnvProjectsTarget$outboundSchema = smartUnion([
    z.array(EditProjectEnvTarget1$outboundSchema),
    EditProjectEnvTarget2$outboundSchema,
]);
export function editProjectEnvProjectsTargetToJSON(editProjectEnvProjectsTarget) {
    return JSON.stringify(EditProjectEnvProjectsTarget$outboundSchema.parse(editProjectEnvProjectsTarget));
}
export function editProjectEnvProjectsTargetFromJSON(jsonString) {
    return safeParse(jsonString, (x) => EditProjectEnvProjectsTarget$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'EditProjectEnvProjectsTarget' from JSON`);
}
/** @internal */
export const ContentHint15$inboundSchema = z.object({
    type: types.literal("flags-connection-string"),
    projectId: types.string(),
});
/** @internal */
export const ContentHint15$outboundSchema = z.object({
    type: z.literal("flags-connection-string"),
    projectId: z.string(),
});
export function contentHint15ToJSON(contentHint15) {
    return JSON.stringify(ContentHint15$outboundSchema.parse(contentHint15));
}
export function contentHint15FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint15$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint15' from JSON`);
}
/** @internal */
export const ContentHint14$inboundSchema = z.object({
    type: types.literal("integration-store-secret"),
    storeId: types.string(),
    integrationId: types.string(),
    integrationProductId: types.string(),
    integrationConfigurationId: types.string(),
});
/** @internal */
export const ContentHint14$outboundSchema = z.object({
    type: z.literal("integration-store-secret"),
    storeId: z.string(),
    integrationId: z.string(),
    integrationProductId: z.string(),
    integrationConfigurationId: z.string(),
});
export function contentHint14ToJSON(contentHint14) {
    return JSON.stringify(ContentHint14$outboundSchema.parse(contentHint14));
}
export function contentHint14FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint14$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint14' from JSON`);
}
/** @internal */
export const ContentHint13$inboundSchema = z.object({
    type: types.literal("postgres-url-no-ssl"),
    storeId: types.string(),
});
/** @internal */
export const ContentHint13$outboundSchema = z.object({
    type: z.literal("postgres-url-no-ssl"),
    storeId: z.string(),
});
export function contentHint13ToJSON(contentHint13) {
    return JSON.stringify(ContentHint13$outboundSchema.parse(contentHint13));
}
export function contentHint13FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint13$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint13' from JSON`);
}
/** @internal */
export const ContentHint12$inboundSchema = z.object({
    type: types.literal("postgres-database"),
    storeId: types.string(),
});
/** @internal */
export const ContentHint12$outboundSchema = z.object({
    type: z.literal("postgres-database"),
    storeId: z.string(),
});
export function contentHint12ToJSON(contentHint12) {
    return JSON.stringify(ContentHint12$outboundSchema.parse(contentHint12));
}
export function contentHint12FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint12$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint12' from JSON`);
}
/** @internal */
export const ContentHint11$inboundSchema = z.object({
    type: types.literal("postgres-password"),
    storeId: types.string(),
});
/** @internal */
export const ContentHint11$outboundSchema = z.object({
    type: z.literal("postgres-password"),
    storeId: z.string(),
});
export function contentHint11ToJSON(contentHint11) {
    return JSON.stringify(ContentHint11$outboundSchema.parse(contentHint11));
}
export function contentHint11FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint11$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint11' from JSON`);
}
/** @internal */
export const ContentHint10$inboundSchema = z.object({
    type: types.literal("postgres-host"),
    storeId: types.string(),
});
/** @internal */
export const ContentHint10$outboundSchema = z.object({
    type: z.literal("postgres-host"),
    storeId: z.string(),
});
export function contentHint10ToJSON(contentHint10) {
    return JSON.stringify(ContentHint10$outboundSchema.parse(contentHint10));
}
export function contentHint10FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint10$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint10' from JSON`);
}
/** @internal */
export const ContentHint9$inboundSchema = z.object({
    type: types.literal("postgres-user"),
    storeId: types.string(),
});
/** @internal */
export const ContentHint9$outboundSchema = z.object({
    type: z.literal("postgres-user"),
    storeId: z.string(),
});
export function contentHint9ToJSON(contentHint9) {
    return JSON.stringify(ContentHint9$outboundSchema.parse(contentHint9));
}
export function contentHint9FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint9$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint9' from JSON`);
}
/** @internal */
export const ContentHint8$inboundSchema = z.object({
    type: types.literal("postgres-prisma-url"),
    storeId: types.string(),
});
/** @internal */
export const ContentHint8$outboundSchema = z.object({
    type: z.literal("postgres-prisma-url"),
    storeId: z.string(),
});
export function contentHint8ToJSON(contentHint8) {
    return JSON.stringify(ContentHint8$outboundSchema.parse(contentHint8));
}
export function contentHint8FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint8$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint8' from JSON`);
}
/** @internal */
export const ContentHint7$inboundSchema = z.object({
    type: types.literal("postgres-url-non-pooling"),
    storeId: types.string(),
});
/** @internal */
export const ContentHint7$outboundSchema = z.object({
    type: z.literal("postgres-url-non-pooling"),
    storeId: z.string(),
});
export function contentHint7ToJSON(contentHint7) {
    return JSON.stringify(ContentHint7$outboundSchema.parse(contentHint7));
}
export function contentHint7FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint7$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint7' from JSON`);
}
/** @internal */
export const ContentHint6$inboundSchema = z.object({
    type: types.literal("postgres-url"),
    storeId: types.string(),
});
/** @internal */
export const ContentHint6$outboundSchema = z.object({
    type: z.literal("postgres-url"),
    storeId: z.string(),
});
export function contentHint6ToJSON(contentHint6) {
    return JSON.stringify(ContentHint6$outboundSchema.parse(contentHint6));
}
export function contentHint6FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint6$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint6' from JSON`);
}
/** @internal */
export const ContentHint5$inboundSchema = z.object({
    type: types.literal("blob-read-write-token"),
    storeId: types.string(),
});
/** @internal */
export const ContentHint5$outboundSchema = z.object({
    type: z.literal("blob-read-write-token"),
    storeId: z.string(),
});
export function contentHint5ToJSON(contentHint5) {
    return JSON.stringify(ContentHint5$outboundSchema.parse(contentHint5));
}
export function contentHint5FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint5$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint5' from JSON`);
}
/** @internal */
export const ContentHint4$inboundSchema = z.object({
    type: types.literal("redis-rest-api-read-only-token"),
    storeId: types.string(),
});
/** @internal */
export const ContentHint4$outboundSchema = z.object({
    type: z.literal("redis-rest-api-read-only-token"),
    storeId: z.string(),
});
export function contentHint4ToJSON(contentHint4) {
    return JSON.stringify(ContentHint4$outboundSchema.parse(contentHint4));
}
export function contentHint4FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint4$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint4' from JSON`);
}
/** @internal */
export const ContentHint3$inboundSchema = z.object({
    type: types.literal("redis-rest-api-token"),
    storeId: types.string(),
});
/** @internal */
export const ContentHint3$outboundSchema = z.object({
    type: z.literal("redis-rest-api-token"),
    storeId: z.string(),
});
export function contentHint3ToJSON(contentHint3) {
    return JSON.stringify(ContentHint3$outboundSchema.parse(contentHint3));
}
export function contentHint3FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint3$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint3' from JSON`);
}
/** @internal */
export const ContentHint2$inboundSchema = z.object({
    type: types.literal("redis-rest-api-url"),
    storeId: types.string(),
});
/** @internal */
export const ContentHint2$outboundSchema = z.object({
    type: z.literal("redis-rest-api-url"),
    storeId: z.string(),
});
export function contentHint2ToJSON(contentHint2) {
    return JSON.stringify(ContentHint2$outboundSchema.parse(contentHint2));
}
export function contentHint2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint2' from JSON`);
}
/** @internal */
export const ContentHint1$inboundSchema = z.object({
    type: types.literal("redis-url"),
    storeId: types.string(),
});
/** @internal */
export const ContentHint1$outboundSchema = z.object({
    type: z.literal("redis-url"),
    storeId: z.string(),
});
export function contentHint1ToJSON(contentHint1) {
    return JSON.stringify(ContentHint1$outboundSchema.parse(contentHint1));
}
export function contentHint1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint1' from JSON`);
}
/** @internal */
export const ContentHint$inboundSchema = z.union([
    z.lazy(() => ContentHint1$inboundSchema),
    z.lazy(() => ContentHint2$inboundSchema),
    z.lazy(() => ContentHint3$inboundSchema),
    z.lazy(() => ContentHint4$inboundSchema),
    z.lazy(() => ContentHint5$inboundSchema),
    z.lazy(() => ContentHint6$inboundSchema),
    z.lazy(() => ContentHint7$inboundSchema),
    z.lazy(() => ContentHint8$inboundSchema),
    z.lazy(() => ContentHint9$inboundSchema),
    z.lazy(() => ContentHint10$inboundSchema),
    z.lazy(() => ContentHint11$inboundSchema),
    z.lazy(() => ContentHint12$inboundSchema),
    z.lazy(() => ContentHint13$inboundSchema),
    z.lazy(() => ContentHint14$inboundSchema),
    z.lazy(() => ContentHint15$inboundSchema),
]);
/** @internal */
export const ContentHint$outboundSchema = z.union([
    z.lazy(() => ContentHint1$outboundSchema),
    z.lazy(() => ContentHint2$outboundSchema),
    z.lazy(() => ContentHint3$outboundSchema),
    z.lazy(() => ContentHint4$outboundSchema),
    z.lazy(() => ContentHint5$outboundSchema),
    z.lazy(() => ContentHint6$outboundSchema),
    z.lazy(() => ContentHint7$outboundSchema),
    z.lazy(() => ContentHint8$outboundSchema),
    z.lazy(() => ContentHint9$outboundSchema),
    z.lazy(() => ContentHint10$outboundSchema),
    z.lazy(() => ContentHint11$outboundSchema),
    z.lazy(() => ContentHint12$outboundSchema),
    z.lazy(() => ContentHint13$outboundSchema),
    z.lazy(() => ContentHint14$outboundSchema),
    z.lazy(() => ContentHint15$outboundSchema),
]);
export function contentHintToJSON(contentHint) {
    return JSON.stringify(ContentHint$outboundSchema.parse(contentHint));
}
export function contentHintFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ContentHint$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ContentHint' from JSON`);
}
/** @internal */
export const EditProjectEnvProjectsResponseType$inboundSchema = z.nativeEnum(EditProjectEnvProjectsResponseType);
/** @internal */
export const EditProjectEnvProjectsResponseType$outboundSchema = EditProjectEnvProjectsResponseType$inboundSchema;
/** @internal */
export const InternalContentHint$inboundSchema = z.object({
    type: EditProjectEnvProjectsResponseType$inboundSchema,
    encryptedValue: types.string(),
});
/** @internal */
export const InternalContentHint$outboundSchema = z.object({
    type: EditProjectEnvProjectsResponseType$outboundSchema,
    encryptedValue: z.string(),
});
export function internalContentHintToJSON(internalContentHint) {
    return JSON.stringify(InternalContentHint$outboundSchema.parse(internalContentHint));
}
export function internalContentHintFromJSON(jsonString) {
    return safeParse(jsonString, (x) => InternalContentHint$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'InternalContentHint' from JSON`);
}
/** @internal */
export const EditProjectEnvResponseBody$inboundSchema = z.object({
    type: EditProjectEnvProjectsType$inboundSchema,
    value: types.string(),
    edgeConfigId: z.nullable(types.string()).optional(),
    edgeConfigTokenId: z.nullable(types.string()).optional(),
    createdAt: types.optional(types.number()),
    updatedAt: types.optional(types.number()),
    id: types.optional(types.string()),
    createdBy: z.nullable(types.string()).optional(),
    target: types.optional(smartUnion([
        z.array(EditProjectEnvTarget1$inboundSchema),
        EditProjectEnvTarget2$inboundSchema,
    ])),
    key: types.string(),
    gitBranch: types.optional(types.string()),
    updatedBy: z.nullable(types.string()).optional(),
    sunsetSecretId: types.optional(types.string()),
    legacyValue: types.optional(types.string()),
    decrypted: types.optional(types.boolean()),
    configurationId: z.nullable(types.string()).optional(),
    contentHint: z.nullable(z.union([
        z.lazy(() => ContentHint1$inboundSchema),
        z.lazy(() => ContentHint2$inboundSchema),
        z.lazy(() => ContentHint3$inboundSchema),
        z.lazy(() => ContentHint4$inboundSchema),
        z.lazy(() => ContentHint5$inboundSchema),
        z.lazy(() => ContentHint6$inboundSchema),
        z.lazy(() => ContentHint7$inboundSchema),
        z.lazy(() => ContentHint8$inboundSchema),
        z.lazy(() => ContentHint9$inboundSchema),
        z.lazy(() => ContentHint10$inboundSchema),
        z.lazy(() => ContentHint11$inboundSchema),
        z.lazy(() => ContentHint12$inboundSchema),
        z.lazy(() => ContentHint13$inboundSchema),
        z.lazy(() => ContentHint14$inboundSchema),
        z.lazy(() => ContentHint15$inboundSchema),
    ])).optional(),
    internalContentHint: z.nullable(z.lazy(() => InternalContentHint$inboundSchema)).optional(),
    comment: types.optional(types.string()),
    customEnvironmentIds: types.optional(z.array(types.string())),
});
/** @internal */
export const EditProjectEnvResponseBody$outboundSchema = z.object({
    type: EditProjectEnvProjectsType$outboundSchema,
    value: z.string(),
    edgeConfigId: z.nullable(z.string()).optional(),
    edgeConfigTokenId: z.nullable(z.string()).optional(),
    createdAt: z.number().optional(),
    updatedAt: z.number().optional(),
    id: z.string().optional(),
    createdBy: z.nullable(z.string()).optional(),
    target: smartUnion([
        z.array(EditProjectEnvTarget1$outboundSchema),
        EditProjectEnvTarget2$outboundSchema,
    ]).optional(),
    key: z.string(),
    gitBranch: z.string().optional(),
    updatedBy: z.nullable(z.string()).optional(),
    sunsetSecretId: z.string().optional(),
    legacyValue: z.string().optional(),
    decrypted: z.boolean().optional(),
    configurationId: z.nullable(z.string()).optional(),
    contentHint: z.nullable(z.union([
        z.lazy(() => ContentHint1$outboundSchema),
        z.lazy(() => ContentHint2$outboundSchema),
        z.lazy(() => ContentHint3$outboundSchema),
        z.lazy(() => ContentHint4$outboundSchema),
        z.lazy(() => ContentHint5$outboundSchema),
        z.lazy(() => ContentHint6$outboundSchema),
        z.lazy(() => ContentHint7$outboundSchema),
        z.lazy(() => ContentHint8$outboundSchema),
        z.lazy(() => ContentHint9$outboundSchema),
        z.lazy(() => ContentHint10$outboundSchema),
        z.lazy(() => ContentHint11$outboundSchema),
        z.lazy(() => ContentHint12$outboundSchema),
        z.lazy(() => ContentHint13$outboundSchema),
        z.lazy(() => ContentHint14$outboundSchema),
        z.lazy(() => ContentHint15$outboundSchema),
    ])).optional(),
    internalContentHint: z.nullable(z.lazy(() => InternalContentHint$outboundSchema)).optional(),
    comment: z.string().optional(),
    customEnvironmentIds: z.array(z.string()).optional(),
});
export function editProjectEnvResponseBodyToJSON(editProjectEnvResponseBody) {
    return JSON.stringify(EditProjectEnvResponseBody$outboundSchema.parse(editProjectEnvResponseBody));
}
export function editProjectEnvResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => EditProjectEnvResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'EditProjectEnvResponseBody' from JSON`);
}
//# sourceMappingURL=editprojectenvop.js.map