/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
import { AuthToken$inboundSchema, AuthToken$outboundSchema, } from "./authtoken.js";
/** @internal */
export const GetAuthTokenRequest$inboundSchema = z.object({
    tokenId: types.string(),
});
/** @internal */
export const GetAuthTokenRequest$outboundSchema = z.object({
    tokenId: z.string(),
});
export function getAuthTokenRequestToJSON(getAuthTokenRequest) {
    return JSON.stringify(GetAuthTokenRequest$outboundSchema.parse(getAuthTokenRequest));
}
export function getAuthTokenRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetAuthTokenRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetAuthTokenRequest' from JSON`);
}
/** @internal */
export const GetAuthTokenResponseBody$inboundSchema = z.object({
    token: AuthToken$inboundSchema,
});
/** @internal */
export const GetAuthTokenResponseBody$outboundSchema = z.object({
    token: AuthToken$outboundSchema,
});
export function getAuthTokenResponseBodyToJSON(getAuthTokenResponseBody) {
    return JSON.stringify(GetAuthTokenResponseBody$outboundSchema.parse(getAuthTokenResponseBody));
}
export function getAuthTokenResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetAuthTokenResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetAuthTokenResponseBody' from JSON`);
}
//# sourceMappingURL=getauthtokenop.js.map