/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
/**
 * The configuration status. Optional. If not defined, assume 'ready'.
 */
export const GetConfigurationResponseBodyIntegrationsResponseStatus = {
    Error: "error",
    Ready: "ready",
    Pending: "pending",
    Onboarding: "onboarding",
    Suspended: "suspended",
    Resumed: "resumed",
    Uninstalled: "uninstalled",
};
/**
 * Source defines where the configuration was installed from. It is used to analyze user engagement for integration installations in product metrics.
 */
export const GetConfigurationResponseBodyIntegrationsResponseSource = {
    Marketplace: "marketplace",
    DeployButton: "deploy-button",
    External: "external",
    V0: "v0",
    ResourceClaims: "resource-claims",
    Cli: "cli",
    Oauth: "oauth",
    Backoffice: "backoffice",
};
export const GetConfigurationResponseBodyIntegrationsResponseType = {
    IntegrationConfiguration: "integration-configuration",
};
export const GetConfigurationResponseBodyIntegrationsResponseDisabledReason = {
    DisabledByOwner: "disabled-by-owner",
    FeatureNotAvailable: "feature-not-available",
    DisabledByAdmin: "disabled-by-admin",
    OriginalOwnerLeftTheTeam: "original-owner-left-the-team",
    AccountPlanDowngrade: "account-plan-downgrade",
    OriginalOwnerRoleDowngraded: "original-owner-role-downgraded",
};
/**
 * Defines the installation type. - 'external' integrations are installed via the existing integrations flow - 'marketplace' integrations are natively installed: - when accepting the TOS of a partner during the store creation process - if undefined, assume 'external'
 */
export const GetConfigurationResponseBodyIntegrationsResponseInstallationType = {
    Marketplace: "marketplace",
    External: "external",
};
/**
 * The configuration status. Optional. If not defined, assume 'ready'.
 */
export const GetConfigurationResponseBodyIntegrationsStatus = {
    Error: "error",
    Ready: "ready",
    Pending: "pending",
    Onboarding: "onboarding",
    Suspended: "suspended",
    Resumed: "resumed",
    Uninstalled: "uninstalled",
};
/**
 * Source defines where the configuration was installed from. It is used to analyze user engagement for integration installations in product metrics.
 */
export const GetConfigurationResponseBodyIntegrationsSource = {
    Marketplace: "marketplace",
    DeployButton: "deploy-button",
    External: "external",
    V0: "v0",
    ResourceClaims: "resource-claims",
    Cli: "cli",
    Oauth: "oauth",
    Backoffice: "backoffice",
};
export const GetConfigurationResponseBodyIntegrationsType = {
    IntegrationConfiguration: "integration-configuration",
};
export const GetConfigurationResponseBodyIntegrationsDisabledReason = {
    DisabledByOwner: "disabled-by-owner",
    FeatureNotAvailable: "feature-not-available",
    DisabledByAdmin: "disabled-by-admin",
    OriginalOwnerLeftTheTeam: "original-owner-left-the-team",
    AccountPlanDowngrade: "account-plan-downgrade",
    OriginalOwnerRoleDowngraded: "original-owner-role-downgraded",
};
/**
 * Defines the installation type. - 'external' integrations are installed via the existing integrations flow - 'marketplace' integrations are natively installed: - when accepting the TOS of a partner during the store creation process - if undefined, assume 'external'
 */
export const GetConfigurationResponseBodyIntegrationsInstallationType = {
    Marketplace: "marketplace",
    External: "external",
};
/**
 * A string representing the permission for projects. Possible values are `all` or `selected`.
 */
export const ProjectSelection = {
    Selected: "selected",
    All: "all",
};
export const GetConfigurationResponseBodyLevel = {
    Error: "error",
    Info: "info",
    Warn: "warn",
};
export const TransferRequestType = {
    Prepayment: "prepayment",
    Subscription: "subscription",
};
export const TransferRequestScope = {
    Installation: "installation",
    Resource: "resource",
};
/**
 * The configuration status. Optional. If not defined, assume 'ready'.
 */
export const GetConfigurationResponseBodyStatus = {
    Error: "error",
    Ready: "ready",
    Pending: "pending",
    Onboarding: "onboarding",
    Suspended: "suspended",
    Resumed: "resumed",
    Uninstalled: "uninstalled",
};
export const GetConfigurationResponseBodyType = {
    IntegrationConfiguration: "integration-configuration",
};
/**
 * Source defines where the configuration was installed from. It is used to analyze user engagement for integration installations in product metrics.
 */
export const GetConfigurationResponseBodySource = {
    Marketplace: "marketplace",
    DeployButton: "deploy-button",
    External: "external",
    V0: "v0",
    ResourceClaims: "resource-claims",
    Cli: "cli",
    Oauth: "oauth",
    Backoffice: "backoffice",
};
export const GetConfigurationResponseBodyDisabledReason = {
    DisabledByOwner: "disabled-by-owner",
    FeatureNotAvailable: "feature-not-available",
    DisabledByAdmin: "disabled-by-admin",
    OriginalOwnerLeftTheTeam: "original-owner-left-the-team",
    AccountPlanDowngrade: "account-plan-downgrade",
    OriginalOwnerRoleDowngraded: "original-owner-role-downgraded",
};
/**
 * Defines the installation type. - 'external' integrations are installed via the existing integrations flow - 'marketplace' integrations are natively installed: - when accepting the TOS of a partner during the store creation process - if undefined, assume 'external'
 */
export const GetConfigurationResponseBodyInstallationType = {
    Marketplace: "marketplace",
    External: "external",
};
/** @internal */
export const GetConfigurationRequest$inboundSchema = z.object({
    id: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
});
/** @internal */
export const GetConfigurationRequest$outboundSchema = z.object({
    id: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
});
export function getConfigurationRequestToJSON(getConfigurationRequest) {
    return JSON.stringify(GetConfigurationRequest$outboundSchema.parse(getConfigurationRequest));
}
export function getConfigurationRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetConfigurationRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetConfigurationRequest' from JSON`);
}
/** @internal */
export const GetConfigurationResponseBodyIntegrationsResponseStatus$inboundSchema = z.nativeEnum(GetConfigurationResponseBodyIntegrationsResponseStatus);
/** @internal */
export const GetConfigurationResponseBodyIntegrationsResponseStatus$outboundSchema = GetConfigurationResponseBodyIntegrationsResponseStatus$inboundSchema;
/** @internal */
export const GetConfigurationResponseBodyIntegrationsResponseSource$inboundSchema = z.nativeEnum(GetConfigurationResponseBodyIntegrationsResponseSource);
/** @internal */
export const GetConfigurationResponseBodyIntegrationsResponseSource$outboundSchema = GetConfigurationResponseBodyIntegrationsResponseSource$inboundSchema;
/** @internal */
export const GetConfigurationResponseBodyIntegrationsResponseType$inboundSchema = z.nativeEnum(GetConfigurationResponseBodyIntegrationsResponseType);
/** @internal */
export const GetConfigurationResponseBodyIntegrationsResponseType$outboundSchema = GetConfigurationResponseBodyIntegrationsResponseType$inboundSchema;
/** @internal */
export const GetConfigurationResponseBodyIntegrationsResponseDisabledReason$inboundSchema = z.nativeEnum(GetConfigurationResponseBodyIntegrationsResponseDisabledReason);
/** @internal */
export const GetConfigurationResponseBodyIntegrationsResponseDisabledReason$outboundSchema = GetConfigurationResponseBodyIntegrationsResponseDisabledReason$inboundSchema;
/** @internal */
export const GetConfigurationResponseBodyIntegrationsResponseInstallationType$inboundSchema = z.nativeEnum(GetConfigurationResponseBodyIntegrationsResponseInstallationType);
/** @internal */
export const GetConfigurationResponseBodyIntegrationsResponseInstallationType$outboundSchema = GetConfigurationResponseBodyIntegrationsResponseInstallationType$inboundSchema;
/** @internal */
export const GetConfigurationResponseBody3$inboundSchema = z.object({
    completedAt: types.optional(types.number()),
    createdAt: types.optional(types.number()),
    id: types.optional(types.string()),
    integrationId: types.optional(types.string()),
    ownerId: types.optional(types.string()),
    status: types.optional(GetConfigurationResponseBodyIntegrationsResponseStatus$inboundSchema),
    externalId: types.optional(types.string()),
    projects: types.optional(z.array(types.string())),
    source: types.optional(GetConfigurationResponseBodyIntegrationsResponseSource$inboundSchema),
    slug: types.optional(types.string()),
    teamId: z.nullable(types.string()).optional(),
    type: types.optional(GetConfigurationResponseBodyIntegrationsResponseType$inboundSchema),
    updatedAt: types.optional(types.number()),
    userId: types.optional(types.string()),
    scopes: types.optional(z.array(types.string())),
    disabledAt: types.optional(types.number()),
    deletedAt: z.nullable(types.number()).optional(),
    deleteRequestedAt: z.nullable(types.number()).optional(),
    disabledReason: types.optional(GetConfigurationResponseBodyIntegrationsResponseDisabledReason$inboundSchema),
    installationType: types.optional(GetConfigurationResponseBodyIntegrationsResponseInstallationType$inboundSchema),
});
/** @internal */
export const GetConfigurationResponseBody3$outboundSchema = z.object({
    completedAt: z.number().optional(),
    createdAt: z.number().optional(),
    id: z.string().optional(),
    integrationId: z.string().optional(),
    ownerId: z.string().optional(),
    status: GetConfigurationResponseBodyIntegrationsResponseStatus$outboundSchema
        .optional(),
    externalId: z.string().optional(),
    projects: z.array(z.string()).optional(),
    source: GetConfigurationResponseBodyIntegrationsResponseSource$outboundSchema
        .optional(),
    slug: z.string().optional(),
    teamId: z.nullable(z.string()).optional(),
    type: GetConfigurationResponseBodyIntegrationsResponseType$outboundSchema
        .optional(),
    updatedAt: z.number().optional(),
    userId: z.string().optional(),
    scopes: z.array(z.string()).optional(),
    disabledAt: z.number().optional(),
    deletedAt: z.nullable(z.number()).optional(),
    deleteRequestedAt: z.nullable(z.number()).optional(),
    disabledReason: GetConfigurationResponseBodyIntegrationsResponseDisabledReason$outboundSchema
        .optional(),
    installationType: GetConfigurationResponseBodyIntegrationsResponseInstallationType$outboundSchema
        .optional(),
});
export function getConfigurationResponseBody3ToJSON(getConfigurationResponseBody3) {
    return JSON.stringify(GetConfigurationResponseBody3$outboundSchema.parse(getConfigurationResponseBody3));
}
export function getConfigurationResponseBody3FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetConfigurationResponseBody3$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetConfigurationResponseBody3' from JSON`);
}
/** @internal */
export const GetConfigurationResponseBodyIntegrationsStatus$inboundSchema = z
    .nativeEnum(GetConfigurationResponseBodyIntegrationsStatus);
/** @internal */
export const GetConfigurationResponseBodyIntegrationsStatus$outboundSchema = GetConfigurationResponseBodyIntegrationsStatus$inboundSchema;
/** @internal */
export const GetConfigurationResponseBodyIntegrationsSource$inboundSchema = z
    .nativeEnum(GetConfigurationResponseBodyIntegrationsSource);
/** @internal */
export const GetConfigurationResponseBodyIntegrationsSource$outboundSchema = GetConfigurationResponseBodyIntegrationsSource$inboundSchema;
/** @internal */
export const GetConfigurationResponseBodyIntegrationsType$inboundSchema = z
    .nativeEnum(GetConfigurationResponseBodyIntegrationsType);
/** @internal */
export const GetConfigurationResponseBodyIntegrationsType$outboundSchema = GetConfigurationResponseBodyIntegrationsType$inboundSchema;
/** @internal */
export const GetConfigurationResponseBodyIntegrationsDisabledReason$inboundSchema = z.nativeEnum(GetConfigurationResponseBodyIntegrationsDisabledReason);
/** @internal */
export const GetConfigurationResponseBodyIntegrationsDisabledReason$outboundSchema = GetConfigurationResponseBodyIntegrationsDisabledReason$inboundSchema;
/** @internal */
export const GetConfigurationResponseBodyIntegrationsInstallationType$inboundSchema = z.nativeEnum(GetConfigurationResponseBodyIntegrationsInstallationType);
/** @internal */
export const GetConfigurationResponseBodyIntegrationsInstallationType$outboundSchema = GetConfigurationResponseBodyIntegrationsInstallationType$inboundSchema;
/** @internal */
export const GetConfigurationResponseBody2$inboundSchema = z.object({
    completedAt: types.optional(types.number()),
    createdAt: types.number(),
    id: types.string(),
    integrationId: types.string(),
    ownerId: types.string(),
    status: types.optional(GetConfigurationResponseBodyIntegrationsStatus$inboundSchema),
    externalId: types.optional(types.string()),
    projects: types.optional(z.array(types.string())),
    source: types.optional(GetConfigurationResponseBodyIntegrationsSource$inboundSchema),
    slug: types.string(),
    teamId: z.nullable(types.string()).optional(),
    type: GetConfigurationResponseBodyIntegrationsType$inboundSchema,
    updatedAt: types.number(),
    userId: types.string(),
    scopes: z.array(types.string()),
    disabledAt: types.optional(types.number()),
    deletedAt: z.nullable(types.number()).optional(),
    deleteRequestedAt: z.nullable(types.number()).optional(),
    disabledReason: types.optional(GetConfigurationResponseBodyIntegrationsDisabledReason$inboundSchema),
    installationType: types.optional(GetConfigurationResponseBodyIntegrationsInstallationType$inboundSchema),
});
/** @internal */
export const GetConfigurationResponseBody2$outboundSchema = z.object({
    completedAt: z.number().optional(),
    createdAt: z.number(),
    id: z.string(),
    integrationId: z.string(),
    ownerId: z.string(),
    status: GetConfigurationResponseBodyIntegrationsStatus$outboundSchema
        .optional(),
    externalId: z.string().optional(),
    projects: z.array(z.string()).optional(),
    source: GetConfigurationResponseBodyIntegrationsSource$outboundSchema
        .optional(),
    slug: z.string(),
    teamId: z.nullable(z.string()).optional(),
    type: GetConfigurationResponseBodyIntegrationsType$outboundSchema,
    updatedAt: z.number(),
    userId: z.string(),
    scopes: z.array(z.string()),
    disabledAt: z.number().optional(),
    deletedAt: z.nullable(z.number()).optional(),
    deleteRequestedAt: z.nullable(z.number()).optional(),
    disabledReason: GetConfigurationResponseBodyIntegrationsDisabledReason$outboundSchema
        .optional(),
    installationType: GetConfigurationResponseBodyIntegrationsInstallationType$outboundSchema
        .optional(),
});
export function getConfigurationResponseBody2ToJSON(getConfigurationResponseBody2) {
    return JSON.stringify(GetConfigurationResponseBody2$outboundSchema.parse(getConfigurationResponseBody2));
}
export function getConfigurationResponseBody2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetConfigurationResponseBody2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetConfigurationResponseBody2' from JSON`);
}
/** @internal */
export const ProjectSelection$inboundSchema = z.nativeEnum(ProjectSelection);
/** @internal */
export const ProjectSelection$outboundSchema = ProjectSelection$inboundSchema;
/** @internal */
export const GetConfigurationResponseBodyLevel$inboundSchema = z.nativeEnum(GetConfigurationResponseBodyLevel);
/** @internal */
export const GetConfigurationResponseBodyLevel$outboundSchema = GetConfigurationResponseBodyLevel$inboundSchema;
/** @internal */
export const ResponseBodyNotification$inboundSchema = z.object({
    level: GetConfigurationResponseBodyLevel$inboundSchema,
    title: types.string(),
    message: types.optional(types.string()),
    href: types.optional(types.string()),
});
/** @internal */
export const ResponseBodyNotification$outboundSchema = z.object({
    level: GetConfigurationResponseBodyLevel$outboundSchema,
    title: z.string(),
    message: z.string().optional(),
    href: z.string().optional(),
});
export function responseBodyNotificationToJSON(responseBodyNotification) {
    return JSON.stringify(ResponseBodyNotification$outboundSchema.parse(responseBodyNotification));
}
export function responseBodyNotificationFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ResponseBodyNotification$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ResponseBodyNotification' from JSON`);
}
/** @internal */
export const TransferRequestRequester$inboundSchema = z.object({
    name: types.string(),
    email: types.optional(types.string()),
});
/** @internal */
export const TransferRequestRequester$outboundSchema = z.object({
    name: z.string(),
    email: z.string().optional(),
});
export function transferRequestRequesterToJSON(transferRequestRequester) {
    return JSON.stringify(TransferRequestRequester$outboundSchema.parse(transferRequestRequester));
}
export function transferRequestRequesterFromJSON(jsonString) {
    return safeParse(jsonString, (x) => TransferRequestRequester$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'TransferRequestRequester' from JSON`);
}
/** @internal */
export const TransferRequest2$inboundSchema = z.object({
    kind: types.literal("transfer-from-marketplace"),
    requestId: types.string(),
    transferId: types.string(),
    requester: z.lazy(() => TransferRequestRequester$inboundSchema),
    createdAt: types.number(),
    expiresAt: types.number(),
    discardedAt: types.optional(types.number()),
    discardedBy: types.optional(types.string()),
    approvedAt: types.optional(types.number()),
    approvedBy: types.optional(types.string()),
    authorizationId: types.optional(types.string()),
});
/** @internal */
export const TransferRequest2$outboundSchema = z.object({
    kind: z.literal("transfer-from-marketplace"),
    requestId: z.string(),
    transferId: z.string(),
    requester: z.lazy(() => TransferRequestRequester$outboundSchema),
    createdAt: z.number(),
    expiresAt: z.number(),
    discardedAt: z.number().optional(),
    discardedBy: z.string().optional(),
    approvedAt: z.number().optional(),
    approvedBy: z.string().optional(),
    authorizationId: z.string().optional(),
});
export function transferRequest2ToJSON(transferRequest2) {
    return JSON.stringify(TransferRequest2$outboundSchema.parse(transferRequest2));
}
export function transferRequest2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => TransferRequest2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'TransferRequest2' from JSON`);
}
/** @internal */
export const TransferRequestType$inboundSchema = z.nativeEnum(TransferRequestType);
/** @internal */
export const TransferRequestType$outboundSchema = TransferRequestType$inboundSchema;
/** @internal */
export const TransferRequestScope$inboundSchema = z.nativeEnum(TransferRequestScope);
/** @internal */
export const TransferRequestScope$outboundSchema = TransferRequestScope$inboundSchema;
/** @internal */
export const TransferRequestBillingPlan$inboundSchema = z.object({
    id: types.string(),
    type: TransferRequestType$inboundSchema,
    scope: types.optional(TransferRequestScope$inboundSchema),
    name: types.string(),
    description: types.string(),
    paymentMethodRequired: types.optional(types.boolean()),
    preauthorizationAmount: types.optional(types.number()),
});
/** @internal */
export const TransferRequestBillingPlan$outboundSchema = z.object({
    id: z.string(),
    type: TransferRequestType$outboundSchema,
    scope: TransferRequestScope$outboundSchema.optional(),
    name: z.string(),
    description: z.string(),
    paymentMethodRequired: z.boolean().optional(),
    preauthorizationAmount: z.number().optional(),
});
export function transferRequestBillingPlanToJSON(transferRequestBillingPlan) {
    return JSON.stringify(TransferRequestBillingPlan$outboundSchema.parse(transferRequestBillingPlan));
}
export function transferRequestBillingPlanFromJSON(jsonString) {
    return safeParse(jsonString, (x) => TransferRequestBillingPlan$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'TransferRequestBillingPlan' from JSON`);
}
/** @internal */
export const Requester$inboundSchema = z.object({
    name: types.string(),
    email: types.optional(types.string()),
});
/** @internal */
export const Requester$outboundSchema = z.object({
    name: z.string(),
    email: z.string().optional(),
});
export function requesterToJSON(requester) {
    return JSON.stringify(Requester$outboundSchema.parse(requester));
}
export function requesterFromJSON(jsonString) {
    return safeParse(jsonString, (x) => Requester$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'Requester' from JSON`);
}
/** @internal */
export const TransferRequest1$inboundSchema = z.object({
    kind: types.literal("transfer-to-marketplace"),
    metadata: types.optional(z.record(z.any())),
    billingPlan: types.optional(z.lazy(() => TransferRequestBillingPlan$inboundSchema)),
    requestId: types.string(),
    transferId: types.string(),
    requester: z.lazy(() => Requester$inboundSchema),
    createdAt: types.number(),
    expiresAt: types.number(),
    discardedAt: types.optional(types.number()),
    discardedBy: types.optional(types.string()),
    approvedAt: types.optional(types.number()),
    approvedBy: types.optional(types.string()),
    authorizationId: types.optional(types.string()),
});
/** @internal */
export const TransferRequest1$outboundSchema = z.object({
    kind: z.literal("transfer-to-marketplace"),
    metadata: z.record(z.any()).optional(),
    billingPlan: z.lazy(() => TransferRequestBillingPlan$outboundSchema)
        .optional(),
    requestId: z.string(),
    transferId: z.string(),
    requester: z.lazy(() => Requester$outboundSchema),
    createdAt: z.number(),
    expiresAt: z.number(),
    discardedAt: z.number().optional(),
    discardedBy: z.string().optional(),
    approvedAt: z.number().optional(),
    approvedBy: z.string().optional(),
    authorizationId: z.string().optional(),
});
export function transferRequest1ToJSON(transferRequest1) {
    return JSON.stringify(TransferRequest1$outboundSchema.parse(transferRequest1));
}
export function transferRequest1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => TransferRequest1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'TransferRequest1' from JSON`);
}
/** @internal */
export const TransferRequest$inboundSchema = z.union([
    z.lazy(() => TransferRequest1$inboundSchema),
    z.lazy(() => TransferRequest2$inboundSchema),
]);
/** @internal */
export const TransferRequest$outboundSchema = z.union([
    z.lazy(() => TransferRequest1$outboundSchema),
    z.lazy(() => TransferRequest2$outboundSchema),
]);
export function transferRequestToJSON(transferRequest) {
    return JSON.stringify(TransferRequest$outboundSchema.parse(transferRequest));
}
export function transferRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => TransferRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'TransferRequest' from JSON`);
}
/** @internal */
export const GetConfigurationResponseBodyStatus$inboundSchema = z.nativeEnum(GetConfigurationResponseBodyStatus);
/** @internal */
export const GetConfigurationResponseBodyStatus$outboundSchema = GetConfigurationResponseBodyStatus$inboundSchema;
/** @internal */
export const GetConfigurationResponseBodyType$inboundSchema = z.nativeEnum(GetConfigurationResponseBodyType);
/** @internal */
export const GetConfigurationResponseBodyType$outboundSchema = GetConfigurationResponseBodyType$inboundSchema;
/** @internal */
export const GetConfigurationResponseBodySource$inboundSchema = z.nativeEnum(GetConfigurationResponseBodySource);
/** @internal */
export const GetConfigurationResponseBodySource$outboundSchema = GetConfigurationResponseBodySource$inboundSchema;
/** @internal */
export const GetConfigurationResponseBodyDisabledReason$inboundSchema = z
    .nativeEnum(GetConfigurationResponseBodyDisabledReason);
/** @internal */
export const GetConfigurationResponseBodyDisabledReason$outboundSchema = GetConfigurationResponseBodyDisabledReason$inboundSchema;
/** @internal */
export const GetConfigurationResponseBodyInstallationType$inboundSchema = z
    .nativeEnum(GetConfigurationResponseBodyInstallationType);
/** @internal */
export const GetConfigurationResponseBodyInstallationType$outboundSchema = GetConfigurationResponseBodyInstallationType$inboundSchema;
/** @internal */
export const GetConfigurationResponseBody1$inboundSchema = z.object({
    projectSelection: ProjectSelection$inboundSchema,
    notification: z.lazy(() => ResponseBodyNotification$inboundSchema),
    transferRequest: z.union([
        z.lazy(() => TransferRequest1$inboundSchema),
        z.lazy(() => TransferRequest2$inboundSchema),
    ]),
    projects: types.optional(z.array(types.string())),
    status: types.optional(GetConfigurationResponseBodyStatus$inboundSchema),
    type: GetConfigurationResponseBodyType$inboundSchema,
    createdAt: types.number(),
    deletedAt: z.nullable(types.number()).optional(),
    id: types.string(),
    slug: types.string(),
    teamId: z.nullable(types.string()).optional(),
    updatedAt: types.number(),
    userId: types.string(),
    scopes: z.array(types.string()),
    source: types.optional(GetConfigurationResponseBodySource$inboundSchema),
    integrationId: types.string(),
    ownerId: types.string(),
    canConfigureOpenTelemetry: types.optional(types.boolean()),
    completedAt: types.optional(types.number()),
    externalId: types.optional(types.string()),
    disabledAt: types.optional(types.number()),
    deleteRequestedAt: z.nullable(types.number()).optional(),
    disabledReason: types.optional(GetConfigurationResponseBodyDisabledReason$inboundSchema),
    installationType: types.optional(GetConfigurationResponseBodyInstallationType$inboundSchema),
});
/** @internal */
export const GetConfigurationResponseBody1$outboundSchema = z.object({
    projectSelection: ProjectSelection$outboundSchema,
    notification: z.lazy(() => ResponseBodyNotification$outboundSchema),
    transferRequest: z.union([
        z.lazy(() => TransferRequest1$outboundSchema),
        z.lazy(() => TransferRequest2$outboundSchema),
    ]),
    projects: z.array(z.string()).optional(),
    status: GetConfigurationResponseBodyStatus$outboundSchema.optional(),
    type: GetConfigurationResponseBodyType$outboundSchema,
    createdAt: z.number(),
    deletedAt: z.nullable(z.number()).optional(),
    id: z.string(),
    slug: z.string(),
    teamId: z.nullable(z.string()).optional(),
    updatedAt: z.number(),
    userId: z.string(),
    scopes: z.array(z.string()),
    source: GetConfigurationResponseBodySource$outboundSchema.optional(),
    integrationId: z.string(),
    ownerId: z.string(),
    canConfigureOpenTelemetry: z.boolean().optional(),
    completedAt: z.number().optional(),
    externalId: z.string().optional(),
    disabledAt: z.number().optional(),
    deleteRequestedAt: z.nullable(z.number()).optional(),
    disabledReason: GetConfigurationResponseBodyDisabledReason$outboundSchema
        .optional(),
    installationType: GetConfigurationResponseBodyInstallationType$outboundSchema
        .optional(),
});
export function getConfigurationResponseBody1ToJSON(getConfigurationResponseBody1) {
    return JSON.stringify(GetConfigurationResponseBody1$outboundSchema.parse(getConfigurationResponseBody1));
}
export function getConfigurationResponseBody1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetConfigurationResponseBody1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetConfigurationResponseBody1' from JSON`);
}
/** @internal */
export const GetConfigurationResponseBody$inboundSchema = smartUnion([
    z.lazy(() => GetConfigurationResponseBody1$inboundSchema),
    z.lazy(() => GetConfigurationResponseBody2$inboundSchema),
    z.lazy(() => GetConfigurationResponseBody3$inboundSchema),
]);
/** @internal */
export const GetConfigurationResponseBody$outboundSchema = smartUnion([
    z.lazy(() => GetConfigurationResponseBody1$outboundSchema),
    z.lazy(() => GetConfigurationResponseBody2$outboundSchema),
    z.lazy(() => GetConfigurationResponseBody3$outboundSchema),
]);
export function getConfigurationResponseBodyToJSON(getConfigurationResponseBody) {
    return JSON.stringify(GetConfigurationResponseBody$outboundSchema.parse(getConfigurationResponseBody));
}
export function getConfigurationResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetConfigurationResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetConfigurationResponseBody' from JSON`);
}
//# sourceMappingURL=getconfigurationop.js.map