/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
import { SandboxCommand$inboundSchema, SandboxCommand$outboundSchema, } from "./sandboxcommand.js";
/**
 * If set to \"true\", the request will block until the command finishes execution. Useful for synchronously waiting for command completion.
 */
export const Wait = {
    True: "true",
    False: "false",
};
/** @internal */
export const Wait$inboundSchema = z.nativeEnum(Wait);
/** @internal */
export const Wait$outboundSchema = Wait$inboundSchema;
/** @internal */
export const GetCommandRequest$inboundSchema = z.object({
    sandboxId: types.string(),
    cmdId: types.string(),
    wait: Wait$inboundSchema.default("false"),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
});
/** @internal */
export const GetCommandRequest$outboundSchema = z.object({
    sandboxId: z.string(),
    cmdId: z.string(),
    wait: Wait$outboundSchema.default("false"),
    teamId: z.string().optional(),
    slug: z.string().optional(),
});
export function getCommandRequestToJSON(getCommandRequest) {
    return JSON.stringify(GetCommandRequest$outboundSchema.parse(getCommandRequest));
}
export function getCommandRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetCommandRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetCommandRequest' from JSON`);
}
/** @internal */
export const GetCommandResponseBody$inboundSchema = z.object({
    command: SandboxCommand$inboundSchema,
});
/** @internal */
export const GetCommandResponseBody$outboundSchema = z.object({
    command: SandboxCommand$outboundSchema,
});
export function getCommandResponseBodyToJSON(getCommandResponseBody) {
    return JSON.stringify(GetCommandResponseBody$outboundSchema.parse(getCommandResponseBody));
}
export function getCommandResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetCommandResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetCommandResponseBody' from JSON`);
}
//# sourceMappingURL=getcommandop.js.map