/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
export const GetDeploymentCheckRunSourceProvider = {
    Github: "github",
    Gitlab: "gitlab",
    Bitbucket: "bitbucket",
};
export const GetDeploymentCheckRunRequires = {
    BuildReady: "build-ready",
    DeploymentUrl: "deployment-url",
    None: "none",
};
export const GetDeploymentCheckRunBlocks = {
    None: "none",
    BuildStart: "build-start",
    DeploymentStart: "deployment-start",
    DeploymentAlias: "deployment-alias",
    DeploymentPromotion: "deployment-promotion",
};
export const GetDeploymentCheckRunStatus = {
    Queued: "queued",
    Running: "running",
    Completed: "completed",
};
export const GetDeploymentCheckRunConclusion = {
    Timeout: "timeout",
    Canceled: "canceled",
    Skipped: "skipped",
    Failed: "failed",
    Neutral: "neutral",
    Succeeded: "succeeded",
};
/** @internal */
export const GetDeploymentCheckRunRequest$inboundSchema = z.object({
    deploymentId: types.string(),
    checkRunId: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
});
/** @internal */
export const GetDeploymentCheckRunRequest$outboundSchema = z.object({
    deploymentId: z.string(),
    checkRunId: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
});
export function getDeploymentCheckRunRequestToJSON(getDeploymentCheckRunRequest) {
    return JSON.stringify(GetDeploymentCheckRunRequest$outboundSchema.parse(getDeploymentCheckRunRequest));
}
export function getDeploymentCheckRunRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetDeploymentCheckRunRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetDeploymentCheckRunRequest' from JSON`);
}
/** @internal */
export const GetDeploymentCheckRunSourceProvider$inboundSchema = z.nativeEnum(GetDeploymentCheckRunSourceProvider);
/** @internal */
export const GetDeploymentCheckRunSourceProvider$outboundSchema = GetDeploymentCheckRunSourceProvider$inboundSchema;
/** @internal */
export const GetDeploymentCheckRunSource3$inboundSchema = z.object({
    kind: types.literal("git-provider"),
    provider: GetDeploymentCheckRunSourceProvider$inboundSchema,
    externalCheckName: types.string(),
});
/** @internal */
export const GetDeploymentCheckRunSource3$outboundSchema = z.object({
    kind: z.literal("git-provider"),
    provider: GetDeploymentCheckRunSourceProvider$outboundSchema,
    externalCheckName: z.string(),
});
export function getDeploymentCheckRunSource3ToJSON(getDeploymentCheckRunSource3) {
    return JSON.stringify(GetDeploymentCheckRunSource3$outboundSchema.parse(getDeploymentCheckRunSource3));
}
export function getDeploymentCheckRunSource3FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetDeploymentCheckRunSource3$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetDeploymentCheckRunSource3' from JSON`);
}
/** @internal */
export const GetDeploymentCheckRunSource2$inboundSchema = z.object({
    kind: types.literal("webhook"),
    webhookId: types.optional(types.string()),
});
/** @internal */
export const GetDeploymentCheckRunSource2$outboundSchema = z.object({
    kind: z.literal("webhook"),
    webhookId: z.string().optional(),
});
export function getDeploymentCheckRunSource2ToJSON(getDeploymentCheckRunSource2) {
    return JSON.stringify(GetDeploymentCheckRunSource2$outboundSchema.parse(getDeploymentCheckRunSource2));
}
export function getDeploymentCheckRunSource2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetDeploymentCheckRunSource2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetDeploymentCheckRunSource2' from JSON`);
}
/** @internal */
export const GetDeploymentCheckRunSource1$inboundSchema = z.object({
    kind: types.literal("integration"),
    integrationId: types.string(),
    integrationConfigurationId: types.string(),
    resourceId: types.optional(types.string()),
    externalResourceId: types.optional(types.string()),
});
/** @internal */
export const GetDeploymentCheckRunSource1$outboundSchema = z.object({
    kind: z.literal("integration"),
    integrationId: z.string(),
    integrationConfigurationId: z.string(),
    resourceId: z.string().optional(),
    externalResourceId: z.string().optional(),
});
export function getDeploymentCheckRunSource1ToJSON(getDeploymentCheckRunSource1) {
    return JSON.stringify(GetDeploymentCheckRunSource1$outboundSchema.parse(getDeploymentCheckRunSource1));
}
export function getDeploymentCheckRunSource1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetDeploymentCheckRunSource1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetDeploymentCheckRunSource1' from JSON`);
}
/** @internal */
export const GetDeploymentCheckRunSource$inboundSchema = z.union([
    z.lazy(() => GetDeploymentCheckRunSource1$inboundSchema),
    z.lazy(() => GetDeploymentCheckRunSource2$inboundSchema),
    z.lazy(() => GetDeploymentCheckRunSource3$inboundSchema),
]);
/** @internal */
export const GetDeploymentCheckRunSource$outboundSchema = z.union([
    z.lazy(() => GetDeploymentCheckRunSource1$outboundSchema),
    z.lazy(() => GetDeploymentCheckRunSource2$outboundSchema),
    z.lazy(() => GetDeploymentCheckRunSource3$outboundSchema),
]);
export function getDeploymentCheckRunSourceToJSON(getDeploymentCheckRunSource) {
    return JSON.stringify(GetDeploymentCheckRunSource$outboundSchema.parse(getDeploymentCheckRunSource));
}
export function getDeploymentCheckRunSourceFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetDeploymentCheckRunSource$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetDeploymentCheckRunSource' from JSON`);
}
/** @internal */
export const GetDeploymentCheckRunRequires$inboundSchema = z.nativeEnum(GetDeploymentCheckRunRequires);
/** @internal */
export const GetDeploymentCheckRunRequires$outboundSchema = GetDeploymentCheckRunRequires$inboundSchema;
/** @internal */
export const GetDeploymentCheckRunBlocks$inboundSchema = z.nativeEnum(GetDeploymentCheckRunBlocks);
/** @internal */
export const GetDeploymentCheckRunBlocks$outboundSchema = GetDeploymentCheckRunBlocks$inboundSchema;
/** @internal */
export const GetDeploymentCheckRunStatus$inboundSchema = z.nativeEnum(GetDeploymentCheckRunStatus);
/** @internal */
export const GetDeploymentCheckRunStatus$outboundSchema = GetDeploymentCheckRunStatus$inboundSchema;
/** @internal */
export const GetDeploymentCheckRunConclusion$inboundSchema = z.nativeEnum(GetDeploymentCheckRunConclusion);
/** @internal */
export const GetDeploymentCheckRunConclusion$outboundSchema = GetDeploymentCheckRunConclusion$inboundSchema;
/** @internal */
export const GetDeploymentCheckRunResponseBody$inboundSchema = z.object({
    id: types.string(),
    name: types.string(),
    checkId: types.string(),
    ownerId: types.string(),
    deploymentId: types.string(),
    projectId: types.optional(types.string()),
    source: z.union([
        z.lazy(() => GetDeploymentCheckRunSource1$inboundSchema),
        z.lazy(() => GetDeploymentCheckRunSource2$inboundSchema),
        z.lazy(() => GetDeploymentCheckRunSource3$inboundSchema),
    ]),
    requires: types.optional(GetDeploymentCheckRunRequires$inboundSchema),
    blocks: types.optional(GetDeploymentCheckRunBlocks$inboundSchema),
    targets: types.optional(z.array(types.string())),
    status: GetDeploymentCheckRunStatus$inboundSchema,
    conclusion: types.optional(GetDeploymentCheckRunConclusion$inboundSchema),
    conclusionText: types.optional(types.string()),
    externalId: types.optional(types.string()),
    externalUrl: types.optional(types.string()),
    output: types.optional(z.record(z.any())),
    timeout: types.number(),
    createdAt: types.number(),
    updatedAt: types.number(),
    completedAt: types.optional(types.number()),
});
/** @internal */
export const GetDeploymentCheckRunResponseBody$outboundSchema = z.object({
    id: z.string(),
    name: z.string(),
    checkId: z.string(),
    ownerId: z.string(),
    deploymentId: z.string(),
    projectId: z.string().optional(),
    source: z.union([
        z.lazy(() => GetDeploymentCheckRunSource1$outboundSchema),
        z.lazy(() => GetDeploymentCheckRunSource2$outboundSchema),
        z.lazy(() => GetDeploymentCheckRunSource3$outboundSchema),
    ]),
    requires: GetDeploymentCheckRunRequires$outboundSchema.optional(),
    blocks: GetDeploymentCheckRunBlocks$outboundSchema.optional(),
    targets: z.array(z.string()).optional(),
    status: GetDeploymentCheckRunStatus$outboundSchema,
    conclusion: GetDeploymentCheckRunConclusion$outboundSchema.optional(),
    conclusionText: z.string().optional(),
    externalId: z.string().optional(),
    externalUrl: z.string().optional(),
    output: z.record(z.any()).optional(),
    timeout: z.number(),
    createdAt: z.number(),
    updatedAt: z.number(),
    completedAt: z.number().optional(),
});
export function getDeploymentCheckRunResponseBodyToJSON(getDeploymentCheckRunResponseBody) {
    return JSON.stringify(GetDeploymentCheckRunResponseBody$outboundSchema.parse(getDeploymentCheckRunResponseBody));
}
export function getDeploymentCheckRunResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetDeploymentCheckRunResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetDeploymentCheckRunResponseBody' from JSON`);
}
//# sourceMappingURL=getdeploymentcheckrunop.js.map