/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
export const GetProjectEnvResponseBodyProjectsType = {
    Secret: "secret",
    System: "system",
    Encrypted: "encrypted",
    Plain: "plain",
    Sensitive: "sensitive",
};
export const GetProjectEnvTargetProjects2 = {
    Production: "production",
    Preview: "preview",
    Development: "development",
};
export const GetProjectEnvTargetProjects1 = {
    Production: "production",
    Preview: "preview",
    Development: "development",
};
export const GetProjectEnvResponseBodyProjectsResponse200Type = {
    FlagsSecret: "flags-secret",
};
export const GetProjectEnvResponseBodyType = {
    Secret: "secret",
    System: "system",
    Encrypted: "encrypted",
    Plain: "plain",
    Sensitive: "sensitive",
};
export const GetProjectEnvTarget2 = {
    Production: "production",
    Preview: "preview",
    Development: "development",
};
export const GetProjectEnvTarget1 = {
    Production: "production",
    Preview: "preview",
    Development: "development",
};
export const GetProjectEnvResponseBodyProjectsResponseType = {
    FlagsSecret: "flags-secret",
};
/** @internal */
export const GetProjectEnvRequest$inboundSchema = z.object({
    idOrName: types.string(),
    id: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
});
/** @internal */
export const GetProjectEnvRequest$outboundSchema = z.object({
    idOrName: z.string(),
    id: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
});
export function getProjectEnvRequestToJSON(getProjectEnvRequest) {
    return JSON.stringify(GetProjectEnvRequest$outboundSchema.parse(getProjectEnvRequest));
}
export function getProjectEnvRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvRequest' from JSON`);
}
/** @internal */
export const GetProjectEnvResponseBodyProjectsType$inboundSchema = z.nativeEnum(GetProjectEnvResponseBodyProjectsType);
/** @internal */
export const GetProjectEnvResponseBodyProjectsType$outboundSchema = GetProjectEnvResponseBodyProjectsType$inboundSchema;
/** @internal */
export const GetProjectEnvTargetProjects2$inboundSchema = z.nativeEnum(GetProjectEnvTargetProjects2);
/** @internal */
export const GetProjectEnvTargetProjects2$outboundSchema = GetProjectEnvTargetProjects2$inboundSchema;
/** @internal */
export const GetProjectEnvTargetProjects1$inboundSchema = z.nativeEnum(GetProjectEnvTargetProjects1);
/** @internal */
export const GetProjectEnvTargetProjects1$outboundSchema = GetProjectEnvTargetProjects1$inboundSchema;
/** @internal */
export const GetProjectEnvResponseBodyProjectsTarget$inboundSchema = smartUnion([
    z.array(GetProjectEnvTargetProjects1$inboundSchema),
    GetProjectEnvTargetProjects2$inboundSchema,
]);
/** @internal */
export const GetProjectEnvResponseBodyProjectsTarget$outboundSchema = smartUnion([
    z.array(GetProjectEnvTargetProjects1$outboundSchema),
    GetProjectEnvTargetProjects2$outboundSchema,
]);
export function getProjectEnvResponseBodyProjectsTargetToJSON(getProjectEnvResponseBodyProjectsTarget) {
    return JSON.stringify(GetProjectEnvResponseBodyProjectsTarget$outboundSchema.parse(getProjectEnvResponseBodyProjectsTarget));
}
export function getProjectEnvResponseBodyProjectsTargetFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvResponseBodyProjectsTarget$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvResponseBodyProjectsTarget' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects15$inboundSchema = z.object({
    type: types.literal("flags-connection-string"),
    projectId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects15$outboundSchema = z.object({
    type: z.literal("flags-connection-string"),
    projectId: z.string(),
});
export function getProjectEnvContentHintProjects15ToJSON(getProjectEnvContentHintProjects15) {
    return JSON.stringify(GetProjectEnvContentHintProjects15$outboundSchema.parse(getProjectEnvContentHintProjects15));
}
export function getProjectEnvContentHintProjects15FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects15$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects15' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects14$inboundSchema = z.object({
    type: types.literal("integration-store-secret"),
    storeId: types.string(),
    integrationId: types.string(),
    integrationProductId: types.string(),
    integrationConfigurationId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects14$outboundSchema = z.object({
    type: z.literal("integration-store-secret"),
    storeId: z.string(),
    integrationId: z.string(),
    integrationProductId: z.string(),
    integrationConfigurationId: z.string(),
});
export function getProjectEnvContentHintProjects14ToJSON(getProjectEnvContentHintProjects14) {
    return JSON.stringify(GetProjectEnvContentHintProjects14$outboundSchema.parse(getProjectEnvContentHintProjects14));
}
export function getProjectEnvContentHintProjects14FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects14$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects14' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects13$inboundSchema = z.object({
    type: types.literal("postgres-url-no-ssl"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects13$outboundSchema = z.object({
    type: z.literal("postgres-url-no-ssl"),
    storeId: z.string(),
});
export function getProjectEnvContentHintProjects13ToJSON(getProjectEnvContentHintProjects13) {
    return JSON.stringify(GetProjectEnvContentHintProjects13$outboundSchema.parse(getProjectEnvContentHintProjects13));
}
export function getProjectEnvContentHintProjects13FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects13$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects13' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects12$inboundSchema = z.object({
    type: types.literal("postgres-database"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects12$outboundSchema = z.object({
    type: z.literal("postgres-database"),
    storeId: z.string(),
});
export function getProjectEnvContentHintProjects12ToJSON(getProjectEnvContentHintProjects12) {
    return JSON.stringify(GetProjectEnvContentHintProjects12$outboundSchema.parse(getProjectEnvContentHintProjects12));
}
export function getProjectEnvContentHintProjects12FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects12$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects12' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects11$inboundSchema = z.object({
    type: types.literal("postgres-password"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects11$outboundSchema = z.object({
    type: z.literal("postgres-password"),
    storeId: z.string(),
});
export function getProjectEnvContentHintProjects11ToJSON(getProjectEnvContentHintProjects11) {
    return JSON.stringify(GetProjectEnvContentHintProjects11$outboundSchema.parse(getProjectEnvContentHintProjects11));
}
export function getProjectEnvContentHintProjects11FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects11$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects11' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects10$inboundSchema = z.object({
    type: types.literal("postgres-host"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects10$outboundSchema = z.object({
    type: z.literal("postgres-host"),
    storeId: z.string(),
});
export function getProjectEnvContentHintProjects10ToJSON(getProjectEnvContentHintProjects10) {
    return JSON.stringify(GetProjectEnvContentHintProjects10$outboundSchema.parse(getProjectEnvContentHintProjects10));
}
export function getProjectEnvContentHintProjects10FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects10$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects10' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects9$inboundSchema = z.object({
    type: types.literal("postgres-user"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects9$outboundSchema = z.object({
    type: z.literal("postgres-user"),
    storeId: z.string(),
});
export function getProjectEnvContentHintProjects9ToJSON(getProjectEnvContentHintProjects9) {
    return JSON.stringify(GetProjectEnvContentHintProjects9$outboundSchema.parse(getProjectEnvContentHintProjects9));
}
export function getProjectEnvContentHintProjects9FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects9$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects9' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects8$inboundSchema = z.object({
    type: types.literal("postgres-prisma-url"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects8$outboundSchema = z.object({
    type: z.literal("postgres-prisma-url"),
    storeId: z.string(),
});
export function getProjectEnvContentHintProjects8ToJSON(getProjectEnvContentHintProjects8) {
    return JSON.stringify(GetProjectEnvContentHintProjects8$outboundSchema.parse(getProjectEnvContentHintProjects8));
}
export function getProjectEnvContentHintProjects8FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects8$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects8' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects7$inboundSchema = z.object({
    type: types.literal("postgres-url-non-pooling"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects7$outboundSchema = z.object({
    type: z.literal("postgres-url-non-pooling"),
    storeId: z.string(),
});
export function getProjectEnvContentHintProjects7ToJSON(getProjectEnvContentHintProjects7) {
    return JSON.stringify(GetProjectEnvContentHintProjects7$outboundSchema.parse(getProjectEnvContentHintProjects7));
}
export function getProjectEnvContentHintProjects7FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects7$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects7' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects6$inboundSchema = z.object({
    type: types.literal("postgres-url"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects6$outboundSchema = z.object({
    type: z.literal("postgres-url"),
    storeId: z.string(),
});
export function getProjectEnvContentHintProjects6ToJSON(getProjectEnvContentHintProjects6) {
    return JSON.stringify(GetProjectEnvContentHintProjects6$outboundSchema.parse(getProjectEnvContentHintProjects6));
}
export function getProjectEnvContentHintProjects6FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects6$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects6' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects5$inboundSchema = z.object({
    type: types.literal("blob-read-write-token"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects5$outboundSchema = z.object({
    type: z.literal("blob-read-write-token"),
    storeId: z.string(),
});
export function getProjectEnvContentHintProjects5ToJSON(getProjectEnvContentHintProjects5) {
    return JSON.stringify(GetProjectEnvContentHintProjects5$outboundSchema.parse(getProjectEnvContentHintProjects5));
}
export function getProjectEnvContentHintProjects5FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects5$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects5' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects4$inboundSchema = z.object({
    type: types.literal("redis-rest-api-read-only-token"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects4$outboundSchema = z.object({
    type: z.literal("redis-rest-api-read-only-token"),
    storeId: z.string(),
});
export function getProjectEnvContentHintProjects4ToJSON(getProjectEnvContentHintProjects4) {
    return JSON.stringify(GetProjectEnvContentHintProjects4$outboundSchema.parse(getProjectEnvContentHintProjects4));
}
export function getProjectEnvContentHintProjects4FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects4$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects4' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects3$inboundSchema = z.object({
    type: types.literal("redis-rest-api-token"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects3$outboundSchema = z.object({
    type: z.literal("redis-rest-api-token"),
    storeId: z.string(),
});
export function getProjectEnvContentHintProjects3ToJSON(getProjectEnvContentHintProjects3) {
    return JSON.stringify(GetProjectEnvContentHintProjects3$outboundSchema.parse(getProjectEnvContentHintProjects3));
}
export function getProjectEnvContentHintProjects3FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects3$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects3' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects2$inboundSchema = z.object({
    type: types.literal("redis-rest-api-url"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects2$outboundSchema = z.object({
    type: z.literal("redis-rest-api-url"),
    storeId: z.string(),
});
export function getProjectEnvContentHintProjects2ToJSON(getProjectEnvContentHintProjects2) {
    return JSON.stringify(GetProjectEnvContentHintProjects2$outboundSchema.parse(getProjectEnvContentHintProjects2));
}
export function getProjectEnvContentHintProjects2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects2' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHintProjects1$inboundSchema = z.object({
    type: types.literal("redis-url"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHintProjects1$outboundSchema = z.object({
    type: z.literal("redis-url"),
    storeId: z.string(),
});
export function getProjectEnvContentHintProjects1ToJSON(getProjectEnvContentHintProjects1) {
    return JSON.stringify(GetProjectEnvContentHintProjects1$outboundSchema.parse(getProjectEnvContentHintProjects1));
}
export function getProjectEnvContentHintProjects1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHintProjects1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHintProjects1' from JSON`);
}
/** @internal */
export const GetProjectEnvResponseBodyProjectsContentHint$inboundSchema = z.union([
    z.lazy(() => GetProjectEnvContentHintProjects1$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects2$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects3$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects4$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects5$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects6$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects7$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects8$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects9$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects10$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects11$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects12$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects13$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects14$inboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects15$inboundSchema),
]);
/** @internal */
export const GetProjectEnvResponseBodyProjectsContentHint$outboundSchema = z.union([
    z.lazy(() => GetProjectEnvContentHintProjects1$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects2$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects3$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects4$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects5$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects6$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects7$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects8$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects9$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects10$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects11$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects12$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects13$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects14$outboundSchema),
    z.lazy(() => GetProjectEnvContentHintProjects15$outboundSchema),
]);
export function getProjectEnvResponseBodyProjectsContentHintToJSON(getProjectEnvResponseBodyProjectsContentHint) {
    return JSON.stringify(GetProjectEnvResponseBodyProjectsContentHint$outboundSchema.parse(getProjectEnvResponseBodyProjectsContentHint));
}
export function getProjectEnvResponseBodyProjectsContentHintFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvResponseBodyProjectsContentHint$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvResponseBodyProjectsContentHint' from JSON`);
}
/** @internal */
export const GetProjectEnvResponseBodyProjectsResponse200Type$inboundSchema = z
    .nativeEnum(GetProjectEnvResponseBodyProjectsResponse200Type);
/** @internal */
export const GetProjectEnvResponseBodyProjectsResponse200Type$outboundSchema = GetProjectEnvResponseBodyProjectsResponse200Type$inboundSchema;
/** @internal */
export const GetProjectEnvResponseBodyProjectsInternalContentHint$inboundSchema = z.object({
    type: GetProjectEnvResponseBodyProjectsResponse200Type$inboundSchema,
    encryptedValue: types.string(),
});
/** @internal */
export const GetProjectEnvResponseBodyProjectsInternalContentHint$outboundSchema = z.object({
    type: GetProjectEnvResponseBodyProjectsResponse200Type$outboundSchema,
    encryptedValue: z.string(),
});
export function getProjectEnvResponseBodyProjectsInternalContentHintToJSON(getProjectEnvResponseBodyProjectsInternalContentHint) {
    return JSON.stringify(GetProjectEnvResponseBodyProjectsInternalContentHint$outboundSchema.parse(getProjectEnvResponseBodyProjectsInternalContentHint));
}
export function getProjectEnvResponseBodyProjectsInternalContentHintFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvResponseBodyProjectsInternalContentHint$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvResponseBodyProjectsInternalContentHint' from JSON`);
}
/** @internal */
export const GetProjectEnvResponseBody2$inboundSchema = z.object({
    type: GetProjectEnvResponseBodyProjectsType$inboundSchema,
    value: types.string(),
    edgeConfigId: z.nullable(types.string()).optional(),
    edgeConfigTokenId: z.nullable(types.string()).optional(),
    createdAt: types.optional(types.number()),
    updatedAt: types.optional(types.number()),
    id: types.optional(types.string()),
    createdBy: z.nullable(types.string()).optional(),
    target: types.optional(smartUnion([
        z.array(GetProjectEnvTargetProjects1$inboundSchema),
        GetProjectEnvTargetProjects2$inboundSchema,
    ])),
    key: types.string(),
    gitBranch: types.optional(types.string()),
    updatedBy: z.nullable(types.string()).optional(),
    sunsetSecretId: types.optional(types.string()),
    legacyValue: types.optional(types.string()),
    decrypted: types.optional(types.boolean()),
    configurationId: z.nullable(types.string()).optional(),
    contentHint: z.nullable(z.union([
        z.lazy(() => GetProjectEnvContentHintProjects1$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects2$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects3$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects4$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects5$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects6$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects7$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects8$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects9$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects10$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects11$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects12$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects13$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects14$inboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects15$inboundSchema),
    ])).optional(),
    internalContentHint: z.nullable(z.lazy(() => GetProjectEnvResponseBodyProjectsInternalContentHint$inboundSchema)).optional(),
    comment: types.optional(types.string()),
    customEnvironmentIds: types.optional(z.array(types.string())),
});
/** @internal */
export const GetProjectEnvResponseBody2$outboundSchema = z.object({
    type: GetProjectEnvResponseBodyProjectsType$outboundSchema,
    value: z.string(),
    edgeConfigId: z.nullable(z.string()).optional(),
    edgeConfigTokenId: z.nullable(z.string()).optional(),
    createdAt: z.number().optional(),
    updatedAt: z.number().optional(),
    id: z.string().optional(),
    createdBy: z.nullable(z.string()).optional(),
    target: smartUnion([
        z.array(GetProjectEnvTargetProjects1$outboundSchema),
        GetProjectEnvTargetProjects2$outboundSchema,
    ]).optional(),
    key: z.string(),
    gitBranch: z.string().optional(),
    updatedBy: z.nullable(z.string()).optional(),
    sunsetSecretId: z.string().optional(),
    legacyValue: z.string().optional(),
    decrypted: z.boolean().optional(),
    configurationId: z.nullable(z.string()).optional(),
    contentHint: z.nullable(z.union([
        z.lazy(() => GetProjectEnvContentHintProjects1$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects2$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects3$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects4$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects5$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects6$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects7$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects8$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects9$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects10$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects11$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects12$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects13$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects14$outboundSchema),
        z.lazy(() => GetProjectEnvContentHintProjects15$outboundSchema),
    ])).optional(),
    internalContentHint: z.nullable(z.lazy(() => GetProjectEnvResponseBodyProjectsInternalContentHint$outboundSchema)).optional(),
    comment: z.string().optional(),
    customEnvironmentIds: z.array(z.string()).optional(),
});
export function getProjectEnvResponseBody2ToJSON(getProjectEnvResponseBody2) {
    return JSON.stringify(GetProjectEnvResponseBody2$outboundSchema.parse(getProjectEnvResponseBody2));
}
export function getProjectEnvResponseBody2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvResponseBody2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvResponseBody2' from JSON`);
}
/** @internal */
export const GetProjectEnvResponseBodyType$inboundSchema = z.nativeEnum(GetProjectEnvResponseBodyType);
/** @internal */
export const GetProjectEnvResponseBodyType$outboundSchema = GetProjectEnvResponseBodyType$inboundSchema;
/** @internal */
export const GetProjectEnvTarget2$inboundSchema = z.nativeEnum(GetProjectEnvTarget2);
/** @internal */
export const GetProjectEnvTarget2$outboundSchema = GetProjectEnvTarget2$inboundSchema;
/** @internal */
export const GetProjectEnvTarget1$inboundSchema = z.nativeEnum(GetProjectEnvTarget1);
/** @internal */
export const GetProjectEnvTarget1$outboundSchema = GetProjectEnvTarget1$inboundSchema;
/** @internal */
export const GetProjectEnvResponseBodyTarget$inboundSchema = smartUnion([
    z.array(GetProjectEnvTarget1$inboundSchema),
    GetProjectEnvTarget2$inboundSchema,
]);
/** @internal */
export const GetProjectEnvResponseBodyTarget$outboundSchema = smartUnion([
    z.array(GetProjectEnvTarget1$outboundSchema),
    GetProjectEnvTarget2$outboundSchema,
]);
export function getProjectEnvResponseBodyTargetToJSON(getProjectEnvResponseBodyTarget) {
    return JSON.stringify(GetProjectEnvResponseBodyTarget$outboundSchema.parse(getProjectEnvResponseBodyTarget));
}
export function getProjectEnvResponseBodyTargetFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvResponseBodyTarget$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvResponseBodyTarget' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint15$inboundSchema = z.object({
    type: types.literal("flags-connection-string"),
    projectId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint15$outboundSchema = z.object({
    type: z.literal("flags-connection-string"),
    projectId: z.string(),
});
export function getProjectEnvContentHint15ToJSON(getProjectEnvContentHint15) {
    return JSON.stringify(GetProjectEnvContentHint15$outboundSchema.parse(getProjectEnvContentHint15));
}
export function getProjectEnvContentHint15FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint15$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint15' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint14$inboundSchema = z.object({
    type: types.literal("integration-store-secret"),
    storeId: types.string(),
    integrationId: types.string(),
    integrationProductId: types.string(),
    integrationConfigurationId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint14$outboundSchema = z.object({
    type: z.literal("integration-store-secret"),
    storeId: z.string(),
    integrationId: z.string(),
    integrationProductId: z.string(),
    integrationConfigurationId: z.string(),
});
export function getProjectEnvContentHint14ToJSON(getProjectEnvContentHint14) {
    return JSON.stringify(GetProjectEnvContentHint14$outboundSchema.parse(getProjectEnvContentHint14));
}
export function getProjectEnvContentHint14FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint14$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint14' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint13$inboundSchema = z.object({
    type: types.literal("postgres-url-no-ssl"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint13$outboundSchema = z.object({
    type: z.literal("postgres-url-no-ssl"),
    storeId: z.string(),
});
export function getProjectEnvContentHint13ToJSON(getProjectEnvContentHint13) {
    return JSON.stringify(GetProjectEnvContentHint13$outboundSchema.parse(getProjectEnvContentHint13));
}
export function getProjectEnvContentHint13FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint13$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint13' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint12$inboundSchema = z.object({
    type: types.literal("postgres-database"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint12$outboundSchema = z.object({
    type: z.literal("postgres-database"),
    storeId: z.string(),
});
export function getProjectEnvContentHint12ToJSON(getProjectEnvContentHint12) {
    return JSON.stringify(GetProjectEnvContentHint12$outboundSchema.parse(getProjectEnvContentHint12));
}
export function getProjectEnvContentHint12FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint12$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint12' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint11$inboundSchema = z.object({
    type: types.literal("postgres-password"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint11$outboundSchema = z.object({
    type: z.literal("postgres-password"),
    storeId: z.string(),
});
export function getProjectEnvContentHint11ToJSON(getProjectEnvContentHint11) {
    return JSON.stringify(GetProjectEnvContentHint11$outboundSchema.parse(getProjectEnvContentHint11));
}
export function getProjectEnvContentHint11FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint11$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint11' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint10$inboundSchema = z.object({
    type: types.literal("postgres-host"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint10$outboundSchema = z.object({
    type: z.literal("postgres-host"),
    storeId: z.string(),
});
export function getProjectEnvContentHint10ToJSON(getProjectEnvContentHint10) {
    return JSON.stringify(GetProjectEnvContentHint10$outboundSchema.parse(getProjectEnvContentHint10));
}
export function getProjectEnvContentHint10FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint10$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint10' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint9$inboundSchema = z.object({
    type: types.literal("postgres-user"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint9$outboundSchema = z.object({
    type: z.literal("postgres-user"),
    storeId: z.string(),
});
export function getProjectEnvContentHint9ToJSON(getProjectEnvContentHint9) {
    return JSON.stringify(GetProjectEnvContentHint9$outboundSchema.parse(getProjectEnvContentHint9));
}
export function getProjectEnvContentHint9FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint9$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint9' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint8$inboundSchema = z.object({
    type: types.literal("postgres-prisma-url"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint8$outboundSchema = z.object({
    type: z.literal("postgres-prisma-url"),
    storeId: z.string(),
});
export function getProjectEnvContentHint8ToJSON(getProjectEnvContentHint8) {
    return JSON.stringify(GetProjectEnvContentHint8$outboundSchema.parse(getProjectEnvContentHint8));
}
export function getProjectEnvContentHint8FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint8$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint8' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint7$inboundSchema = z.object({
    type: types.literal("postgres-url-non-pooling"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint7$outboundSchema = z.object({
    type: z.literal("postgres-url-non-pooling"),
    storeId: z.string(),
});
export function getProjectEnvContentHint7ToJSON(getProjectEnvContentHint7) {
    return JSON.stringify(GetProjectEnvContentHint7$outboundSchema.parse(getProjectEnvContentHint7));
}
export function getProjectEnvContentHint7FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint7$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint7' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint6$inboundSchema = z.object({
    type: types.literal("postgres-url"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint6$outboundSchema = z.object({
    type: z.literal("postgres-url"),
    storeId: z.string(),
});
export function getProjectEnvContentHint6ToJSON(getProjectEnvContentHint6) {
    return JSON.stringify(GetProjectEnvContentHint6$outboundSchema.parse(getProjectEnvContentHint6));
}
export function getProjectEnvContentHint6FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint6$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint6' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint5$inboundSchema = z.object({
    type: types.literal("blob-read-write-token"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint5$outboundSchema = z.object({
    type: z.literal("blob-read-write-token"),
    storeId: z.string(),
});
export function getProjectEnvContentHint5ToJSON(getProjectEnvContentHint5) {
    return JSON.stringify(GetProjectEnvContentHint5$outboundSchema.parse(getProjectEnvContentHint5));
}
export function getProjectEnvContentHint5FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint5$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint5' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint4$inboundSchema = z.object({
    type: types.literal("redis-rest-api-read-only-token"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint4$outboundSchema = z.object({
    type: z.literal("redis-rest-api-read-only-token"),
    storeId: z.string(),
});
export function getProjectEnvContentHint4ToJSON(getProjectEnvContentHint4) {
    return JSON.stringify(GetProjectEnvContentHint4$outboundSchema.parse(getProjectEnvContentHint4));
}
export function getProjectEnvContentHint4FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint4$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint4' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint3$inboundSchema = z.object({
    type: types.literal("redis-rest-api-token"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint3$outboundSchema = z.object({
    type: z.literal("redis-rest-api-token"),
    storeId: z.string(),
});
export function getProjectEnvContentHint3ToJSON(getProjectEnvContentHint3) {
    return JSON.stringify(GetProjectEnvContentHint3$outboundSchema.parse(getProjectEnvContentHint3));
}
export function getProjectEnvContentHint3FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint3$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint3' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint2$inboundSchema = z.object({
    type: types.literal("redis-rest-api-url"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint2$outboundSchema = z.object({
    type: z.literal("redis-rest-api-url"),
    storeId: z.string(),
});
export function getProjectEnvContentHint2ToJSON(getProjectEnvContentHint2) {
    return JSON.stringify(GetProjectEnvContentHint2$outboundSchema.parse(getProjectEnvContentHint2));
}
export function getProjectEnvContentHint2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint2' from JSON`);
}
/** @internal */
export const GetProjectEnvContentHint1$inboundSchema = z.object({
    type: types.literal("redis-url"),
    storeId: types.string(),
});
/** @internal */
export const GetProjectEnvContentHint1$outboundSchema = z.object({
    type: z.literal("redis-url"),
    storeId: z.string(),
});
export function getProjectEnvContentHint1ToJSON(getProjectEnvContentHint1) {
    return JSON.stringify(GetProjectEnvContentHint1$outboundSchema.parse(getProjectEnvContentHint1));
}
export function getProjectEnvContentHint1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvContentHint1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvContentHint1' from JSON`);
}
/** @internal */
export const GetProjectEnvResponseBodyContentHint$inboundSchema = z.union([
    z.lazy(() => GetProjectEnvContentHint1$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint2$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint3$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint4$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint5$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint6$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint7$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint8$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint9$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint10$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint11$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint12$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint13$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint14$inboundSchema),
    z.lazy(() => GetProjectEnvContentHint15$inboundSchema),
]);
/** @internal */
export const GetProjectEnvResponseBodyContentHint$outboundSchema = z.union([
    z.lazy(() => GetProjectEnvContentHint1$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint2$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint3$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint4$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint5$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint6$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint7$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint8$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint9$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint10$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint11$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint12$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint13$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint14$outboundSchema),
    z.lazy(() => GetProjectEnvContentHint15$outboundSchema),
]);
export function getProjectEnvResponseBodyContentHintToJSON(getProjectEnvResponseBodyContentHint) {
    return JSON.stringify(GetProjectEnvResponseBodyContentHint$outboundSchema.parse(getProjectEnvResponseBodyContentHint));
}
export function getProjectEnvResponseBodyContentHintFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvResponseBodyContentHint$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvResponseBodyContentHint' from JSON`);
}
/** @internal */
export const GetProjectEnvResponseBodyProjectsResponseType$inboundSchema = z
    .nativeEnum(GetProjectEnvResponseBodyProjectsResponseType);
/** @internal */
export const GetProjectEnvResponseBodyProjectsResponseType$outboundSchema = GetProjectEnvResponseBodyProjectsResponseType$inboundSchema;
/** @internal */
export const GetProjectEnvResponseBodyInternalContentHint$inboundSchema = z.object({
    type: GetProjectEnvResponseBodyProjectsResponseType$inboundSchema,
    encryptedValue: types.string(),
});
/** @internal */
export const GetProjectEnvResponseBodyInternalContentHint$outboundSchema = z.object({
    type: GetProjectEnvResponseBodyProjectsResponseType$outboundSchema,
    encryptedValue: z.string(),
});
export function getProjectEnvResponseBodyInternalContentHintToJSON(getProjectEnvResponseBodyInternalContentHint) {
    return JSON.stringify(GetProjectEnvResponseBodyInternalContentHint$outboundSchema.parse(getProjectEnvResponseBodyInternalContentHint));
}
export function getProjectEnvResponseBodyInternalContentHintFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvResponseBodyInternalContentHint$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvResponseBodyInternalContentHint' from JSON`);
}
/** @internal */
export const GetProjectEnvResponseBody1$inboundSchema = z.object({
    decrypted: types.boolean(),
    type: GetProjectEnvResponseBodyType$inboundSchema,
    edgeConfigId: z.nullable(types.string()).optional(),
    edgeConfigTokenId: z.nullable(types.string()).optional(),
    createdAt: types.optional(types.number()),
    updatedAt: types.optional(types.number()),
    id: types.optional(types.string()),
    createdBy: z.nullable(types.string()).optional(),
    target: types.optional(smartUnion([
        z.array(GetProjectEnvTarget1$inboundSchema),
        GetProjectEnvTarget2$inboundSchema,
    ])),
    key: types.string(),
    gitBranch: types.optional(types.string()),
    updatedBy: z.nullable(types.string()).optional(),
    sunsetSecretId: types.optional(types.string()),
    legacyValue: types.optional(types.string()),
    configurationId: z.nullable(types.string()).optional(),
    contentHint: z.nullable(z.union([
        z.lazy(() => GetProjectEnvContentHint1$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint2$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint3$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint4$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint5$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint6$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint7$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint8$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint9$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint10$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint11$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint12$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint13$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint14$inboundSchema),
        z.lazy(() => GetProjectEnvContentHint15$inboundSchema),
    ])).optional(),
    internalContentHint: z.nullable(z.lazy(() => GetProjectEnvResponseBodyInternalContentHint$inboundSchema)).optional(),
    comment: types.optional(types.string()),
    customEnvironmentIds: types.optional(z.array(types.string())),
});
/** @internal */
export const GetProjectEnvResponseBody1$outboundSchema = z.object({
    decrypted: z.boolean(),
    type: GetProjectEnvResponseBodyType$outboundSchema,
    edgeConfigId: z.nullable(z.string()).optional(),
    edgeConfigTokenId: z.nullable(z.string()).optional(),
    createdAt: z.number().optional(),
    updatedAt: z.number().optional(),
    id: z.string().optional(),
    createdBy: z.nullable(z.string()).optional(),
    target: smartUnion([
        z.array(GetProjectEnvTarget1$outboundSchema),
        GetProjectEnvTarget2$outboundSchema,
    ]).optional(),
    key: z.string(),
    gitBranch: z.string().optional(),
    updatedBy: z.nullable(z.string()).optional(),
    sunsetSecretId: z.string().optional(),
    legacyValue: z.string().optional(),
    configurationId: z.nullable(z.string()).optional(),
    contentHint: z.nullable(z.union([
        z.lazy(() => GetProjectEnvContentHint1$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint2$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint3$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint4$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint5$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint6$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint7$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint8$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint9$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint10$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint11$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint12$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint13$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint14$outboundSchema),
        z.lazy(() => GetProjectEnvContentHint15$outboundSchema),
    ])).optional(),
    internalContentHint: z.nullable(z.lazy(() => GetProjectEnvResponseBodyInternalContentHint$outboundSchema)).optional(),
    comment: z.string().optional(),
    customEnvironmentIds: z.array(z.string()).optional(),
});
export function getProjectEnvResponseBody1ToJSON(getProjectEnvResponseBody1) {
    return JSON.stringify(GetProjectEnvResponseBody1$outboundSchema.parse(getProjectEnvResponseBody1));
}
export function getProjectEnvResponseBody1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvResponseBody1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvResponseBody1' from JSON`);
}
/** @internal */
export const GetProjectEnvResponseBody$inboundSchema = smartUnion([
    z.lazy(() => GetProjectEnvResponseBody1$inboundSchema),
    z.lazy(() => GetProjectEnvResponseBody2$inboundSchema),
]);
/** @internal */
export const GetProjectEnvResponseBody$outboundSchema = smartUnion([
    z.lazy(() => GetProjectEnvResponseBody1$outboundSchema),
    z.lazy(() => GetProjectEnvResponseBody2$outboundSchema),
]);
export function getProjectEnvResponseBodyToJSON(getProjectEnvResponseBody) {
    return JSON.stringify(GetProjectEnvResponseBody$outboundSchema.parse(getProjectEnvResponseBody));
}
export function getProjectEnvResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetProjectEnvResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetProjectEnvResponseBody' from JSON`);
}
//# sourceMappingURL=getprojectenvop.js.map