/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
/**
 * The type of this cosmos doc instance, if blank, assume secret.
 */
export const GetSharedEnvVarType = {
    Encrypted: "encrypted",
    Sensitive: "sensitive",
    System: "system",
    Plain: "plain",
};
/**
 * environments this env variable targets
 */
export const GetSharedEnvVarTarget = {
    Production: "production",
    Preview: "preview",
    Development: "development",
};
/** @internal */
export const GetSharedEnvVarRequest$inboundSchema = z.object({
    id: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
});
/** @internal */
export const GetSharedEnvVarRequest$outboundSchema = z.object({
    id: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
});
export function getSharedEnvVarRequestToJSON(getSharedEnvVarRequest) {
    return JSON.stringify(GetSharedEnvVarRequest$outboundSchema.parse(getSharedEnvVarRequest));
}
export function getSharedEnvVarRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetSharedEnvVarRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetSharedEnvVarRequest' from JSON`);
}
/** @internal */
export const GetSharedEnvVarType$inboundSchema = z.nativeEnum(GetSharedEnvVarType);
/** @internal */
export const GetSharedEnvVarType$outboundSchema = GetSharedEnvVarType$inboundSchema;
/** @internal */
export const GetSharedEnvVarTarget$inboundSchema = z.nativeEnum(GetSharedEnvVarTarget);
/** @internal */
export const GetSharedEnvVarTarget$outboundSchema = GetSharedEnvVarTarget$inboundSchema;
/** @internal */
export const GetSharedEnvVarResponseBody$inboundSchema = z.object({
    created: types.optional(types.date()),
    key: types.optional(types.string()),
    ownerId: z.nullable(types.string()).optional(),
    id: types.optional(types.string()),
    createdBy: z.nullable(types.string()).optional(),
    deletedBy: z.nullable(types.string()).optional(),
    updatedBy: z.nullable(types.string()).optional(),
    createdAt: types.optional(types.number()),
    deletedAt: types.optional(types.number()),
    updatedAt: types.optional(types.number()),
    value: types.optional(types.string()),
    projectId: types.optional(z.array(types.string())),
    type: types.optional(GetSharedEnvVarType$inboundSchema),
    target: types.optional(z.array(GetSharedEnvVarTarget$inboundSchema)),
    applyToAllCustomEnvironments: types.optional(types.boolean()),
    decrypted: types.optional(types.boolean()),
    comment: types.optional(types.string()),
    lastEditedByDisplayName: types.optional(types.string()),
});
/** @internal */
export const GetSharedEnvVarResponseBody$outboundSchema = z.object({
    created: z.date().transform(v => v.toISOString()).optional(),
    key: z.string().optional(),
    ownerId: z.nullable(z.string()).optional(),
    id: z.string().optional(),
    createdBy: z.nullable(z.string()).optional(),
    deletedBy: z.nullable(z.string()).optional(),
    updatedBy: z.nullable(z.string()).optional(),
    createdAt: z.number().optional(),
    deletedAt: z.number().optional(),
    updatedAt: z.number().optional(),
    value: z.string().optional(),
    projectId: z.array(z.string()).optional(),
    type: GetSharedEnvVarType$outboundSchema.optional(),
    target: z.array(GetSharedEnvVarTarget$outboundSchema).optional(),
    applyToAllCustomEnvironments: z.boolean().optional(),
    decrypted: z.boolean().optional(),
    comment: z.string().optional(),
    lastEditedByDisplayName: z.string().optional(),
});
export function getSharedEnvVarResponseBodyToJSON(getSharedEnvVarResponseBody) {
    return JSON.stringify(GetSharedEnvVarResponseBody$outboundSchema.parse(getSharedEnvVarResponseBody));
}
export function getSharedEnvVarResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetSharedEnvVarResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetSharedEnvVarResponseBody' from JSON`);
}
//# sourceMappingURL=getsharedenvvarop.js.map