/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { Pagination$inboundSchema, Pagination$outboundSchema, } from "./pagination.js";
import { Team$inboundSchema, Team$outboundSchema, } from "./team.js";
import { TeamLimited$inboundSchema, TeamLimited$outboundSchema, } from "./teamlimited.js";
/** @internal */
export const GetTeamsRequest$inboundSchema = z.object({
    limit: types.optional(types.number()),
    since: types.optional(types.number()),
    until: types.optional(types.number()),
});
/** @internal */
export const GetTeamsRequest$outboundSchema = z.object({
    limit: z.number().optional(),
    since: z.number().optional(),
    until: z.number().optional(),
});
export function getTeamsRequestToJSON(getTeamsRequest) {
    return JSON.stringify(GetTeamsRequest$outboundSchema.parse(getTeamsRequest));
}
export function getTeamsRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetTeamsRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetTeamsRequest' from JSON`);
}
/** @internal */
export const GetTeamsTeams$inboundSchema = smartUnion([Team$inboundSchema, TeamLimited$inboundSchema]);
/** @internal */
export const GetTeamsTeams$outboundSchema = smartUnion([Team$outboundSchema, TeamLimited$outboundSchema]);
export function getTeamsTeamsToJSON(getTeamsTeams) {
    return JSON.stringify(GetTeamsTeams$outboundSchema.parse(getTeamsTeams));
}
export function getTeamsTeamsFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetTeamsTeams$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetTeamsTeams' from JSON`);
}
/** @internal */
export const GetTeamsResponseBody$inboundSchema = z.object({
    teams: z.array(smartUnion([Team$inboundSchema, TeamLimited$inboundSchema])),
    pagination: Pagination$inboundSchema,
});
/** @internal */
export const GetTeamsResponseBody$outboundSchema = z.object({
    teams: z.array(smartUnion([Team$outboundSchema, TeamLimited$outboundSchema])),
    pagination: Pagination$outboundSchema,
});
export function getTeamsResponseBodyToJSON(getTeamsResponseBody) {
    return JSON.stringify(GetTeamsResponseBody$outboundSchema.parse(getTeamsResponseBody));
}
export function getTeamsResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetTeamsResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetTeamsResponseBody' from JSON`);
}
//# sourceMappingURL=getteamsop.js.map