/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
import { SandboxCommand$inboundSchema, SandboxCommand$outboundSchema, } from "./sandboxcommand.js";
/** @internal */
export const KillCommandRequestBody$inboundSchema = z.object({
    signal: types.number(),
});
/** @internal */
export const KillCommandRequestBody$outboundSchema = z.object({
    signal: z.number(),
});
export function killCommandRequestBodyToJSON(killCommandRequestBody) {
    return JSON.stringify(KillCommandRequestBody$outboundSchema.parse(killCommandRequestBody));
}
export function killCommandRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => KillCommandRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'KillCommandRequestBody' from JSON`);
}
/** @internal */
export const KillCommandRequest$inboundSchema = z.object({
    cmdId: types.string(),
    sandboxId: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
    RequestBody: types.optional(z.lazy(() => KillCommandRequestBody$inboundSchema)),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const KillCommandRequest$outboundSchema = z.object({
    cmdId: z.string(),
    sandboxId: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
    requestBody: z.lazy(() => KillCommandRequestBody$outboundSchema).optional(),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function killCommandRequestToJSON(killCommandRequest) {
    return JSON.stringify(KillCommandRequest$outboundSchema.parse(killCommandRequest));
}
export function killCommandRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => KillCommandRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'KillCommandRequest' from JSON`);
}
/** @internal */
export const KillCommandResponseBody$inboundSchema = z.object({
    command: SandboxCommand$inboundSchema,
});
/** @internal */
export const KillCommandResponseBody$outboundSchema = z.object({
    command: SandboxCommand$outboundSchema,
});
export function killCommandResponseBodyToJSON(killCommandResponseBody) {
    return JSON.stringify(KillCommandResponseBody$outboundSchema.parse(killCommandResponseBody));
}
export function killCommandResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => KillCommandResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'KillCommandResponseBody' from JSON`);
}
//# sourceMappingURL=killcommandop.js.map