import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
export type ListEventTypesRequest = {
    /**
     * The Team identifier to perform the request on behalf of.
     */
    teamId?: string | undefined;
    /**
     * The Team slug to perform the request on behalf of.
     */
    slug?: string | undefined;
};
export declare const ListEventTypesName: {
    readonly Team: "team";
    readonly Avatar: "avatar";
    readonly Alias: "alias";
    readonly Plan: "plan";
    readonly Flag: "flag";
    readonly Deployment: "deployment";
    readonly AccessGroupCreated: "access-group-created";
    readonly AccessGroupDeleted: "access-group-deleted";
    readonly AccessGroupProjectUpdated: "access-group-project-updated";
    readonly AccessGroupUpdated: "access-group-updated";
    readonly AccessGroupUserAdded: "access-group-user-added";
    readonly AccessGroupUserRemoved: "access-group-user-removed";
    readonly PasswordProtectionDisabled: "password-protection-disabled";
    readonly PasswordProtectionEnabled: "password-protection-enabled";
    readonly AliasChown: "alias-chown";
    readonly AliasDelete: "alias-delete";
    readonly AliasInviteCreated: "alias-invite-created";
    readonly AliasInviteJoined: "alias-invite-joined";
    readonly AliasInviteRevoked: "alias-invite-revoked";
    readonly AliasProtectionBypassCreated: "alias-protection-bypass-created";
    readonly AliasProtectionBypassException: "alias-protection-bypass-exception";
    readonly AliasProtectionBypassRegenerated: "alias-protection-bypass-regenerated";
    readonly AliasProtectionBypassRevoked: "alias-protection-bypass-revoked";
    readonly AliasSystem: "alias-system";
    readonly AliasUserScopedAccessDenied: "alias-user-scoped-access-denied";
    readonly AliasUserScopedAccessGranted: "alias-user-scoped-access-granted";
    readonly AliasUserScopedAccessRequested: "alias-user-scoped-access-requested";
    readonly AliasUserScopedAccessRevoked: "alias-user-scoped-access-revoked";
    readonly OauthAppConnectionCreated: "oauth-app-connection-created";
    readonly OauthAppConnectionRemoved: "oauth-app-connection-removed";
    readonly OauthAppConnectionUpdated: "oauth-app-connection-updated";
    readonly OauthAppCreated: "oauth-app-created";
    readonly OauthAppDeleted: "oauth-app-deleted";
    readonly VercelAppInstallationRequestDismissed: "vercel-app-installation-request-dismissed";
    readonly VercelAppInstallationRequested: "vercel-app-installation-requested";
    readonly VercelAppInstallationUpdated: "vercel-app-installation-updated";
    readonly VercelAppInstalled: "vercel-app-installed";
    readonly OauthAppSecretDeleted: "oauth-app-secret-deleted";
    readonly OauthAppSecretGenerated: "oauth-app-secret-generated";
    readonly OauthAppTokenCreated: "oauth-app-token-created";
    readonly VercelAppTokensRevoked: "vercel-app-tokens-revoked";
    readonly VercelAppUninstalled: "vercel-app-uninstalled";
    readonly OauthAppUpdated: "oauth-app-updated";
    readonly AttackModeDisabled: "attack-mode-disabled";
    readonly AttackModeEnabled: "attack-mode-enabled";
    readonly AutoExposeSystemEnvs: "auto-expose-system-envs";
    readonly InvoiceRefunded: "invoice-refunded";
    readonly InvoiceModified: "invoice-modified";
    readonly PaymentMethodAdded: "payment-method-added";
    readonly PaymentMethodDefaultUpdated: "payment-method-default-updated";
    readonly PaymentMethodRemoved: "payment-method-removed";
    readonly SubscriptionCreated: "subscription-created";
    readonly SubscriptionUpdated: "subscription-updated";
    readonly SubscriptionProductAdded: "subscription-product-added";
    readonly SubscriptionProductRemoved: "subscription-product-removed";
    readonly BulkRedirectsSettingsUpdated: "bulk-redirects-settings-updated";
    readonly BulkRedirectsVersionPromoted: "bulk-redirects-version-promoted";
    readonly BulkRedirectsVersionRestored: "bulk-redirects-version-restored";
    readonly Cert: "cert";
    readonly CertSystemCreate: "cert-system-create";
    readonly CertAutorenew: "cert-autorenew";
    readonly CertChown: "cert-chown";
    readonly CertClone: "cert-clone";
    readonly CertDelete: "cert-delete";
    readonly CertRenew: "cert-renew";
    readonly CertReplace: "cert-replace";
    readonly ConnectConfigurationCreated: "connect-configuration-created";
    readonly ConnectConfigurationDeleted: "connect-configuration-deleted";
    readonly ConnectConfigurationLinkUpdated: "connect-configuration-link-updated";
    readonly ConnectConfigurationLinked: "connect-configuration-linked";
    readonly ConnectConfigurationUnlinked: "connect-configuration-unlinked";
    readonly ConnectConfigurationUpdated: "connect-configuration-updated";
    readonly ConnectGithub: "connect-github";
    readonly DisconnectGithub: "disconnect-github";
    readonly ConnectGithubLimited: "connect-github-limited";
    readonly DisconnectGithubLimited: "disconnect-github-limited";
    readonly ConnectGithubCustomHost: "connect-github-custom-host";
    readonly DisconnectGithubCustomHost: "disconnect-github-custom-host";
    readonly ConnectGitlab: "connect-gitlab";
    readonly ConnectGitlabApp: "connect-gitlab-app";
    readonly DisconnectGitlabApp: "disconnect-gitlab-app";
    readonly ConnectBitbucket: "connect-bitbucket";
    readonly ConnectBitbucketApp: "connect-bitbucket-app";
    readonly DisconnectBitbucketApp: "disconnect-bitbucket-app";
    readonly CustomSuffixClear: "custom-suffix-clear";
    readonly CustomSuffixDisable: "custom-suffix-disable";
    readonly PreviewDeploymentSuffixDisabled: "preview-deployment-suffix-disabled";
    readonly CustomSuffixEnable: "custom-suffix-enable";
    readonly PreviewDeploymentSuffixEnabled: "preview-deployment-suffix-enabled";
    readonly CustomSuffixPending: "custom-suffix-pending";
    readonly CustomSuffixReady: "custom-suffix-ready";
    readonly DeployHookCreated: "deploy-hook-created";
    readonly DeployHookDeleted: "deploy-hook-deleted";
    readonly DeployHookDeduped: "deploy-hook-deduped";
    readonly DeployHookProcessed: "deploy-hook-processed";
    readonly AuthorizeGitDeployment: "authorize-git-deployment";
    readonly DeploymentChown: "deployment-chown";
    readonly DeploymentCreationBlocked: "deployment-creation-blocked";
    readonly DeploymentDelete: "deployment-delete";
    readonly DisabledIntegrationInstallationRemoved: "disabled-integration-installation-removed";
    readonly DnsAdd: "dns-add";
    readonly DnsDelete: "dns-delete";
    readonly DnsUpdate: "dns-update";
    readonly Domain: "domain";
    readonly DomainBuy: "domain-buy";
    readonly DomainCdn: "domain-cdn";
    readonly DomainChown: "domain-chown";
    readonly DomainDelegated: "domain-delegated";
    readonly DomainDelete: "domain-delete";
    readonly DomainServiceTypeUpdated: "domain-service-type-updated";
    readonly DomainCustomNsChange: "domain-custom-ns-change";
    readonly DnsZonefileImport: "dns-zonefile-import";
    readonly DomainMoveIn: "domain-move-in";
    readonly DomainMoveOut: "domain-move-out";
    readonly DomainMoveOutRequestSent: "domain-move-out-request-sent";
    readonly DomainRenewChange: "domain-renew-change";
    readonly DomainTransferIn: "domain-transfer-in";
    readonly DomainTransferInCanceled: "domain-transfer-in-canceled";
    readonly DomainTransferInCompleted: "domain-transfer-in-completed";
    readonly DrainCreated: "drain-created";
    readonly DrainDeleted: "drain-deleted";
    readonly DrainDisabled: "drain-disabled";
    readonly DrainEnabled: "drain-enabled";
    readonly DrainUpdated: "drain-updated";
    readonly EdgeCacheDangerouslyDeleteBySrcImages: "edge-cache-dangerously-delete-by-src-images";
    readonly EdgeCacheDangerouslyDeleteByTags: "edge-cache-dangerously-delete-by-tags";
    readonly EdgeCacheInvalidateBySrcImages: "edge-cache-invalidate-by-src-images";
    readonly EdgeCacheInvalidateByTags: "edge-cache-invalidate-by-tags";
    readonly EdgeCachePurgeAll: "edge-cache-purge-all";
    readonly EdgeCacheRollbackPurge: "edge-cache-rollback-purge";
    readonly EdgeConfigCreated: "edge-config-created";
    readonly EdgeConfigDeleted: "edge-config-deleted";
    readonly EdgeConfigItemsUpdated: "edge-config-items-updated";
    readonly EdgeConfigSchemaDeleted: "edge-config-schema-deleted";
    readonly EdgeConfigSchemaUpdated: "edge-config-schema-updated";
    readonly EdgeConfigTransferIn: "edge-config-transfer-in";
    readonly EdgeConfigTransferOut: "edge-config-transfer-out";
    readonly EdgeConfigTokenCreated: "edge-config-token-created";
    readonly EdgeConfigTokenDeleted: "edge-config-token-deleted";
    readonly EdgeConfigUpdated: "edge-config-updated";
    readonly Email: "email";
    readonly EmailNotificationRuleRemoved: "email-notification-rule-removed";
    readonly EmailNotificationRuleUpdated: "email-notification-rule-updated";
    readonly EnvVariableAdd: "env-variable-add";
    readonly EnvVariableDelete: "env-variable-delete";
    readonly EnvVariableEdit: "env-variable-edit";
    readonly EnvVariableRead: "env-variable-read";
    readonly EnvVariableReadCliDev: "env-variable-read:cli:dev";
    readonly EnvVariableReadCliEnvAdd: "env-variable-read:cli:env:add";
    readonly EnvVariableReadCliEnvLs: "env-variable-read:cli:env:ls";
    readonly EnvVariableReadCliEnvPull: "env-variable-read:cli:env:pull";
    readonly EnvVariableReadCliEnvRm: "env-variable-read:cli:env:rm";
    readonly EnvVariableReadCliPull: "env-variable-read:cli:pull";
    readonly EnvVariableReadUnknownSource: "env-variable-read:unknown-source";
    readonly EnvVariableReadV0EnvPull: "env-variable-read:v0:env:pull";
    readonly SharedEnvVariableCreate: "shared-env-variable-create";
    readonly SharedEnvVariableDelete: "shared-env-variable-delete";
    readonly SharedEnvVariableRead: "shared-env-variable-read";
    readonly SharedEnvVariableUpdate: "shared-env-variable-update";
    readonly FirewallBypassCreated: "firewall-bypass-created";
    readonly FirewallBypassDeleted: "firewall-bypass-deleted";
    readonly FirewallConfigPromoted: "firewall-config-promoted";
    readonly FirewallManagedRulegroupUpdated: "firewall-managed-rulegroup-updated";
    readonly FirewallManagedRulesetUpdated: "firewall-managed-ruleset-updated";
    readonly FlagsSegment: "flags-segment";
    readonly FlagsSettings: "flags-settings";
    readonly FlagsExplorerSubscription: "flags-explorer-subscription";
    readonly FlagsSDKKey: "flags-sdk-key";
    readonly InstantRollbackCreated: "instant-rollback-created";
    readonly IntegrationConfigurationOwnerChanged: "integration-configuration-owner-changed";
    readonly IntegrationConfigurationScopeChangeConfirmed: "integration-configuration-scope-change-confirmed";
    readonly IntegrationConfigurationsDisabled: "integration-configurations-disabled";
    readonly IntegrationInstallationBillingPlanUpdated: "integration-installation-billing-plan-updated";
    readonly IntegrationInstallationCompleted: "integration-installation-completed";
    readonly IntegrationInstallationPermissionUpdated: "integration-installation-permission-updated";
    readonly IntegrationInstallationRemoved: "integration-installation-removed";
    readonly IntegrationScopeChanged: "integration-scope-changed";
    readonly LogDrainCreated: "log-drain-created";
    readonly LogDrainDeleted: "log-drain-deleted";
    readonly LogDrainDisabled: "log-drain-disabled";
    readonly LogDrainEnabled: "log-drain-enabled";
    readonly Login: "login";
    readonly ManualDeploymentPromotionCreated: "manual-deployment-promotion-created";
    readonly MicrofrontendGroupAdded: "microfrontend-group-added";
    readonly MicrofrontendGroupDeleted: "microfrontend-group-deleted";
    readonly MicrofrontendGroupUpdated: "microfrontend-group-updated";
    readonly MicrofrontendProjectAddedToGroup: "microfrontend-project-added-to-group";
    readonly MicrofrontendProjectRemovedFromGroup: "microfrontend-project-removed-from-group";
    readonly MicrofrontendProjectUpdated: "microfrontend-project-updated";
    readonly MonitoringDisabled: "monitoring-disabled";
    readonly MonitoringEnabled: "monitoring-enabled";
    readonly ObservabilityDisabled: "observability-disabled";
    readonly ObservabilityEnabled: "observability-enabled";
    readonly ObservabilityPlusProjectDisabled: "observability-plus-project-disabled";
    readonly ObservabilityPlusProjectEnabled: "observability-plus-project-enabled";
    readonly OwnerBlocked: "owner-blocked";
    readonly OwnerUnblocked: "owner-unblocked";
    readonly OwnerSoftBlocked: "owner-soft-blocked";
    readonly OwnerSoftUnblocked: "owner-soft-unblocked";
    readonly PasskeyCreated: "passkey-created";
    readonly PasskeyDeleted: "passkey-deleted";
    readonly PasskeyUpdated: "passkey-updated";
    readonly PreviewDeploymentSuffixUpdate: "preview-deployment-suffix-update";
    readonly ProductionBranchUpdated: "production-branch-updated";
    readonly ProjectDirectoryListing: "project-directory-listing";
    readonly ProjectAnalyticsDisabled: "project-analytics-disabled";
    readonly ProjectSpeedInsightsDisabled: "project-speed-insights-disabled";
    readonly ProjectAnalyticsEnabled: "project-analytics-enabled";
    readonly ProjectSpeedInsightsEnabled: "project-speed-insights-enabled";
    readonly ProjectAutomationBypass: "project-automation-bypass";
    readonly ProjectAffectedProjectsDeploymentsUpdated: "project-affected-projects-deployments-updated";
    readonly ProjectBuildCommandUpdated: "project-build-command-updated";
    readonly ProjectFrameworkUpdated: "project-framework-updated";
    readonly ProjectInstallCommandUpdated: "project-install-command-updated";
    readonly ProjectNodeVersionUpdated: "project-node-version-updated";
    readonly ProjectOutputDirectoryUpdated: "project-output-directory-updated";
    readonly ProjectPrioritizeProductionBuildsUpdated: "project-prioritize-production-builds-updated";
    readonly ProjectRootDirectoryUpdated: "project-root-directory-updated";
    readonly ProjectSourceFilesOutsideRootDirectoryUpdated: "project-source-files-outside-root-directory-updated";
    readonly ProjectBuildMachineUpdated: "project-build-machine-updated";
    readonly ProjectClientCertDelete: "project-client-cert-delete";
    readonly ProjectClientCertUpload: "project-client-cert-upload";
    readonly ProjectConnectConfigurations: "project-connect-configurations";
    readonly ProjectCreated: "project-created";
    readonly ProjectCronJobsToggled: "project-cron-jobs-toggled";
    readonly ProjectDelete: "project-delete";
    readonly ProjectDomainUnverified: "project-domain-unverified";
    readonly ProjectDomainVerified: "project-domain-verified";
    readonly ProjectElasticConcurrencyUpdated: "project-elastic-concurrency-updated";
    readonly ProjectAutoAssignCustomProductionDomainsUpdated: "project-auto-assign-custom-production-domains-updated";
    readonly ProjectPreviewEnvironmentBranchTrackingUpdated: "project-preview-environment-branch-tracking-updated";
    readonly ProjectCustomEnvironmentUpdated: "project-custom-environment-updated";
    readonly ProjectCustomEnvironmentCreated: "project-custom-environment-created";
    readonly ProjectCustomEnvironmentDeleted: "project-custom-environment-deleted";
    readonly ProjectFunctionsFluidDisabled: "project-functions-fluid-disabled";
    readonly ProjectFunctionsFluidEnabled: "project-functions-fluid-enabled";
    readonly ProjectFunctionMaxDuration: "project-function-max-duration";
    readonly ProjectFunctionCpuMemory: "project-function-cpu-memory";
    readonly ProjectFunctionRegions: "project-function-regions";
    readonly ProjectFunctionFailover: "project-function-failover";
    readonly ProjectPreviewDeploymentSuffix: "project-preview-deployment-suffix";
    readonly ProjectName: "project-name";
    readonly ProjectGitRepositoryConnected: "project-git-repository-connected";
    readonly ProjectGitRepositoryDisconnected: "project-git-repository-disconnected";
    readonly ProjectGitPrCommentsToggled: "project-git-pr-comments-toggled";
    readonly ProjectGitCommitCommentsToggled: "project-git-commit-comments-toggled";
    readonly ProjectGitRepositoryDispatchEventsToggled: "project-git-repository-dispatch-events-toggled";
    readonly ProjectGitCreateDeploymentsToggled: "project-git-create-deployments-toggled";
    readonly ProjectGitRequireVerifiedCommitsToggled: "project-git-require-verified-commits-toggled";
    readonly ProjectGitLfsToggled: "project-git-lfs-toggled";
    readonly ProjectIgnoredBuildStepUpdated: "project-ignored-build-step-updated";
    readonly ProjectAddAlias: "project-add-alias";
    readonly ProjectAddRedirect: "project-add-redirect";
    readonly ProjectDomainDeleted: "project-domain-deleted";
    readonly ProjectDomainMoved: "project-domain-moved";
    readonly ProjectDomainUpdated: "project-domain-updated";
    readonly ProjectMemberRemovedBatch: "project-member-removed-batch";
    readonly ProjectAliasConfiguredChange: "project-alias-configured-change";
    readonly ProjectMemberAdded: "project-member-added";
    readonly ProjectMemberInvited: "project-member-invited";
    readonly ProjectMemberRemoved: "project-member-removed";
    readonly ProjectMemberUpdated: "project-member-updated";
    readonly ProjectMoveInSuccess: "project-move-in-success";
    readonly ProjectMoveOutFailed: "project-move-out-failed";
    readonly ProjectMoveOutStarted: "project-move-out-started";
    readonly ProjectMoveOutSuccess: "project-move-out-success";
    readonly ProjectOidcTokenCreated: "project-oidc-token-created";
    readonly ProjectOptionsAllowlist: "project-options-allowlist";
    readonly ProjectPasswordProtection: "project-password-protection";
    readonly ProjectPaused: "project-paused";
    readonly ProjectRollingReleaseEnabled: "project-rolling-release-enabled";
    readonly ProjectRollingReleaseDisabled: "project-rolling-release-disabled";
    readonly ProjectRollingReleaseConfigured: "project-rolling-release-configured";
    readonly ProjectRollingReleaseStarted: "project-rolling-release-started";
    readonly ProjectRollingReleaseCompleted: "project-rolling-release-completed";
    readonly ProjectRollingReleaseAborted: "project-rolling-release-aborted";
    readonly ProjectRollingReleaseApproved: "project-rolling-release-approved";
    readonly ProjectRollingReleaseTimer: "project-rolling-release-timer";
    readonly ProjectRoutesVersionPromoted: "project-routes-version-promoted";
    readonly ProjectRoutesVersionRestored: "project-routes-version-restored";
    readonly ProjectOidcIssuerModeUpdated: "project-oidc-issuer-mode-updated";
    readonly ProjectCustomerSuccessCodeVisibilityUpdated: "project-customer-success-code-visibility-updated";
    readonly ProjectGitForkProtectionUpdated: "project-git-fork-protection-updated";
    readonly ProjectProtectedSourcemapsUpdated: "project-protected-sourcemaps-updated";
    readonly ProjectBuildLogsAndSourceProtectionUpdated: "project-build-logs-and-source-protection-updated";
    readonly ProjectDeploymentRetentionUpdated: "project-deployment-retention-updated";
    readonly ProjectSkewProtectionThresholdUpdated: "project-skew-protection-threshold-updated";
    readonly ProjectSkewProtectionMaxAgeUpdated: "project-skew-protection-max-age-updated";
    readonly ProjectSkewProtectionAllowedDomainsUpdated: "project-skew-protection-allowed-domains-updated";
    readonly ProjectSsoProtection: "project-sso-protection";
    readonly ProjectStaticIpsUpdated: "project-static-ips-updated";
    readonly ProjectTrustedIps: "project-trusted-ips";
    readonly ProjectUnpaused: "project-unpaused";
    readonly ProjectWebAnalyticsDisabled: "project-web-analytics-disabled";
    readonly ProjectWebAnalyticsEnabled: "project-web-analytics-enabled";
    readonly ProtectedGitScopeAdded: "protected-git-scope-added";
    readonly ProtectedGitScopeRemoved: "protected-git-scope-removed";
    readonly RuntimeCachePurgeAll: "runtime-cache-purge-all";
    readonly Scale: "scale";
    readonly ScaleAuto: "scale-auto";
    readonly SecondaryEmailAdded: "secondary-email-added";
    readonly SecondaryEmailRemoved: "secondary-email-removed";
    readonly SecondaryEmailVerified: "secondary-email-verified";
    readonly SecretAdd: "secret-add";
    readonly SecretDelete: "secret-delete";
    readonly SecretRename: "secret-rename";
    readonly SecurityPlusUpdated: "security-plus-updated";
    readonly SetBio: "set-bio";
    readonly SetName: "set-name";
    readonly SetProfiles: "set-profiles";
    readonly SetScale: "set-scale";
    readonly Signup: "signup";
    readonly SignupViaBitbucket: "signup-via-bitbucket";
    readonly SignupViaGithub: "signup-via-github";
    readonly SignupViaGitlab: "signup-via-gitlab";
    readonly SpeedInsightsSettingsUpdated: "speed-insights-settings-updated";
    readonly SpendCreated: "spend-created";
    readonly SpendDeleted: "spend-deleted";
    readonly SpendUpdated: "spend-updated";
    readonly StorageAcceptTos: "storage-accept-tos";
    readonly StorageCreate: "storage-create";
    readonly StorageResetCredentials: "storage-reset-credentials";
    readonly StorageUpdate: "storage-update";
    readonly StorageConnectProject: "storage-connect-project";
    readonly StorageDisconnectProject: "storage-disconnect-project";
    readonly StorageUpdateProjectConnection: "storage-update-project-connection";
    readonly StorageDelete: "storage-delete";
    readonly StorageAccessedDataBrowser: "storage-accessed-data-browser";
    readonly StorageViewSecret: "storage-view-secret";
    readonly StorageInactiveStoreDeleted: "storage-inactive-store-deleted";
    readonly StorageResourceReplCommand: "storage-resource-repl-command";
    readonly StorageDisconnectProjects: "storage-disconnect-projects";
    readonly StorageAccessTokenSet: "storage-access-token-set";
    readonly AiCodeReview: "ai-code-review";
    readonly AiAlertInvestigation: "ai-alert-investigation";
    readonly VercelAgentTeamTrialCreditsApplied: "vercel-agent-team-trial-credits-applied";
    readonly TeamAvatarUpdate: "team-avatar-update";
    readonly TeamDelete: "team-delete";
    readonly StrictDeploymentProtectionSettings: "strict-deployment-protection-settings";
    readonly VercelToolbar: "vercel-toolbar";
    readonly TeamEmailDomainUpdate: "team-email-domain-update";
    readonly TeamInviteBulkDelete: "team-invite-bulk-delete";
    readonly TeamMemberAdd: "team-member-add";
    readonly TeamMemberConfirmRequest: "team-member-confirm-request";
    readonly TeamMemberDeclineRequest: "team-member-decline-request";
    readonly TeamMemberDelete: "team-member-delete";
    readonly TeamMemberEntitlementAdded: "team-member-entitlement-added";
    readonly TeamMemberEntitlementCanceled: "team-member-entitlement-canceled";
    readonly TeamMemberEntitlementReactivated: "team-member-entitlement-reactivated";
    readonly TeamMemberEntitlementRemoved: "team-member-entitlement-removed";
    readonly TeamMemberJoin: "team-member-join";
    readonly TeamMemberLeave: "team-member-leave";
    readonly TeamMemberRequestAccess: "team-member-request-access";
    readonly TeamMemberRoleUpdate: "team-member-role-update";
    readonly TeamMfaEnforcementUpdated: "team-mfa-enforcement-updated";
    readonly ConcurrentBuildsUpdate: "concurrent-builds-update";
    readonly TeamEndedTrial: "team-ended-trial";
    readonly TeamPaidInvoice: "team-paid-invoice";
    readonly TeamInviteCodeReset: "team-invite-code-reset";
    readonly TeamNameUpdate: "team-name-update";
    readonly TeamRemoteCachingUpdate: "team-remote-caching-update";
    readonly EnforceSensitiveEnvironmentVariables: "enforce-sensitive-environment-variables";
    readonly ShowIpAddresses: "show-ip-addresses";
    readonly TeamSamlEnforced: "team-saml-enforced";
    readonly TeamSamlRoles: "team-saml-roles";
    readonly TeamIpBlockingRulesCreated: "team-ip-blocking-rules-created";
    readonly TeamIpBlockingRulesRemoved: "team-ip-blocking-rules-removed";
    readonly AuditLogExportRequested: "audit-log-export-requested";
    readonly AuditLogExportDownloaded: "audit-log-export-downloaded";
    readonly TeamSlugUpdate: "team-slug-update";
    readonly UnlinkLoginConnection: "unlink-login-connection";
    readonly UserMfaRemoved: "user-mfa-removed";
    readonly UserDelete: "user-delete";
    readonly UserMfaChallengeVerified: "user-mfa-challenge-verified";
    readonly UserMfaConfigurationUpdated: "user-mfa-configuration-updated";
    readonly UserMfaRecoveryCodesRegenerated: "user-mfa-recovery-codes-regenerated";
    readonly UserMfaTotpVerificationStarted: "user-mfa-totp-verification-started";
    readonly UserMfaTotpVerified: "user-mfa-totp-verified";
    readonly UserPrimaryEmailUpdated: "user-primary-email-updated";
    readonly Username: "username";
    readonly AlertRuleCreated: "alert-rule-created";
    readonly AlertRuleUpdated: "alert-rule-updated";
    readonly AlertRuleDeleted: "alert-rule-deleted";
    readonly VpcPeeringConnectionAccepted: "vpc-peering-connection-accepted";
    readonly VpcPeeringConnectionDeleted: "vpc-peering-connection-deleted";
    readonly VpcPeeringConnectionRejected: "vpc-peering-connection-rejected";
    readonly VpcPeeringConnectionUpdated: "vpc-peering-connection-updated";
    readonly WebAnalyticsTierUpdated: "web-analytics-tier-updated";
    readonly WebhookCreated: "webhook-created";
    readonly WebhookDeleted: "webhook-deleted";
    readonly WebhookUpdated: "webhook-updated";
    readonly V0ChatCreated: "v0-chat-created";
    readonly V0ChatMessageSent: "v0-chat-message-sent";
    readonly WorkflowDeploymentKeyAccessed: "workflow-deployment-key-accessed";
};
export type ListEventTypesName = ClosedEnum<typeof ListEventTypesName>;
export type Types = {
    replacedBy: Array<string>;
    deprecated: boolean;
    name: ListEventTypesName;
    description: string;
};
export type ListEventTypesResponseBody = {
    types: Array<Types>;
};
/** @internal */
export declare const ListEventTypesRequest$inboundSchema: z.ZodType<ListEventTypesRequest, z.ZodTypeDef, unknown>;
/** @internal */
export type ListEventTypesRequest$Outbound = {
    teamId?: string | undefined;
    slug?: string | undefined;
};
/** @internal */
export declare const ListEventTypesRequest$outboundSchema: z.ZodType<ListEventTypesRequest$Outbound, z.ZodTypeDef, ListEventTypesRequest>;
export declare function listEventTypesRequestToJSON(listEventTypesRequest: ListEventTypesRequest): string;
export declare function listEventTypesRequestFromJSON(jsonString: string): SafeParseResult<ListEventTypesRequest, SDKValidationError>;
/** @internal */
export declare const ListEventTypesName$inboundSchema: z.ZodNativeEnum<typeof ListEventTypesName>;
/** @internal */
export declare const ListEventTypesName$outboundSchema: z.ZodNativeEnum<typeof ListEventTypesName>;
/** @internal */
export declare const Types$inboundSchema: z.ZodType<Types, z.ZodTypeDef, unknown>;
/** @internal */
export type Types$Outbound = {
    replacedBy: Array<string>;
    deprecated: boolean;
    name: string;
    description: string;
};
/** @internal */
export declare const Types$outboundSchema: z.ZodType<Types$Outbound, z.ZodTypeDef, Types>;
export declare function typesToJSON(types: Types): string;
export declare function typesFromJSON(jsonString: string): SafeParseResult<Types, SDKValidationError>;
/** @internal */
export declare const ListEventTypesResponseBody$inboundSchema: z.ZodType<ListEventTypesResponseBody, z.ZodTypeDef, unknown>;
/** @internal */
export type ListEventTypesResponseBody$Outbound = {
    types: Array<Types$Outbound>;
};
/** @internal */
export declare const ListEventTypesResponseBody$outboundSchema: z.ZodType<ListEventTypesResponseBody$Outbound, z.ZodTypeDef, ListEventTypesResponseBody>;
export declare function listEventTypesResponseBodyToJSON(listEventTypesResponseBody: ListEventTypesResponseBody): string;
export declare function listEventTypesResponseBodyFromJSON(jsonString: string): SafeParseResult<ListEventTypesResponseBody, SDKValidationError>;
//# sourceMappingURL=listeventtypesop.d.ts.map