import * as z from "zod/v3";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import { UserEvent, UserEvent$Outbound } from "./userevent.js";
export type ListUserEventsRequest = {
    /**
     * Maximum number of items which may be returned.
     */
    limit?: number | undefined;
    /**
     * Timestamp to only include items created since then.
     */
    since?: string | undefined;
    /**
     * Timestamp to only include items created until then.
     */
    until?: string | undefined;
    /**
     * Comma-delimited list of event \"types\" to filter the results by.
     */
    types?: string | undefined;
    /**
     * Deprecated. Use `principalId` instead. If `principalId` and `userId` both exist, `principalId` will be used.
     */
    userId?: string | undefined;
    /**
     * When retrieving events for a Team, the `principalId` parameter may be specified to filter events generated by a specific principal.
     */
    principalId?: string | undefined;
    /**
     * Comma-delimited list of project IDs to filter the results by.
     */
    projectIds?: string | undefined;
    /**
     * When set to `true`, the response will include the `payload` field for each event.
     */
    withPayload?: string | undefined;
    /**
     * The Team identifier to perform the request on behalf of.
     */
    teamId?: string | undefined;
    /**
     * The Team slug to perform the request on behalf of.
     */
    slug?: string | undefined;
};
/**
 * Successful response.
 */
export type ListUserEventsResponseBody2 = {
    /**
     * Array of events generated by the User.
     */
    events: Array<UserEvent>;
};
export type ListUserEventsResponseBody1 = {};
/**
 * Successful response.
 */
export type ListUserEventsResponseBody = ListUserEventsResponseBody2 | ListUserEventsResponseBody1;
/** @internal */
export declare const ListUserEventsRequest$inboundSchema: z.ZodType<ListUserEventsRequest, z.ZodTypeDef, unknown>;
/** @internal */
export type ListUserEventsRequest$Outbound = {
    limit?: number | undefined;
    since?: string | undefined;
    until?: string | undefined;
    types?: string | undefined;
    userId?: string | undefined;
    principalId?: string | undefined;
    projectIds?: string | undefined;
    withPayload?: string | undefined;
    teamId?: string | undefined;
    slug?: string | undefined;
};
/** @internal */
export declare const ListUserEventsRequest$outboundSchema: z.ZodType<ListUserEventsRequest$Outbound, z.ZodTypeDef, ListUserEventsRequest>;
export declare function listUserEventsRequestToJSON(listUserEventsRequest: ListUserEventsRequest): string;
export declare function listUserEventsRequestFromJSON(jsonString: string): SafeParseResult<ListUserEventsRequest, SDKValidationError>;
/** @internal */
export declare const ListUserEventsResponseBody2$inboundSchema: z.ZodType<ListUserEventsResponseBody2, z.ZodTypeDef, unknown>;
/** @internal */
export type ListUserEventsResponseBody2$Outbound = {
    events: Array<UserEvent$Outbound>;
};
/** @internal */
export declare const ListUserEventsResponseBody2$outboundSchema: z.ZodType<ListUserEventsResponseBody2$Outbound, z.ZodTypeDef, ListUserEventsResponseBody2>;
export declare function listUserEventsResponseBody2ToJSON(listUserEventsResponseBody2: ListUserEventsResponseBody2): string;
export declare function listUserEventsResponseBody2FromJSON(jsonString: string): SafeParseResult<ListUserEventsResponseBody2, SDKValidationError>;
/** @internal */
export declare const ListUserEventsResponseBody1$inboundSchema: z.ZodType<ListUserEventsResponseBody1, z.ZodTypeDef, unknown>;
/** @internal */
export type ListUserEventsResponseBody1$Outbound = {};
/** @internal */
export declare const ListUserEventsResponseBody1$outboundSchema: z.ZodType<ListUserEventsResponseBody1$Outbound, z.ZodTypeDef, ListUserEventsResponseBody1>;
export declare function listUserEventsResponseBody1ToJSON(listUserEventsResponseBody1: ListUserEventsResponseBody1): string;
export declare function listUserEventsResponseBody1FromJSON(jsonString: string): SafeParseResult<ListUserEventsResponseBody1, SDKValidationError>;
/** @internal */
export declare const ListUserEventsResponseBody$inboundSchema: z.ZodType<ListUserEventsResponseBody, z.ZodTypeDef, unknown>;
/** @internal */
export type ListUserEventsResponseBody$Outbound = ListUserEventsResponseBody2$Outbound | ListUserEventsResponseBody1$Outbound;
/** @internal */
export declare const ListUserEventsResponseBody$outboundSchema: z.ZodType<ListUserEventsResponseBody$Outbound, z.ZodTypeDef, ListUserEventsResponseBody>;
export declare function listUserEventsResponseBodyToJSON(listUserEventsResponseBody: ListUserEventsResponseBody): string;
export declare function listUserEventsResponseBodyFromJSON(jsonString: string): SafeParseResult<ListUserEventsResponseBody, SDKValidationError>;
//# sourceMappingURL=listusereventsop.d.ts.map