/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { Sandbox$inboundSchema, Sandbox$outboundSchema, } from "./sandbox.js";
/** @internal */
export const ListSandboxesRequest$inboundSchema = z.object({
    project: types.optional(types.string()),
    limit: types.optional(types.number()),
    since: types.optional(types.number()),
    until: types.optional(types.number()),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
});
/** @internal */
export const ListSandboxesRequest$outboundSchema = z.object({
    project: z.string().optional(),
    limit: z.number().optional(),
    since: z.number().optional(),
    until: z.number().optional(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
});
export function listSandboxesRequestToJSON(listSandboxesRequest) {
    return JSON.stringify(ListSandboxesRequest$outboundSchema.parse(listSandboxesRequest));
}
export function listSandboxesRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListSandboxesRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListSandboxesRequest' from JSON`);
}
/** @internal */
export const ListSandboxesResponseBodyPagination$inboundSchema = z.object({
    total: types.number(),
    count: types.number(),
    next: types.nullable(types.number()),
    prev: types.nullable(types.number()),
});
/** @internal */
export const ListSandboxesResponseBodyPagination$outboundSchema = z.object({
    total: z.number(),
    count: z.number(),
    next: z.nullable(z.number()),
    prev: z.nullable(z.number()),
});
export function listSandboxesResponseBodyPaginationToJSON(listSandboxesResponseBodyPagination) {
    return JSON.stringify(ListSandboxesResponseBodyPagination$outboundSchema.parse(listSandboxesResponseBodyPagination));
}
export function listSandboxesResponseBodyPaginationFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListSandboxesResponseBodyPagination$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListSandboxesResponseBodyPagination' from JSON`);
}
/** @internal */
export const ListSandboxesResponseBody2$inboundSchema = z.object({
    sandboxes: z.array(Sandbox$inboundSchema),
    pagination: z.lazy(() => ListSandboxesResponseBodyPagination$inboundSchema),
});
/** @internal */
export const ListSandboxesResponseBody2$outboundSchema = z.object({
    sandboxes: z.array(Sandbox$outboundSchema),
    pagination: z.lazy(() => ListSandboxesResponseBodyPagination$outboundSchema),
});
export function listSandboxesResponseBody2ToJSON(listSandboxesResponseBody2) {
    return JSON.stringify(ListSandboxesResponseBody2$outboundSchema.parse(listSandboxesResponseBody2));
}
export function listSandboxesResponseBody2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListSandboxesResponseBody2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListSandboxesResponseBody2' from JSON`);
}
/** @internal */
export const ListSandboxesResponseBody1$inboundSchema = z.object({});
/** @internal */
export const ListSandboxesResponseBody1$outboundSchema = z.object({});
export function listSandboxesResponseBody1ToJSON(listSandboxesResponseBody1) {
    return JSON.stringify(ListSandboxesResponseBody1$outboundSchema.parse(listSandboxesResponseBody1));
}
export function listSandboxesResponseBody1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListSandboxesResponseBody1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListSandboxesResponseBody1' from JSON`);
}
/** @internal */
export const ListSandboxesResponseBody$inboundSchema = smartUnion([
    z.lazy(() => ListSandboxesResponseBody2$inboundSchema),
    z.lazy(() => ListSandboxesResponseBody1$inboundSchema),
]);
/** @internal */
export const ListSandboxesResponseBody$outboundSchema = smartUnion([
    z.lazy(() => ListSandboxesResponseBody2$outboundSchema),
    z.lazy(() => ListSandboxesResponseBody1$outboundSchema),
]);
export function listSandboxesResponseBodyToJSON(listSandboxesResponseBody) {
    return JSON.stringify(ListSandboxesResponseBody$outboundSchema.parse(listSandboxesResponseBody));
}
export function listSandboxesResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListSandboxesResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListSandboxesResponseBody' from JSON`);
}
//# sourceMappingURL=listsandboxesop.js.map