/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
export const ListAccessGroupProjectsRole = {
    Admin: "ADMIN",
    ProjectDeveloper: "PROJECT_DEVELOPER",
    ProjectViewer: "PROJECT_VIEWER",
    ProjectGuest: "PROJECT_GUEST",
};
/** @internal */
export const ListAccessGroupProjectsRequest$inboundSchema = z.object({
    idOrName: types.string(),
    limit: types.optional(types.number()),
    next: types.optional(types.string()),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
});
/** @internal */
export const ListAccessGroupProjectsRequest$outboundSchema = z.object({
    idOrName: z.string(),
    limit: z.number().int().optional(),
    next: z.string().optional(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
});
export function listAccessGroupProjectsRequestToJSON(listAccessGroupProjectsRequest) {
    return JSON.stringify(ListAccessGroupProjectsRequest$outboundSchema.parse(listAccessGroupProjectsRequest));
}
export function listAccessGroupProjectsRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListAccessGroupProjectsRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListAccessGroupProjectsRequest' from JSON`);
}
/** @internal */
export const ListAccessGroupProjectsRole$inboundSchema = z.nativeEnum(ListAccessGroupProjectsRole);
/** @internal */
export const ListAccessGroupProjectsRole$outboundSchema = ListAccessGroupProjectsRole$inboundSchema;
/** @internal */
export const ListAccessGroupProjectsProject$inboundSchema = z.object({
    name: types.optional(types.string()),
    framework: z.nullable(types.string()).optional(),
    latestDeploymentId: types.optional(types.string()),
});
/** @internal */
export const ListAccessGroupProjectsProject$outboundSchema = z.object({
    name: z.string().optional(),
    framework: z.nullable(z.string()).optional(),
    latestDeploymentId: z.string().optional(),
});
export function listAccessGroupProjectsProjectToJSON(listAccessGroupProjectsProject) {
    return JSON.stringify(ListAccessGroupProjectsProject$outboundSchema.parse(listAccessGroupProjectsProject));
}
export function listAccessGroupProjectsProjectFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListAccessGroupProjectsProject$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListAccessGroupProjectsProject' from JSON`);
}
/** @internal */
export const ListAccessGroupProjectsProjects$inboundSchema = z.object({
    projectId: types.string(),
    role: ListAccessGroupProjectsRole$inboundSchema,
    createdAt: types.string(),
    updatedAt: types.string(),
    project: z.lazy(() => ListAccessGroupProjectsProject$inboundSchema),
});
/** @internal */
export const ListAccessGroupProjectsProjects$outboundSchema = z.object({
    projectId: z.string(),
    role: ListAccessGroupProjectsRole$outboundSchema,
    createdAt: z.string(),
    updatedAt: z.string(),
    project: z.lazy(() => ListAccessGroupProjectsProject$outboundSchema),
});
export function listAccessGroupProjectsProjectsToJSON(listAccessGroupProjectsProjects) {
    return JSON.stringify(ListAccessGroupProjectsProjects$outboundSchema.parse(listAccessGroupProjectsProjects));
}
export function listAccessGroupProjectsProjectsFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListAccessGroupProjectsProjects$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListAccessGroupProjectsProjects' from JSON`);
}
/** @internal */
export const ListAccessGroupProjectsPagination$inboundSchema = z.object({
    count: types.number(),
    next: types.nullable(types.string()),
});
/** @internal */
export const ListAccessGroupProjectsPagination$outboundSchema = z.object({
    count: z.number(),
    next: z.nullable(z.string()),
});
export function listAccessGroupProjectsPaginationToJSON(listAccessGroupProjectsPagination) {
    return JSON.stringify(ListAccessGroupProjectsPagination$outboundSchema.parse(listAccessGroupProjectsPagination));
}
export function listAccessGroupProjectsPaginationFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListAccessGroupProjectsPagination$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListAccessGroupProjectsPagination' from JSON`);
}
/** @internal */
export const ListAccessGroupProjectsResponseBody$inboundSchema = z.object({
    projects: z.array(z.lazy(() => ListAccessGroupProjectsProjects$inboundSchema)),
    pagination: z.lazy(() => ListAccessGroupProjectsPagination$inboundSchema),
});
/** @internal */
export const ListAccessGroupProjectsResponseBody$outboundSchema = z.object({
    projects: z.array(z.lazy(() => ListAccessGroupProjectsProjects$outboundSchema)),
    pagination: z.lazy(() => ListAccessGroupProjectsPagination$outboundSchema),
});
export function listAccessGroupProjectsResponseBodyToJSON(listAccessGroupProjectsResponseBody) {
    return JSON.stringify(ListAccessGroupProjectsResponseBody$outboundSchema.parse(listAccessGroupProjectsResponseBody));
}
export function listAccessGroupProjectsResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListAccessGroupProjectsResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListAccessGroupProjectsResponseBody' from JSON`);
}
//# sourceMappingURL=listaccessgroupprojectsop.js.map