/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import * as types from "../types/primitives.js";
import { VercelError } from "./vercelerror.js";
export const NotFoundCode = {
    NotFound: "not_found",
};
export class NotFound extends VercelError {
    constructor(err, httpMeta) {
        const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
        super(message, httpMeta);
        this.data$ = err;
        this.status = err.status;
        this.code = err.code;
        this.name = "NotFound";
    }
}
/** @internal */
export const NotFoundCode$inboundSchema = z.nativeEnum(NotFoundCode);
/** @internal */
export const NotFoundCode$outboundSchema = NotFoundCode$inboundSchema;
/** @internal */
export const NotFound$inboundSchema = z.object({
    status: types.number(),
    code: NotFoundCode$inboundSchema,
    message: types.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
})
    .transform((v) => {
    return new NotFound(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
    });
});
/** @internal */
export const NotFound$outboundSchema = z.instanceof(NotFound)
    .transform(v => v.data$)
    .pipe(z.object({
    status: z.number(),
    code: NotFoundCode$outboundSchema,
    message: z.string(),
}));
//# sourceMappingURL=notfound.js.map