/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import * as types from "../types/primitives.js";
import { VercelError } from "./vercelerror.js";
export const OrderTooExpensiveCode = {
    OrderTooExpensive: "order_too_expensive",
};
/**
 * The total price of the order is too high.
 */
export class OrderTooExpensive extends VercelError {
    constructor(err, httpMeta) {
        const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
        super(message, httpMeta);
        this.data$ = err;
        this.status = err.status;
        this.code = err.code;
        this.name = "OrderTooExpensive";
    }
}
/** @internal */
export const OrderTooExpensiveCode$inboundSchema = z.nativeEnum(OrderTooExpensiveCode);
/** @internal */
export const OrderTooExpensiveCode$outboundSchema = OrderTooExpensiveCode$inboundSchema;
/** @internal */
export const OrderTooExpensive$inboundSchema = z.object({
    status: types.number(),
    code: OrderTooExpensiveCode$inboundSchema,
    message: types.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
})
    .transform((v) => {
    return new OrderTooExpensive(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
    });
});
/** @internal */
export const OrderTooExpensive$outboundSchema = z.instanceof(OrderTooExpensive)
    .transform(v => v.data$)
    .pipe(z.object({
    status: z.number(),
    code: OrderTooExpensiveCode$outboundSchema,
    message: z.string(),
}));
//# sourceMappingURL=ordertooexpensive.js.map