/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
/** @internal */
export const PatchDomainRequestBody2$inboundSchema = z.object({
    op: types.optional(types.string()),
    destination: types.optional(types.string()),
});
/** @internal */
export const PatchDomainRequestBody2$outboundSchema = z.object({
    op: z.string().optional(),
    destination: z.string().optional(),
});
export function patchDomainRequestBody2ToJSON(patchDomainRequestBody2) {
    return JSON.stringify(PatchDomainRequestBody2$outboundSchema.parse(patchDomainRequestBody2));
}
export function patchDomainRequestBody2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => PatchDomainRequestBody2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PatchDomainRequestBody2' from JSON`);
}
/** @internal */
export const PatchDomainRequestBody1$inboundSchema = z.object({
    op: types.optional(types.string()),
    renew: types.optional(types.boolean()),
    customNameservers: types.optional(z.array(types.string())),
    zone: types.optional(types.boolean()),
});
/** @internal */
export const PatchDomainRequestBody1$outboundSchema = z.object({
    op: z.string().optional(),
    renew: z.boolean().optional(),
    customNameservers: z.array(z.string()).optional(),
    zone: z.boolean().optional(),
});
export function patchDomainRequestBody1ToJSON(patchDomainRequestBody1) {
    return JSON.stringify(PatchDomainRequestBody1$outboundSchema.parse(patchDomainRequestBody1));
}
export function patchDomainRequestBody1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => PatchDomainRequestBody1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PatchDomainRequestBody1' from JSON`);
}
/** @internal */
export const PatchDomainRequestBody$inboundSchema = smartUnion([
    z.lazy(() => PatchDomainRequestBody1$inboundSchema),
    z.lazy(() => PatchDomainRequestBody2$inboundSchema),
]);
/** @internal */
export const PatchDomainRequestBody$outboundSchema = smartUnion([
    z.lazy(() => PatchDomainRequestBody1$outboundSchema),
    z.lazy(() => PatchDomainRequestBody2$outboundSchema),
]);
export function patchDomainRequestBodyToJSON(patchDomainRequestBody) {
    return JSON.stringify(PatchDomainRequestBody$outboundSchema.parse(patchDomainRequestBody));
}
export function patchDomainRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PatchDomainRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PatchDomainRequestBody' from JSON`);
}
/** @internal */
export const PatchDomainRequest$inboundSchema = z.object({
    domain: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
    RequestBody: smartUnion([
        z.lazy(() => PatchDomainRequestBody1$inboundSchema),
        z.lazy(() => PatchDomainRequestBody2$inboundSchema),
    ]),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const PatchDomainRequest$outboundSchema = z.object({
    domain: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
    requestBody: smartUnion([
        z.lazy(() => PatchDomainRequestBody1$outboundSchema),
        z.lazy(() => PatchDomainRequestBody2$outboundSchema),
    ]),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function patchDomainRequestToJSON(patchDomainRequest) {
    return JSON.stringify(PatchDomainRequest$outboundSchema.parse(patchDomainRequest));
}
export function patchDomainRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PatchDomainRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PatchDomainRequest' from JSON`);
}
/** @internal */
export const PatchDomainResponseBody3$inboundSchema = z.object({
    renew: types.optional(types.boolean()),
    customNameservers: types.optional(z.array(types.string())),
    zone: types.optional(types.boolean()),
});
/** @internal */
export const PatchDomainResponseBody3$outboundSchema = z.object({
    renew: z.boolean().optional(),
    customNameservers: z.array(z.string()).optional(),
    zone: z.boolean().optional(),
});
export function patchDomainResponseBody3ToJSON(patchDomainResponseBody3) {
    return JSON.stringify(PatchDomainResponseBody3$outboundSchema.parse(patchDomainResponseBody3));
}
export function patchDomainResponseBody3FromJSON(jsonString) {
    return safeParse(jsonString, (x) => PatchDomainResponseBody3$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PatchDomainResponseBody3' from JSON`);
}
/** @internal */
export const PatchDomainResponseBody2$inboundSchema = z.object({
    moved: types.boolean(),
    token: types.string(),
});
/** @internal */
export const PatchDomainResponseBody2$outboundSchema = z.object({
    moved: z.boolean(),
    token: z.string(),
});
export function patchDomainResponseBody2ToJSON(patchDomainResponseBody2) {
    return JSON.stringify(PatchDomainResponseBody2$outboundSchema.parse(patchDomainResponseBody2));
}
export function patchDomainResponseBody2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => PatchDomainResponseBody2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PatchDomainResponseBody2' from JSON`);
}
/** @internal */
export const PatchDomainResponseBody1$inboundSchema = z.object({
    moved: types.boolean(),
});
/** @internal */
export const PatchDomainResponseBody1$outboundSchema = z.object({
    moved: z.boolean(),
});
export function patchDomainResponseBody1ToJSON(patchDomainResponseBody1) {
    return JSON.stringify(PatchDomainResponseBody1$outboundSchema.parse(patchDomainResponseBody1));
}
export function patchDomainResponseBody1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => PatchDomainResponseBody1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PatchDomainResponseBody1' from JSON`);
}
/** @internal */
export const PatchDomainResponseBody$inboundSchema = smartUnion([
    z.lazy(() => PatchDomainResponseBody2$inboundSchema),
    z.lazy(() => PatchDomainResponseBody1$inboundSchema),
    z.lazy(() => PatchDomainResponseBody3$inboundSchema),
]);
/** @internal */
export const PatchDomainResponseBody$outboundSchema = smartUnion([
    z.lazy(() => PatchDomainResponseBody2$outboundSchema),
    z.lazy(() => PatchDomainResponseBody1$outboundSchema),
    z.lazy(() => PatchDomainResponseBody3$outboundSchema),
]);
export function patchDomainResponseBodyToJSON(patchDomainResponseBody) {
    return JSON.stringify(PatchDomainResponseBody$outboundSchema.parse(patchDomainResponseBody));
}
export function patchDomainResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PatchDomainResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PatchDomainResponseBody' from JSON`);
}
//# sourceMappingURL=patchdomainop.js.map