/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
/** @internal */
export const PatchEdgeConfigSchemaRequestBody$inboundSchema = z.object({
    definition: types.optional(z.any()),
});
/** @internal */
export const PatchEdgeConfigSchemaRequestBody$outboundSchema = z.object({
    definition: z.any().optional(),
});
export function patchEdgeConfigSchemaRequestBodyToJSON(patchEdgeConfigSchemaRequestBody) {
    return JSON.stringify(PatchEdgeConfigSchemaRequestBody$outboundSchema.parse(patchEdgeConfigSchemaRequestBody));
}
export function patchEdgeConfigSchemaRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PatchEdgeConfigSchemaRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PatchEdgeConfigSchemaRequestBody' from JSON`);
}
/** @internal */
export const PatchEdgeConfigSchemaRequest$inboundSchema = z.object({
    edgeConfigId: types.string(),
    dryRun: types.optional(types.string()),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
    RequestBody: z.lazy(() => PatchEdgeConfigSchemaRequestBody$inboundSchema),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const PatchEdgeConfigSchemaRequest$outboundSchema = z.object({
    edgeConfigId: z.string(),
    dryRun: z.string().optional(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
    requestBody: z.lazy(() => PatchEdgeConfigSchemaRequestBody$outboundSchema),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function patchEdgeConfigSchemaRequestToJSON(patchEdgeConfigSchemaRequest) {
    return JSON.stringify(PatchEdgeConfigSchemaRequest$outboundSchema.parse(patchEdgeConfigSchemaRequest));
}
export function patchEdgeConfigSchemaRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PatchEdgeConfigSchemaRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PatchEdgeConfigSchemaRequest' from JSON`);
}
/** @internal */
export const PatchEdgeConfigSchemaResponseBody$inboundSchema = z.object({});
/** @internal */
export const PatchEdgeConfigSchemaResponseBody$outboundSchema = z.object({});
export function patchEdgeConfigSchemaResponseBodyToJSON(patchEdgeConfigSchemaResponseBody) {
    return JSON.stringify(PatchEdgeConfigSchemaResponseBody$outboundSchema.parse(patchEdgeConfigSchemaResponseBody));
}
export function patchEdgeConfigSchemaResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PatchEdgeConfigSchemaResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PatchEdgeConfigSchemaResponseBody' from JSON`);
}
//# sourceMappingURL=patchedgeconfigschemaop.js.map