/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
/** @internal */
export const PauseProjectRequest$inboundSchema = z.object({
    projectId: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
});
/** @internal */
export const PauseProjectRequest$outboundSchema = z.object({
    projectId: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
});
export function pauseProjectRequestToJSON(pauseProjectRequest) {
    return JSON.stringify(PauseProjectRequest$outboundSchema.parse(pauseProjectRequest));
}
export function pauseProjectRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PauseProjectRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PauseProjectRequest' from JSON`);
}
//# sourceMappingURL=pauseprojectop.js.map