/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
/** @internal */
export const RerequestCheckRequest$inboundSchema = z.object({
    deploymentId: types.string(),
    checkId: types.string(),
    autoUpdate: types.optional(types.boolean()),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
});
/** @internal */
export const RerequestCheckRequest$outboundSchema = z.object({
    deploymentId: z.string(),
    checkId: z.string(),
    autoUpdate: z.boolean().optional(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
});
export function rerequestCheckRequestToJSON(rerequestCheckRequest) {
    return JSON.stringify(RerequestCheckRequest$outboundSchema.parse(rerequestCheckRequest));
}
export function rerequestCheckRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RerequestCheckRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RerequestCheckRequest' from JSON`);
}
/** @internal */
export const RerequestCheckResponseBody$inboundSchema = z.object({});
/** @internal */
export const RerequestCheckResponseBody$outboundSchema = z.object({});
export function rerequestCheckResponseBodyToJSON(rerequestCheckResponseBody) {
    return JSON.stringify(RerequestCheckResponseBody$outboundSchema.parse(rerequestCheckResponseBody));
}
export function rerequestCheckResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RerequestCheckResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RerequestCheckResponseBody' from JSON`);
}
//# sourceMappingURL=rerequestcheckop.js.map