/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
/** @internal */
export const RestoreRedirectsRequestBody$inboundSchema = z.object({
    name: types.optional(types.string()),
    redirects: z.array(types.string()),
});
/** @internal */
export const RestoreRedirectsRequestBody$outboundSchema = z.object({
    name: z.string().optional(),
    redirects: z.array(z.string()),
});
export function restoreRedirectsRequestBodyToJSON(restoreRedirectsRequestBody) {
    return JSON.stringify(RestoreRedirectsRequestBody$outboundSchema.parse(restoreRedirectsRequestBody));
}
export function restoreRedirectsRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RestoreRedirectsRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RestoreRedirectsRequestBody' from JSON`);
}
/** @internal */
export const RestoreRedirectsRequest$inboundSchema = z.object({
    projectId: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
    RequestBody: types.optional(z.lazy(() => RestoreRedirectsRequestBody$inboundSchema)),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const RestoreRedirectsRequest$outboundSchema = z.object({
    projectId: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
    requestBody: z.lazy(() => RestoreRedirectsRequestBody$outboundSchema)
        .optional(),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function restoreRedirectsRequestToJSON(restoreRedirectsRequest) {
    return JSON.stringify(RestoreRedirectsRequest$outboundSchema.parse(restoreRedirectsRequest));
}
export function restoreRedirectsRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RestoreRedirectsRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RestoreRedirectsRequest' from JSON`);
}
/** @internal */
export const RestoreRedirectsVersion$inboundSchema = z.object({
    id: types.string(),
    key: types.string(),
    lastModified: types.number(),
    createdBy: types.string(),
    name: types.optional(types.string()),
    isStaging: types.optional(types.boolean()),
    isLive: types.optional(types.boolean()),
    redirectCount: types.optional(types.number()),
    alias: types.optional(types.string()),
});
/** @internal */
export const RestoreRedirectsVersion$outboundSchema = z.object({
    id: z.string(),
    key: z.string(),
    lastModified: z.number(),
    createdBy: z.string(),
    name: z.string().optional(),
    isStaging: z.boolean().optional(),
    isLive: z.boolean().optional(),
    redirectCount: z.number().optional(),
    alias: z.string().optional(),
});
export function restoreRedirectsVersionToJSON(restoreRedirectsVersion) {
    return JSON.stringify(RestoreRedirectsVersion$outboundSchema.parse(restoreRedirectsVersion));
}
export function restoreRedirectsVersionFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RestoreRedirectsVersion$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RestoreRedirectsVersion' from JSON`);
}
/** @internal */
export const RestoreRedirectsResponseBody$inboundSchema = z.object({
    version: z.lazy(() => RestoreRedirectsVersion$inboundSchema),
    restored: z.array(types.string()),
    failedToRestore: z.array(types.string()),
});
/** @internal */
export const RestoreRedirectsResponseBody$outboundSchema = z.object({
    version: z.lazy(() => RestoreRedirectsVersion$outboundSchema),
    restored: z.array(z.string()),
    failedToRestore: z.array(z.string()),
});
export function restoreRedirectsResponseBodyToJSON(restoreRedirectsResponseBody) {
    return JSON.stringify(RestoreRedirectsResponseBody$outboundSchema.parse(restoreRedirectsResponseBody));
}
export function restoreRedirectsResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RestoreRedirectsResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RestoreRedirectsResponseBody' from JSON`);
}
//# sourceMappingURL=restoreredirectsop.js.map