/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { JsonLStream } from "../lib/jsonl.js";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
import { SandboxCommand$inboundSchema, SandboxCommand$outboundSchema, } from "./sandboxcommand.js";
/** @internal */
export const RunCommandRequestBody$inboundSchema = z.object({
    command: types.string(),
    args: types.optional(z.array(types.string())),
    cwd: types.optional(types.string()),
    env: types.optional(z.record(types.string())),
    sudo: types.boolean().default(false),
    wait: types.boolean().default(false),
});
/** @internal */
export const RunCommandRequestBody$outboundSchema = z.object({
    command: z.string(),
    args: z.array(z.string()).optional(),
    cwd: z.string().optional(),
    env: z.record(z.string()).optional(),
    sudo: z.boolean().default(false),
    wait: z.boolean().default(false),
});
export function runCommandRequestBodyToJSON(runCommandRequestBody) {
    return JSON.stringify(RunCommandRequestBody$outboundSchema.parse(runCommandRequestBody));
}
export function runCommandRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RunCommandRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RunCommandRequestBody' from JSON`);
}
/** @internal */
export const RunCommandRequest$inboundSchema = z.object({
    sandboxId: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
    RequestBody: types.optional(z.lazy(() => RunCommandRequestBody$inboundSchema)),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const RunCommandRequest$outboundSchema = z.object({
    sandboxId: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
    requestBody: z.lazy(() => RunCommandRequestBody$outboundSchema).optional(),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function runCommandRequestToJSON(runCommandRequest) {
    return JSON.stringify(RunCommandRequest$outboundSchema.parse(runCommandRequest));
}
export function runCommandRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RunCommandRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RunCommandRequest' from JSON`);
}
/** @internal */
export const RunCommandSandboxesResponseBody$inboundSchema = z.object({
    command: SandboxCommand$inboundSchema,
});
/** @internal */
export const RunCommandSandboxesResponseBody$outboundSchema = z.object({
    command: SandboxCommand$outboundSchema,
});
export function runCommandSandboxesResponseBodyToJSON(runCommandSandboxesResponseBody) {
    return JSON.stringify(RunCommandSandboxesResponseBody$outboundSchema.parse(runCommandSandboxesResponseBody));
}
export function runCommandSandboxesResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RunCommandSandboxesResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RunCommandSandboxesResponseBody' from JSON`);
}
/** @internal */
export const RunCommandResponseBody$inboundSchema = z.object({
    command: SandboxCommand$inboundSchema,
});
/** @internal */
export const RunCommandResponseBody$outboundSchema = z.object({
    command: SandboxCommand$outboundSchema,
});
export function runCommandResponseBodyToJSON(runCommandResponseBody) {
    return JSON.stringify(RunCommandResponseBody$outboundSchema.parse(runCommandResponseBody));
}
export function runCommandResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RunCommandResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RunCommandResponseBody' from JSON`);
}
/** @internal */
export const RunCommandResponse$inboundSchema = smartUnion([
    z.lazy(() => RunCommandResponseBody$inboundSchema),
    z.instanceof((ReadableStream)).transform(stream => {
        return new JsonLStream({
            stream,
            decoder(rawEvent) {
                const schema = z.lazy(() => RunCommandSandboxesResponseBody$inboundSchema);
                return schema.parse(rawEvent);
            },
        });
    }),
]);
/** @internal */
export const RunCommandResponse$outboundSchema = smartUnion([
    z.lazy(() => RunCommandResponseBody$outboundSchema),
    z.never(),
]);
export function runCommandResponseToJSON(runCommandResponse) {
    return JSON.stringify(RunCommandResponse$outboundSchema.parse(runCommandResponse));
}
export function runCommandResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RunCommandResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RunCommandResponse' from JSON`);
}
//# sourceMappingURL=runcommandop.js.map