/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
export const UpdateDeploymentCheckRunStatus = {
    Queued: "queued",
    Running: "running",
    Completed: "completed",
};
export const Conclusion = {
    Canceled: "canceled",
    Skipped: "skipped",
    Timeout: "timeout",
    Failed: "failed",
    Neutral: "neutral",
    Succeeded: "succeeded",
};
export const UpdateDeploymentCheckRunSourceProvider = {
    Github: "github",
    Gitlab: "gitlab",
    Bitbucket: "bitbucket",
};
export const UpdateDeploymentCheckRunRequires = {
    BuildReady: "build-ready",
    DeploymentUrl: "deployment-url",
    None: "none",
};
export const UpdateDeploymentCheckRunBlocks = {
    None: "none",
    BuildStart: "build-start",
    DeploymentStart: "deployment-start",
    DeploymentAlias: "deployment-alias",
    DeploymentPromotion: "deployment-promotion",
};
export const UpdateDeploymentCheckRunChecksV2Status = {
    Queued: "queued",
    Running: "running",
    Completed: "completed",
};
export const UpdateDeploymentCheckRunConclusion = {
    Timeout: "timeout",
    Canceled: "canceled",
    Skipped: "skipped",
    Failed: "failed",
    Neutral: "neutral",
    Succeeded: "succeeded",
};
/** @internal */
export const UpdateDeploymentCheckRunStatus$inboundSchema = z.nativeEnum(UpdateDeploymentCheckRunStatus);
/** @internal */
export const UpdateDeploymentCheckRunStatus$outboundSchema = UpdateDeploymentCheckRunStatus$inboundSchema;
/** @internal */
export const Output$inboundSchema = z
    .object({});
/** @internal */
export const Output$outboundSchema = z.object({});
export function outputToJSON(output) {
    return JSON.stringify(Output$outboundSchema.parse(output));
}
export function outputFromJSON(jsonString) {
    return safeParse(jsonString, (x) => Output$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'Output' from JSON`);
}
/** @internal */
export const Conclusion$inboundSchema = z
    .nativeEnum(Conclusion);
/** @internal */
export const Conclusion$outboundSchema = Conclusion$inboundSchema;
/** @internal */
export const UpdateDeploymentCheckRunRequestBody$inboundSchema = z.object({
    externalId: types.optional(types.string()),
    externalUrl: types.optional(types.string()),
    status: types.optional(UpdateDeploymentCheckRunStatus$inboundSchema),
    output: types.optional(z.lazy(() => Output$inboundSchema)),
    completedAt: types.optional(types.number()),
    conclusion: types.optional(Conclusion$inboundSchema),
    conclusionText: types.optional(types.string()),
});
/** @internal */
export const UpdateDeploymentCheckRunRequestBody$outboundSchema = z.object({
    externalId: z.string().optional(),
    externalUrl: z.string().optional(),
    status: UpdateDeploymentCheckRunStatus$outboundSchema.optional(),
    output: z.lazy(() => Output$outboundSchema).optional(),
    completedAt: z.number().optional(),
    conclusion: Conclusion$outboundSchema.optional(),
    conclusionText: z.string().optional(),
});
export function updateDeploymentCheckRunRequestBodyToJSON(updateDeploymentCheckRunRequestBody) {
    return JSON.stringify(UpdateDeploymentCheckRunRequestBody$outboundSchema.parse(updateDeploymentCheckRunRequestBody));
}
export function updateDeploymentCheckRunRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateDeploymentCheckRunRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateDeploymentCheckRunRequestBody' from JSON`);
}
/** @internal */
export const UpdateDeploymentCheckRunRequest$inboundSchema = z.object({
    deploymentId: types.string(),
    checkRunId: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
    RequestBody: types.optional(z.lazy(() => UpdateDeploymentCheckRunRequestBody$inboundSchema)),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const UpdateDeploymentCheckRunRequest$outboundSchema = z.object({
    deploymentId: z.string(),
    checkRunId: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
    requestBody: z.lazy(() => UpdateDeploymentCheckRunRequestBody$outboundSchema)
        .optional(),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function updateDeploymentCheckRunRequestToJSON(updateDeploymentCheckRunRequest) {
    return JSON.stringify(UpdateDeploymentCheckRunRequest$outboundSchema.parse(updateDeploymentCheckRunRequest));
}
export function updateDeploymentCheckRunRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateDeploymentCheckRunRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateDeploymentCheckRunRequest' from JSON`);
}
/** @internal */
export const UpdateDeploymentCheckRunSourceProvider$inboundSchema = z.nativeEnum(UpdateDeploymentCheckRunSourceProvider);
/** @internal */
export const UpdateDeploymentCheckRunSourceProvider$outboundSchema = UpdateDeploymentCheckRunSourceProvider$inboundSchema;
/** @internal */
export const UpdateDeploymentCheckRunSource3$inboundSchema = z.object({
    kind: types.literal("git-provider"),
    provider: UpdateDeploymentCheckRunSourceProvider$inboundSchema,
    externalCheckName: types.string(),
});
/** @internal */
export const UpdateDeploymentCheckRunSource3$outboundSchema = z.object({
    kind: z.literal("git-provider"),
    provider: UpdateDeploymentCheckRunSourceProvider$outboundSchema,
    externalCheckName: z.string(),
});
export function updateDeploymentCheckRunSource3ToJSON(updateDeploymentCheckRunSource3) {
    return JSON.stringify(UpdateDeploymentCheckRunSource3$outboundSchema.parse(updateDeploymentCheckRunSource3));
}
export function updateDeploymentCheckRunSource3FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateDeploymentCheckRunSource3$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateDeploymentCheckRunSource3' from JSON`);
}
/** @internal */
export const UpdateDeploymentCheckRunSource2$inboundSchema = z.object({
    kind: types.literal("webhook"),
    webhookId: types.optional(types.string()),
});
/** @internal */
export const UpdateDeploymentCheckRunSource2$outboundSchema = z.object({
    kind: z.literal("webhook"),
    webhookId: z.string().optional(),
});
export function updateDeploymentCheckRunSource2ToJSON(updateDeploymentCheckRunSource2) {
    return JSON.stringify(UpdateDeploymentCheckRunSource2$outboundSchema.parse(updateDeploymentCheckRunSource2));
}
export function updateDeploymentCheckRunSource2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateDeploymentCheckRunSource2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateDeploymentCheckRunSource2' from JSON`);
}
/** @internal */
export const UpdateDeploymentCheckRunSource1$inboundSchema = z.object({
    kind: types.literal("integration"),
    integrationId: types.string(),
    integrationConfigurationId: types.string(),
    resourceId: types.optional(types.string()),
    externalResourceId: types.optional(types.string()),
});
/** @internal */
export const UpdateDeploymentCheckRunSource1$outboundSchema = z.object({
    kind: z.literal("integration"),
    integrationId: z.string(),
    integrationConfigurationId: z.string(),
    resourceId: z.string().optional(),
    externalResourceId: z.string().optional(),
});
export function updateDeploymentCheckRunSource1ToJSON(updateDeploymentCheckRunSource1) {
    return JSON.stringify(UpdateDeploymentCheckRunSource1$outboundSchema.parse(updateDeploymentCheckRunSource1));
}
export function updateDeploymentCheckRunSource1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateDeploymentCheckRunSource1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateDeploymentCheckRunSource1' from JSON`);
}
/** @internal */
export const UpdateDeploymentCheckRunSource$inboundSchema = z.union([
    z.lazy(() => UpdateDeploymentCheckRunSource1$inboundSchema),
    z.lazy(() => UpdateDeploymentCheckRunSource2$inboundSchema),
    z.lazy(() => UpdateDeploymentCheckRunSource3$inboundSchema),
]);
/** @internal */
export const UpdateDeploymentCheckRunSource$outboundSchema = z.union([
    z.lazy(() => UpdateDeploymentCheckRunSource1$outboundSchema),
    z.lazy(() => UpdateDeploymentCheckRunSource2$outboundSchema),
    z.lazy(() => UpdateDeploymentCheckRunSource3$outboundSchema),
]);
export function updateDeploymentCheckRunSourceToJSON(updateDeploymentCheckRunSource) {
    return JSON.stringify(UpdateDeploymentCheckRunSource$outboundSchema.parse(updateDeploymentCheckRunSource));
}
export function updateDeploymentCheckRunSourceFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateDeploymentCheckRunSource$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateDeploymentCheckRunSource' from JSON`);
}
/** @internal */
export const UpdateDeploymentCheckRunRequires$inboundSchema = z.nativeEnum(UpdateDeploymentCheckRunRequires);
/** @internal */
export const UpdateDeploymentCheckRunRequires$outboundSchema = UpdateDeploymentCheckRunRequires$inboundSchema;
/** @internal */
export const UpdateDeploymentCheckRunBlocks$inboundSchema = z.nativeEnum(UpdateDeploymentCheckRunBlocks);
/** @internal */
export const UpdateDeploymentCheckRunBlocks$outboundSchema = UpdateDeploymentCheckRunBlocks$inboundSchema;
/** @internal */
export const UpdateDeploymentCheckRunChecksV2Status$inboundSchema = z.nativeEnum(UpdateDeploymentCheckRunChecksV2Status);
/** @internal */
export const UpdateDeploymentCheckRunChecksV2Status$outboundSchema = UpdateDeploymentCheckRunChecksV2Status$inboundSchema;
/** @internal */
export const UpdateDeploymentCheckRunConclusion$inboundSchema = z.nativeEnum(UpdateDeploymentCheckRunConclusion);
/** @internal */
export const UpdateDeploymentCheckRunConclusion$outboundSchema = UpdateDeploymentCheckRunConclusion$inboundSchema;
/** @internal */
export const UpdateDeploymentCheckRunResponseBody$inboundSchema = z.object({
    id: types.string(),
    name: types.string(),
    checkId: types.string(),
    ownerId: types.string(),
    deploymentId: types.string(),
    projectId: types.optional(types.string()),
    source: z.union([
        z.lazy(() => UpdateDeploymentCheckRunSource1$inboundSchema),
        z.lazy(() => UpdateDeploymentCheckRunSource2$inboundSchema),
        z.lazy(() => UpdateDeploymentCheckRunSource3$inboundSchema),
    ]),
    requires: types.optional(UpdateDeploymentCheckRunRequires$inboundSchema),
    blocks: types.optional(UpdateDeploymentCheckRunBlocks$inboundSchema),
    targets: types.optional(z.array(types.string())),
    status: UpdateDeploymentCheckRunChecksV2Status$inboundSchema,
    conclusion: types.optional(UpdateDeploymentCheckRunConclusion$inboundSchema),
    conclusionText: types.optional(types.string()),
    externalId: types.optional(types.string()),
    externalUrl: types.optional(types.string()),
    output: types.optional(z.record(z.any())),
    timeout: types.number(),
    createdAt: types.number(),
    updatedAt: types.number(),
    completedAt: types.optional(types.number()),
});
/** @internal */
export const UpdateDeploymentCheckRunResponseBody$outboundSchema = z.object({
    id: z.string(),
    name: z.string(),
    checkId: z.string(),
    ownerId: z.string(),
    deploymentId: z.string(),
    projectId: z.string().optional(),
    source: z.union([
        z.lazy(() => UpdateDeploymentCheckRunSource1$outboundSchema),
        z.lazy(() => UpdateDeploymentCheckRunSource2$outboundSchema),
        z.lazy(() => UpdateDeploymentCheckRunSource3$outboundSchema),
    ]),
    requires: UpdateDeploymentCheckRunRequires$outboundSchema.optional(),
    blocks: UpdateDeploymentCheckRunBlocks$outboundSchema.optional(),
    targets: z.array(z.string()).optional(),
    status: UpdateDeploymentCheckRunChecksV2Status$outboundSchema,
    conclusion: UpdateDeploymentCheckRunConclusion$outboundSchema.optional(),
    conclusionText: z.string().optional(),
    externalId: z.string().optional(),
    externalUrl: z.string().optional(),
    output: z.record(z.any()).optional(),
    timeout: z.number(),
    createdAt: z.number(),
    updatedAt: z.number(),
    completedAt: z.number().optional(),
});
export function updateDeploymentCheckRunResponseBodyToJSON(updateDeploymentCheckRunResponseBody) {
    return JSON.stringify(UpdateDeploymentCheckRunResponseBody$outboundSchema.parse(updateDeploymentCheckRunResponseBody));
}
export function updateDeploymentCheckRunResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateDeploymentCheckRunResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateDeploymentCheckRunResponseBody' from JSON`);
}
//# sourceMappingURL=updatedeploymentcheckrunop.js.map