/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
/**
 * Status code for domain redirect
 */
export const RedirectStatusCode = {
    ThreeHundredAndOne: 301,
    ThreeHundredAndTwo: 302,
    ThreeHundredAndSeven: 307,
    ThreeHundredAndEight: 308,
};
/** @internal */
export const RedirectStatusCode$inboundSchema = z.nativeEnum(RedirectStatusCode);
/** @internal */
export const RedirectStatusCode$outboundSchema = RedirectStatusCode$inboundSchema;
/** @internal */
export const UpdateProjectDomainRequestBody$inboundSchema = z.object({
    gitBranch: z.nullable(types.string()).optional(),
    redirect: z.nullable(types.string()).optional(),
    redirectStatusCode: z.nullable(RedirectStatusCode$inboundSchema).optional(),
});
/** @internal */
export const UpdateProjectDomainRequestBody$outboundSchema = z.object({
    gitBranch: z.nullable(z.string()).optional(),
    redirect: z.nullable(z.string()).optional(),
    redirectStatusCode: z.nullable(RedirectStatusCode$outboundSchema).optional(),
});
export function updateProjectDomainRequestBodyToJSON(updateProjectDomainRequestBody) {
    return JSON.stringify(UpdateProjectDomainRequestBody$outboundSchema.parse(updateProjectDomainRequestBody));
}
export function updateProjectDomainRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateProjectDomainRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateProjectDomainRequestBody' from JSON`);
}
/** @internal */
export const UpdateProjectDomainRequest$inboundSchema = z.object({
    idOrName: types.string(),
    domain: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
    RequestBody: z.lazy(() => UpdateProjectDomainRequestBody$inboundSchema),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const UpdateProjectDomainRequest$outboundSchema = z.object({
    idOrName: z.string(),
    domain: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
    requestBody: z.lazy(() => UpdateProjectDomainRequestBody$outboundSchema),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function updateProjectDomainRequestToJSON(updateProjectDomainRequest) {
    return JSON.stringify(UpdateProjectDomainRequest$outboundSchema.parse(updateProjectDomainRequest));
}
export function updateProjectDomainRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateProjectDomainRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateProjectDomainRequest' from JSON`);
}
/** @internal */
export const UpdateProjectDomainVerification$inboundSchema = z.object({
    type: types.string(),
    domain: types.string(),
    value: types.string(),
    reason: types.string(),
});
/** @internal */
export const UpdateProjectDomainVerification$outboundSchema = z.object({
    type: z.string(),
    domain: z.string(),
    value: z.string(),
    reason: z.string(),
});
export function updateProjectDomainVerificationToJSON(updateProjectDomainVerification) {
    return JSON.stringify(UpdateProjectDomainVerification$outboundSchema.parse(updateProjectDomainVerification));
}
export function updateProjectDomainVerificationFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateProjectDomainVerification$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateProjectDomainVerification' from JSON`);
}
/** @internal */
export const UpdateProjectDomainResponseBody$inboundSchema = z.object({
    name: types.string(),
    apexName: types.string(),
    projectId: types.string(),
    redirect: z.nullable(types.string()).optional(),
    redirectStatusCode: z.nullable(types.number()).optional(),
    gitBranch: z.nullable(types.string()).optional(),
    customEnvironmentId: z.nullable(types.string()).optional(),
    updatedAt: types.optional(types.number()),
    createdAt: types.optional(types.number()),
    verified: types.boolean(),
    verification: types.optional(z.array(z.lazy(() => UpdateProjectDomainVerification$inboundSchema))),
});
/** @internal */
export const UpdateProjectDomainResponseBody$outboundSchema = z.object({
    name: z.string(),
    apexName: z.string(),
    projectId: z.string(),
    redirect: z.nullable(z.string()).optional(),
    redirectStatusCode: z.nullable(z.number()).optional(),
    gitBranch: z.nullable(z.string()).optional(),
    customEnvironmentId: z.nullable(z.string()).optional(),
    updatedAt: z.number().optional(),
    createdAt: z.number().optional(),
    verified: z.boolean(),
    verification: z.array(z.lazy(() => UpdateProjectDomainVerification$outboundSchema)).optional(),
});
export function updateProjectDomainResponseBodyToJSON(updateProjectDomainResponseBody) {
    return JSON.stringify(UpdateProjectDomainResponseBody$outboundSchema.parse(updateProjectDomainResponseBody));
}
export function updateProjectDomainResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateProjectDomainResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateProjectDomainResponseBody' from JSON`);
}
//# sourceMappingURL=updateprojectdomainop.js.map