/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smartUnion.js";
export const UpdateFirewallConfigRequestBodyId = {
    AiBots: "ai_bots",
    BotFilter: "bot_filter",
    BotProtection: "bot_protection",
    VercelRuleset: "vercel_ruleset",
    Owasp: "owasp",
};
export const UpdateFirewallConfigRequestBodySecurityRequest12Action = {
    Log: "log",
    Challenge: "challenge",
    Deny: "deny",
};
export const UpdateFirewallConfigRequestBodySecurityRequest11Action = {
    ManagedRulesUpdate: "managedRules.update",
};
export const RequestBodyId = {
    AiBots: "ai_bots",
    BotFilter: "bot_filter",
    BotProtection: "bot_protection",
    VercelRuleset: "vercel_ruleset",
    Owasp: "owasp",
};
export const UpdateFirewallConfigRequestBodySecurityRequest11ValueAction = {
    Log: "log",
    Challenge: "challenge",
    Deny: "deny",
};
export const UpdateFirewallConfigRequestBodySecurityRequest10Action = {
    IpRemove: "ip.remove",
};
export const UpdateFirewallConfigRequestBodySecurityRequest9Action = {
    IpUpdate: "ip.update",
};
export const UpdateFirewallConfigRequestBodySecurityRequest9ValueAction = {
    Deny: "deny",
    Challenge: "challenge",
    Log: "log",
    Bypass: "bypass",
};
export const UpdateFirewallConfigRequestBodySecurityRequest8Action = {
    IpInsert: "ip.insert",
};
export const UpdateFirewallConfigRequestBodySecurityRequest8ValueAction = {
    Deny: "deny",
    Challenge: "challenge",
    Log: "log",
    Bypass: "bypass",
};
export const UpdateFirewallConfigRequestBodySecurityRequest7Action = {
    CrsDisable: "crs.disable",
};
export const UpdateFirewallConfigRequestBodySecurityRequest6Action = {
    CrsUpdate: "crs.update",
};
export const Id = {
    Sd: "sd",
    Ma: "ma",
    Lfi: "lfi",
    Rfi: "rfi",
    Rce: "rce",
    Php: "php",
    Gen: "gen",
    Xss: "xss",
    Sqli: "sqli",
    Sf: "sf",
    Java: "java",
};
export const UpdateFirewallConfigRequestBodySecurityRequest6ValueAction = {
    Deny: "deny",
    Log: "log",
};
export const UpdateFirewallConfigRequestBodySecurityRequest5Action = {
    RulesPriority: "rules.priority",
};
export const UpdateFirewallConfigRequestBodySecurityRequest4Action = {
    RulesRemove: "rules.remove",
};
export const UpdateFirewallConfigRequestBodySecurityRequestAction = {
    RulesUpdate: "rules.update",
};
export const UpdateFirewallConfigRequestBodySecurityType = {
    Host: "host",
    Path: "path",
    Method: "method",
    Header: "header",
    Query: "query",
    Cookie: "cookie",
    TargetPath: "target_path",
    Route: "route",
    RawPath: "raw_path",
    IpAddress: "ip_address",
    Region: "region",
    Protocol: "protocol",
    Scheme: "scheme",
    Environment: "environment",
    UserAgent: "user_agent",
    GeoContinent: "geo_continent",
    GeoCountry: "geo_country",
    GeoCountryRegion: "geo_country_region",
    GeoCity: "geo_city",
    GeoAsNumber: "geo_as_number",
    Ja4Digest: "ja4_digest",
    Ja3Digest: "ja3_digest",
    RateLimitApiId: "rate_limit_api_id",
    ServerAction: "server_action",
    BotName: "bot_name",
    BotCategory: "bot_category",
};
export const UpdateFirewallConfigRequestBodyOp = {
    Re: "re",
    Eq: "eq",
    Neq: "neq",
    Ex: "ex",
    Nex: "nex",
    Inc: "inc",
    Ninc: "ninc",
    Pre: "pre",
    Suf: "suf",
    Sub: "sub",
    Gt: "gt",
    Gte: "gte",
    Lt: "lt",
    Lte: "lte",
};
export const UpdateFirewallConfigRequestBodySecurityRequest3ValueAction = {
    Log: "log",
    Challenge: "challenge",
    Deny: "deny",
    Bypass: "bypass",
    RateLimit: "rate_limit",
    Redirect: "redirect",
};
export const UpdateFirewallConfigRateLimitAlgo = {
    FixedWindow: "fixed_window",
    TokenBucket: "token_bucket",
};
export const UpdateFirewallConfigActionSecurity1 = {
    Log: "log",
    Challenge: "challenge",
    Deny: "deny",
    RateLimit: "rate_limit",
};
export const UpdateFirewallConfigRequestBodySecurityAction = {
    RulesInsert: "rules.insert",
};
export const UpdateFirewallConfigRequestBodyType = {
    Host: "host",
    Path: "path",
    Method: "method",
    Header: "header",
    Query: "query",
    Cookie: "cookie",
    TargetPath: "target_path",
    Route: "route",
    RawPath: "raw_path",
    IpAddress: "ip_address",
    Region: "region",
    Protocol: "protocol",
    Scheme: "scheme",
    Environment: "environment",
    UserAgent: "user_agent",
    GeoContinent: "geo_continent",
    GeoCountry: "geo_country",
    GeoCountryRegion: "geo_country_region",
    GeoCity: "geo_city",
    GeoAsNumber: "geo_as_number",
    Ja4Digest: "ja4_digest",
    Ja3Digest: "ja3_digest",
    RateLimitApiId: "rate_limit_api_id",
    ServerAction: "server_action",
    BotName: "bot_name",
    BotCategory: "bot_category",
};
export const RequestBodyOp = {
    Re: "re",
    Eq: "eq",
    Neq: "neq",
    Ex: "ex",
    Nex: "nex",
    Inc: "inc",
    Ninc: "ninc",
    Pre: "pre",
    Suf: "suf",
    Sub: "sub",
    Gt: "gt",
    Gte: "gte",
    Lt: "lt",
    Lte: "lte",
};
export const UpdateFirewallConfigRequestBodySecurityRequest2ValueAction = {
    Log: "log",
    Challenge: "challenge",
    Deny: "deny",
    Bypass: "bypass",
    RateLimit: "rate_limit",
    Redirect: "redirect",
};
export const RateLimitAlgo = {
    FixedWindow: "fixed_window",
    TokenBucket: "token_bucket",
};
export const UpdateFirewallConfigAction1 = {
    Log: "log",
    Challenge: "challenge",
    Deny: "deny",
    RateLimit: "rate_limit",
};
export const UpdateFirewallConfigRequestBodyAction = {
    FirewallEnabled: "firewallEnabled",
};
/** @internal */
export const RequestBody13$inboundSchema = z.object({
    action: types.string(),
    id: types.optional(types.string()),
    value: types.boolean(),
});
/** @internal */
export const RequestBody13$outboundSchema = z.object({
    action: z.string(),
    id: z.string().optional(),
    value: z.boolean(),
});
export function requestBody13ToJSON(requestBody13) {
    return JSON.stringify(RequestBody13$outboundSchema.parse(requestBody13));
}
export function requestBody13FromJSON(jsonString) {
    return safeParse(jsonString, (x) => RequestBody13$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RequestBody13' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodyId$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodyId);
/** @internal */
export const UpdateFirewallConfigRequestBodyId$outboundSchema = UpdateFirewallConfigRequestBodyId$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest12Action$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest12Action);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest12Action$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest12Action$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest12Value$inboundSchema = z.object({
    active: types.boolean(),
    action: types.optional(UpdateFirewallConfigRequestBodySecurityRequest12Action$inboundSchema),
});
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest12Value$outboundSchema = z.object({
    active: z.boolean(),
    action: UpdateFirewallConfigRequestBodySecurityRequest12Action$outboundSchema
        .optional(),
});
export function updateFirewallConfigRequestBodySecurityRequest12ValueToJSON(updateFirewallConfigRequestBodySecurityRequest12Value) {
    return JSON.stringify(UpdateFirewallConfigRequestBodySecurityRequest12Value$outboundSchema.parse(updateFirewallConfigRequestBodySecurityRequest12Value));
}
export function updateFirewallConfigRequestBodySecurityRequest12ValueFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodySecurityRequest12Value$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodySecurityRequest12Value' from JSON`);
}
/** @internal */
export const RequestBody12$inboundSchema = z.object({
    action: types.string(),
    id: UpdateFirewallConfigRequestBodyId$inboundSchema,
    value: z.record(z.lazy(() => UpdateFirewallConfigRequestBodySecurityRequest12Value$inboundSchema)),
});
/** @internal */
export const RequestBody12$outboundSchema = z.object({
    action: z.string(),
    id: UpdateFirewallConfigRequestBodyId$outboundSchema,
    value: z.record(z.lazy(() => UpdateFirewallConfigRequestBodySecurityRequest12Value$outboundSchema)),
});
export function requestBody12ToJSON(requestBody12) {
    return JSON.stringify(RequestBody12$outboundSchema.parse(requestBody12));
}
export function requestBody12FromJSON(jsonString) {
    return safeParse(jsonString, (x) => RequestBody12$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RequestBody12' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest11Action$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest11Action);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest11Action$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest11Action$inboundSchema;
/** @internal */
export const RequestBodyId$inboundSchema = z.nativeEnum(RequestBodyId);
/** @internal */
export const RequestBodyId$outboundSchema = RequestBodyId$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest11ValueAction$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest11ValueAction);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest11ValueAction$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest11ValueAction$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest11Value$inboundSchema = z.object({
    action: types.optional(UpdateFirewallConfigRequestBodySecurityRequest11ValueAction$inboundSchema),
    active: types.boolean(),
});
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest11Value$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest11ValueAction$outboundSchema
        .optional(),
    active: z.boolean(),
});
export function updateFirewallConfigRequestBodySecurityRequest11ValueToJSON(updateFirewallConfigRequestBodySecurityRequest11Value) {
    return JSON.stringify(UpdateFirewallConfigRequestBodySecurityRequest11Value$outboundSchema.parse(updateFirewallConfigRequestBodySecurityRequest11Value));
}
export function updateFirewallConfigRequestBodySecurityRequest11ValueFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodySecurityRequest11Value$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodySecurityRequest11Value' from JSON`);
}
/** @internal */
export const RequestBody11$inboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest11Action$inboundSchema,
    id: RequestBodyId$inboundSchema,
    value: z.lazy(() => UpdateFirewallConfigRequestBodySecurityRequest11Value$inboundSchema),
});
/** @internal */
export const RequestBody11$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest11Action$outboundSchema,
    id: RequestBodyId$outboundSchema,
    value: z.lazy(() => UpdateFirewallConfigRequestBodySecurityRequest11Value$outboundSchema),
});
export function requestBody11ToJSON(requestBody11) {
    return JSON.stringify(RequestBody11$outboundSchema.parse(requestBody11));
}
export function requestBody11FromJSON(jsonString) {
    return safeParse(jsonString, (x) => RequestBody11$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RequestBody11' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest10Action$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest10Action);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest10Action$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest10Action$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBody10$inboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest10Action$inboundSchema,
    id: types.string(),
    value: z.nullable(z.any()).optional(),
});
/** @internal */
export const UpdateFirewallConfigRequestBody10$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest10Action$outboundSchema,
    id: z.string(),
    value: z.nullable(z.any()).optional(),
});
export function updateFirewallConfigRequestBody10ToJSON(updateFirewallConfigRequestBody10) {
    return JSON.stringify(UpdateFirewallConfigRequestBody10$outboundSchema.parse(updateFirewallConfigRequestBody10));
}
export function updateFirewallConfigRequestBody10FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBody10$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBody10' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest9Action$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest9Action);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest9Action$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest9Action$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest9ValueAction$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest9ValueAction);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest9ValueAction$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest9ValueAction$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest9Value$inboundSchema = z.object({
    hostname: types.string(),
    ip: types.string(),
    notes: types.optional(types.string()),
    action: UpdateFirewallConfigRequestBodySecurityRequest9ValueAction$inboundSchema,
});
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest9Value$outboundSchema = z.object({
    hostname: z.string(),
    ip: z.string(),
    notes: z.string().optional(),
    action: UpdateFirewallConfigRequestBodySecurityRequest9ValueAction$outboundSchema,
});
export function updateFirewallConfigRequestBodySecurityRequest9ValueToJSON(updateFirewallConfigRequestBodySecurityRequest9Value) {
    return JSON.stringify(UpdateFirewallConfigRequestBodySecurityRequest9Value$outboundSchema.parse(updateFirewallConfigRequestBodySecurityRequest9Value));
}
export function updateFirewallConfigRequestBodySecurityRequest9ValueFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodySecurityRequest9Value$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodySecurityRequest9Value' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBody9$inboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest9Action$inboundSchema,
    id: types.string(),
    value: z.lazy(() => UpdateFirewallConfigRequestBodySecurityRequest9Value$inboundSchema),
});
/** @internal */
export const UpdateFirewallConfigRequestBody9$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest9Action$outboundSchema,
    id: z.string(),
    value: z.lazy(() => UpdateFirewallConfigRequestBodySecurityRequest9Value$outboundSchema),
});
export function updateFirewallConfigRequestBody9ToJSON(updateFirewallConfigRequestBody9) {
    return JSON.stringify(UpdateFirewallConfigRequestBody9$outboundSchema.parse(updateFirewallConfigRequestBody9));
}
export function updateFirewallConfigRequestBody9FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBody9$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBody9' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest8Action$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest8Action);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest8Action$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest8Action$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest8ValueAction$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest8ValueAction);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest8ValueAction$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest8ValueAction$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequestValue$inboundSchema = z.object({
    hostname: types.string(),
    ip: types.string(),
    notes: types.optional(types.string()),
    action: UpdateFirewallConfigRequestBodySecurityRequest8ValueAction$inboundSchema,
});
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequestValue$outboundSchema = z.object({
    hostname: z.string(),
    ip: z.string(),
    notes: z.string().optional(),
    action: UpdateFirewallConfigRequestBodySecurityRequest8ValueAction$outboundSchema,
});
export function updateFirewallConfigRequestBodySecurityRequestValueToJSON(updateFirewallConfigRequestBodySecurityRequestValue) {
    return JSON.stringify(UpdateFirewallConfigRequestBodySecurityRequestValue$outboundSchema.parse(updateFirewallConfigRequestBodySecurityRequestValue));
}
export function updateFirewallConfigRequestBodySecurityRequestValueFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodySecurityRequestValue$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodySecurityRequestValue' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBody8$inboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest8Action$inboundSchema,
    id: z.nullable(z.any()).optional(),
    value: z.lazy(() => UpdateFirewallConfigRequestBodySecurityRequestValue$inboundSchema),
});
/** @internal */
export const UpdateFirewallConfigRequestBody8$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest8Action$outboundSchema,
    id: z.nullable(z.any()).optional(),
    value: z.lazy(() => UpdateFirewallConfigRequestBodySecurityRequestValue$outboundSchema),
});
export function updateFirewallConfigRequestBody8ToJSON(updateFirewallConfigRequestBody8) {
    return JSON.stringify(UpdateFirewallConfigRequestBody8$outboundSchema.parse(updateFirewallConfigRequestBody8));
}
export function updateFirewallConfigRequestBody8FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBody8$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBody8' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest7Action$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest7Action);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest7Action$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest7Action$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBody7$inboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest7Action$inboundSchema,
    id: z.nullable(z.any()).optional(),
    value: z.nullable(z.any()).optional(),
});
/** @internal */
export const UpdateFirewallConfigRequestBody7$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest7Action$outboundSchema,
    id: z.nullable(z.any()).optional(),
    value: z.nullable(z.any()).optional(),
});
export function updateFirewallConfigRequestBody7ToJSON(updateFirewallConfigRequestBody7) {
    return JSON.stringify(UpdateFirewallConfigRequestBody7$outboundSchema.parse(updateFirewallConfigRequestBody7));
}
export function updateFirewallConfigRequestBody7FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBody7$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBody7' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest6Action$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest6Action);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest6Action$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest6Action$inboundSchema;
/** @internal */
export const Id$inboundSchema = z.nativeEnum(Id);
/** @internal */
export const Id$outboundSchema = Id$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest6ValueAction$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest6ValueAction);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest6ValueAction$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest6ValueAction$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityValue$inboundSchema = z.object({
    active: types.boolean(),
    action: UpdateFirewallConfigRequestBodySecurityRequest6ValueAction$inboundSchema,
});
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityValue$outboundSchema = z.object({
    active: z.boolean(),
    action: UpdateFirewallConfigRequestBodySecurityRequest6ValueAction$outboundSchema,
});
export function updateFirewallConfigRequestBodySecurityValueToJSON(updateFirewallConfigRequestBodySecurityValue) {
    return JSON.stringify(UpdateFirewallConfigRequestBodySecurityValue$outboundSchema.parse(updateFirewallConfigRequestBodySecurityValue));
}
export function updateFirewallConfigRequestBodySecurityValueFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodySecurityValue$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodySecurityValue' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBody6$inboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest6Action$inboundSchema,
    id: Id$inboundSchema,
    value: z.lazy(() => UpdateFirewallConfigRequestBodySecurityValue$inboundSchema),
});
/** @internal */
export const UpdateFirewallConfigRequestBody6$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest6Action$outboundSchema,
    id: Id$outboundSchema,
    value: z.lazy(() => UpdateFirewallConfigRequestBodySecurityValue$outboundSchema),
});
export function updateFirewallConfigRequestBody6ToJSON(updateFirewallConfigRequestBody6) {
    return JSON.stringify(UpdateFirewallConfigRequestBody6$outboundSchema.parse(updateFirewallConfigRequestBody6));
}
export function updateFirewallConfigRequestBody6FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBody6$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBody6' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest5Action$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest5Action);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest5Action$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest5Action$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBody5$inboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest5Action$inboundSchema,
    id: types.string(),
    value: types.number(),
});
/** @internal */
export const UpdateFirewallConfigRequestBody5$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest5Action$outboundSchema,
    id: z.string(),
    value: z.number(),
});
export function updateFirewallConfigRequestBody5ToJSON(updateFirewallConfigRequestBody5) {
    return JSON.stringify(UpdateFirewallConfigRequestBody5$outboundSchema.parse(updateFirewallConfigRequestBody5));
}
export function updateFirewallConfigRequestBody5FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBody5$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBody5' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest4Action$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest4Action);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest4Action$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest4Action$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBody4$inboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest4Action$inboundSchema,
    id: types.string(),
    value: z.nullable(z.any()).optional(),
});
/** @internal */
export const UpdateFirewallConfigRequestBody4$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest4Action$outboundSchema,
    id: z.string(),
    value: z.nullable(z.any()).optional(),
});
export function updateFirewallConfigRequestBody4ToJSON(updateFirewallConfigRequestBody4) {
    return JSON.stringify(UpdateFirewallConfigRequestBody4$outboundSchema.parse(updateFirewallConfigRequestBody4));
}
export function updateFirewallConfigRequestBody4FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBody4$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBody4' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequestAction$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequestAction);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequestAction$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequestAction$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityType$inboundSchema = z
    .nativeEnum(UpdateFirewallConfigRequestBodySecurityType);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityType$outboundSchema = UpdateFirewallConfigRequestBodySecurityType$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodyOp$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodyOp);
/** @internal */
export const UpdateFirewallConfigRequestBodyOp$outboundSchema = UpdateFirewallConfigRequestBodyOp$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest3Value$inboundSchema = smartUnion([types.string(), z.array(types.string()), types.number()]);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest3Value$outboundSchema = smartUnion([z.string(), z.array(z.string()), z.number()]);
export function updateFirewallConfigRequestBodySecurityRequest3ValueToJSON(updateFirewallConfigRequestBodySecurityRequest3Value) {
    return JSON.stringify(UpdateFirewallConfigRequestBodySecurityRequest3Value$outboundSchema.parse(updateFirewallConfigRequestBodySecurityRequest3Value));
}
export function updateFirewallConfigRequestBodySecurityRequest3ValueFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodySecurityRequest3Value$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodySecurityRequest3Value' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodyConditions$inboundSchema = z.object({
    type: UpdateFirewallConfigRequestBodySecurityType$inboundSchema,
    op: UpdateFirewallConfigRequestBodyOp$inboundSchema,
    neg: types.optional(types.boolean()),
    key: types.optional(types.string()),
    value: types.optional(smartUnion([types.string(), z.array(types.string()), types.number()])),
});
/** @internal */
export const UpdateFirewallConfigRequestBodyConditions$outboundSchema = z.object({
    type: UpdateFirewallConfigRequestBodySecurityType$outboundSchema,
    op: UpdateFirewallConfigRequestBodyOp$outboundSchema,
    neg: z.boolean().optional(),
    key: z.string().optional(),
    value: smartUnion([z.string(), z.array(z.string()), z.number()]).optional(),
});
export function updateFirewallConfigRequestBodyConditionsToJSON(updateFirewallConfigRequestBodyConditions) {
    return JSON.stringify(UpdateFirewallConfigRequestBodyConditions$outboundSchema.parse(updateFirewallConfigRequestBodyConditions));
}
export function updateFirewallConfigRequestBodyConditionsFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodyConditions$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodyConditions' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodyConditionGroup$inboundSchema = z.object({
    conditions: z.array(z.lazy(() => UpdateFirewallConfigRequestBodyConditions$inboundSchema)),
});
/** @internal */
export const UpdateFirewallConfigRequestBodyConditionGroup$outboundSchema = z.object({
    conditions: z.array(z.lazy(() => UpdateFirewallConfigRequestBodyConditions$outboundSchema)),
});
export function updateFirewallConfigRequestBodyConditionGroupToJSON(updateFirewallConfigRequestBodyConditionGroup) {
    return JSON.stringify(UpdateFirewallConfigRequestBodyConditionGroup$outboundSchema.parse(updateFirewallConfigRequestBodyConditionGroup));
}
export function updateFirewallConfigRequestBodyConditionGroupFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodyConditionGroup$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodyConditionGroup' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest3ValueAction$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest3ValueAction);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest3ValueAction$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest3ValueAction$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRateLimitAlgo$inboundSchema = z.nativeEnum(UpdateFirewallConfigRateLimitAlgo);
/** @internal */
export const UpdateFirewallConfigRateLimitAlgo$outboundSchema = UpdateFirewallConfigRateLimitAlgo$inboundSchema;
/** @internal */
export const UpdateFirewallConfigActionSecurity1$inboundSchema = z.nativeEnum(UpdateFirewallConfigActionSecurity1);
/** @internal */
export const UpdateFirewallConfigActionSecurity1$outboundSchema = UpdateFirewallConfigActionSecurity1$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRateLimitSecurityAction$inboundSchema = smartUnion([UpdateFirewallConfigActionSecurity1$inboundSchema, z.any()]);
/** @internal */
export const UpdateFirewallConfigRateLimitSecurityAction$outboundSchema = smartUnion([UpdateFirewallConfigActionSecurity1$outboundSchema, z.any()]);
export function updateFirewallConfigRateLimitSecurityActionToJSON(updateFirewallConfigRateLimitSecurityAction) {
    return JSON.stringify(UpdateFirewallConfigRateLimitSecurityAction$outboundSchema.parse(updateFirewallConfigRateLimitSecurityAction));
}
export function updateFirewallConfigRateLimitSecurityActionFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRateLimitSecurityAction$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRateLimitSecurityAction' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRateLimitSecurity1$inboundSchema = z.object({
    algo: UpdateFirewallConfigRateLimitAlgo$inboundSchema,
    window: types.number(),
    limit: types.number(),
    keys: z.array(types.string()),
    action: z.nullable(smartUnion([UpdateFirewallConfigActionSecurity1$inboundSchema, z.any()])).optional(),
});
/** @internal */
export const UpdateFirewallConfigRateLimitSecurity1$outboundSchema = z.object({
    algo: UpdateFirewallConfigRateLimitAlgo$outboundSchema,
    window: z.number(),
    limit: z.number(),
    keys: z.array(z.string()),
    action: z.nullable(smartUnion([UpdateFirewallConfigActionSecurity1$outboundSchema, z.any()])).optional(),
});
export function updateFirewallConfigRateLimitSecurity1ToJSON(updateFirewallConfigRateLimitSecurity1) {
    return JSON.stringify(UpdateFirewallConfigRateLimitSecurity1$outboundSchema.parse(updateFirewallConfigRateLimitSecurity1));
}
export function updateFirewallConfigRateLimitSecurity1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRateLimitSecurity1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRateLimitSecurity1' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodyRateLimit$inboundSchema = smartUnion([
    z.lazy(() => UpdateFirewallConfigRateLimitSecurity1$inboundSchema),
    z.any(),
]);
/** @internal */
export const UpdateFirewallConfigRequestBodyRateLimit$outboundSchema = smartUnion([
    z.lazy(() => UpdateFirewallConfigRateLimitSecurity1$outboundSchema),
    z.any(),
]);
export function updateFirewallConfigRequestBodyRateLimitToJSON(updateFirewallConfigRequestBodyRateLimit) {
    return JSON.stringify(UpdateFirewallConfigRequestBodyRateLimit$outboundSchema.parse(updateFirewallConfigRequestBodyRateLimit));
}
export function updateFirewallConfigRequestBodyRateLimitFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodyRateLimit$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodyRateLimit' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRedirectSecurity1$inboundSchema = z.object({
    location: types.string(),
    permanent: types.boolean(),
});
/** @internal */
export const UpdateFirewallConfigRedirectSecurity1$outboundSchema = z.object({
    location: z.string(),
    permanent: z.boolean(),
});
export function updateFirewallConfigRedirectSecurity1ToJSON(updateFirewallConfigRedirectSecurity1) {
    return JSON.stringify(UpdateFirewallConfigRedirectSecurity1$outboundSchema.parse(updateFirewallConfigRedirectSecurity1));
}
export function updateFirewallConfigRedirectSecurity1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRedirectSecurity1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRedirectSecurity1' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodyRedirect$inboundSchema = smartUnion([
    z.lazy(() => UpdateFirewallConfigRedirectSecurity1$inboundSchema),
    z.any(),
]);
/** @internal */
export const UpdateFirewallConfigRequestBodyRedirect$outboundSchema = smartUnion([
    z.lazy(() => UpdateFirewallConfigRedirectSecurity1$outboundSchema),
    z.any(),
]);
export function updateFirewallConfigRequestBodyRedirectToJSON(updateFirewallConfigRequestBodyRedirect) {
    return JSON.stringify(UpdateFirewallConfigRequestBodyRedirect$outboundSchema.parse(updateFirewallConfigRequestBodyRedirect));
}
export function updateFirewallConfigRequestBodyRedirectFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodyRedirect$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodyRedirect' from JSON`);
}
/** @internal */
export const RequestBodyLogHeaders$inboundSchema = smartUnion([types.string(), z.array(types.string())]);
/** @internal */
export const RequestBodyLogHeaders$outboundSchema = smartUnion([z.string(), z.array(z.string())]);
export function requestBodyLogHeadersToJSON(requestBodyLogHeaders) {
    return JSON.stringify(RequestBodyLogHeaders$outboundSchema.parse(requestBodyLogHeaders));
}
export function requestBodyLogHeadersFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RequestBodyLogHeaders$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RequestBodyLogHeaders' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodyMitigate$inboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest3ValueAction$inboundSchema,
    rateLimit: z.nullable(smartUnion([
        z.lazy(() => UpdateFirewallConfigRateLimitSecurity1$inboundSchema),
        z.any(),
    ])).optional(),
    redirect: z.nullable(smartUnion([
        z.lazy(() => UpdateFirewallConfigRedirectSecurity1$inboundSchema),
        z.any(),
    ])).optional(),
    actionDuration: z.nullable(types.string()).optional(),
    bypassSystem: z.nullable(types.boolean()).optional(),
    logHeaders: types.optional(smartUnion([types.string(), z.array(types.string())])),
});
/** @internal */
export const UpdateFirewallConfigRequestBodyMitigate$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest3ValueAction$outboundSchema,
    rateLimit: z.nullable(smartUnion([
        z.lazy(() => UpdateFirewallConfigRateLimitSecurity1$outboundSchema),
        z.any(),
    ])).optional(),
    redirect: z.nullable(smartUnion([
        z.lazy(() => UpdateFirewallConfigRedirectSecurity1$outboundSchema),
        z.any(),
    ])).optional(),
    actionDuration: z.nullable(z.string()).optional(),
    bypassSystem: z.nullable(z.boolean()).optional(),
    logHeaders: smartUnion([z.string(), z.array(z.string())]).optional(),
});
export function updateFirewallConfigRequestBodyMitigateToJSON(updateFirewallConfigRequestBodyMitigate) {
    return JSON.stringify(UpdateFirewallConfigRequestBodyMitigate$outboundSchema.parse(updateFirewallConfigRequestBodyMitigate));
}
export function updateFirewallConfigRequestBodyMitigateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodyMitigate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodyMitigate' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest3Action$inboundSchema = z.object({
    mitigate: types.optional(z.lazy(() => UpdateFirewallConfigRequestBodyMitigate$inboundSchema)),
});
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest3Action$outboundSchema = z.object({
    mitigate: z.lazy(() => UpdateFirewallConfigRequestBodyMitigate$outboundSchema).optional(),
});
export function updateFirewallConfigRequestBodySecurityRequest3ActionToJSON(updateFirewallConfigRequestBodySecurityRequest3Action) {
    return JSON.stringify(UpdateFirewallConfigRequestBodySecurityRequest3Action$outboundSchema.parse(updateFirewallConfigRequestBodySecurityRequest3Action));
}
export function updateFirewallConfigRequestBodySecurityRequest3ActionFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodySecurityRequest3Action$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodySecurityRequest3Action' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodyValidationErrors$inboundSchema = smartUnion([z.array(types.string()), types.string()]);
/** @internal */
export const UpdateFirewallConfigRequestBodyValidationErrors$outboundSchema = smartUnion([z.array(z.string()), z.string()]);
export function updateFirewallConfigRequestBodyValidationErrorsToJSON(updateFirewallConfigRequestBodyValidationErrors) {
    return JSON.stringify(UpdateFirewallConfigRequestBodyValidationErrors$outboundSchema.parse(updateFirewallConfigRequestBodyValidationErrors));
}
export function updateFirewallConfigRequestBodyValidationErrorsFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodyValidationErrors$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodyValidationErrors' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodyValue$inboundSchema = z.object({
    name: types.string(),
    description: types.optional(types.string()),
    active: types.boolean(),
    conditionGroup: z.array(z.lazy(() => UpdateFirewallConfigRequestBodyConditionGroup$inboundSchema)),
    action: z.lazy(() => UpdateFirewallConfigRequestBodySecurityRequest3Action$inboundSchema),
    valid: types.optional(types.boolean()),
    validationErrors: types.optional(smartUnion([z.array(types.string()), types.string()])),
});
/** @internal */
export const UpdateFirewallConfigRequestBodyValue$outboundSchema = z.object({
    name: z.string(),
    description: z.string().optional(),
    active: z.boolean(),
    conditionGroup: z.array(z.lazy(() => UpdateFirewallConfigRequestBodyConditionGroup$outboundSchema)),
    action: z.lazy(() => UpdateFirewallConfigRequestBodySecurityRequest3Action$outboundSchema),
    valid: z.boolean().optional(),
    validationErrors: smartUnion([z.array(z.string()), z.string()]).optional(),
});
export function updateFirewallConfigRequestBodyValueToJSON(updateFirewallConfigRequestBodyValue) {
    return JSON.stringify(UpdateFirewallConfigRequestBodyValue$outboundSchema.parse(updateFirewallConfigRequestBodyValue));
}
export function updateFirewallConfigRequestBodyValueFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodyValue$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodyValue' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBody3$inboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequestAction$inboundSchema,
    id: types.string(),
    value: z.lazy(() => UpdateFirewallConfigRequestBodyValue$inboundSchema),
});
/** @internal */
export const UpdateFirewallConfigRequestBody3$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequestAction$outboundSchema,
    id: z.string(),
    value: z.lazy(() => UpdateFirewallConfigRequestBodyValue$outboundSchema),
});
export function updateFirewallConfigRequestBody3ToJSON(updateFirewallConfigRequestBody3) {
    return JSON.stringify(UpdateFirewallConfigRequestBody3$outboundSchema.parse(updateFirewallConfigRequestBody3));
}
export function updateFirewallConfigRequestBody3FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBody3$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBody3' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityAction$inboundSchema = z
    .nativeEnum(UpdateFirewallConfigRequestBodySecurityAction);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityAction$outboundSchema = UpdateFirewallConfigRequestBodySecurityAction$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodyType$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodyType);
/** @internal */
export const UpdateFirewallConfigRequestBodyType$outboundSchema = UpdateFirewallConfigRequestBodyType$inboundSchema;
/** @internal */
export const RequestBodyOp$inboundSchema = z.nativeEnum(RequestBodyOp);
/** @internal */
export const RequestBodyOp$outboundSchema = RequestBodyOp$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest2Value$inboundSchema = smartUnion([types.string(), z.array(types.string()), types.number()]);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest2Value$outboundSchema = smartUnion([z.string(), z.array(z.string()), z.number()]);
export function updateFirewallConfigRequestBodySecurityRequest2ValueToJSON(updateFirewallConfigRequestBodySecurityRequest2Value) {
    return JSON.stringify(UpdateFirewallConfigRequestBodySecurityRequest2Value$outboundSchema.parse(updateFirewallConfigRequestBodySecurityRequest2Value));
}
export function updateFirewallConfigRequestBodySecurityRequest2ValueFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodySecurityRequest2Value$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodySecurityRequest2Value' from JSON`);
}
/** @internal */
export const RequestBodyConditions$inboundSchema = z.object({
    type: UpdateFirewallConfigRequestBodyType$inboundSchema,
    op: RequestBodyOp$inboundSchema,
    neg: types.optional(types.boolean()),
    key: types.optional(types.string()),
    value: types.optional(smartUnion([types.string(), z.array(types.string()), types.number()])),
});
/** @internal */
export const RequestBodyConditions$outboundSchema = z.object({
    type: UpdateFirewallConfigRequestBodyType$outboundSchema,
    op: RequestBodyOp$outboundSchema,
    neg: z.boolean().optional(),
    key: z.string().optional(),
    value: smartUnion([z.string(), z.array(z.string()), z.number()]).optional(),
});
export function requestBodyConditionsToJSON(requestBodyConditions) {
    return JSON.stringify(RequestBodyConditions$outboundSchema.parse(requestBodyConditions));
}
export function requestBodyConditionsFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RequestBodyConditions$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RequestBodyConditions' from JSON`);
}
/** @internal */
export const RequestBodyConditionGroup$inboundSchema = z.object({
    conditions: z.array(z.lazy(() => RequestBodyConditions$inboundSchema)),
});
/** @internal */
export const RequestBodyConditionGroup$outboundSchema = z.object({
    conditions: z.array(z.lazy(() => RequestBodyConditions$outboundSchema)),
});
export function requestBodyConditionGroupToJSON(requestBodyConditionGroup) {
    return JSON.stringify(RequestBodyConditionGroup$outboundSchema.parse(requestBodyConditionGroup));
}
export function requestBodyConditionGroupFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RequestBodyConditionGroup$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RequestBodyConditionGroup' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest2ValueAction$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodySecurityRequest2ValueAction);
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest2ValueAction$outboundSchema = UpdateFirewallConfigRequestBodySecurityRequest2ValueAction$inboundSchema;
/** @internal */
export const RateLimitAlgo$inboundSchema = z.nativeEnum(RateLimitAlgo);
/** @internal */
export const RateLimitAlgo$outboundSchema = RateLimitAlgo$inboundSchema;
/** @internal */
export const UpdateFirewallConfigAction1$inboundSchema = z.nativeEnum(UpdateFirewallConfigAction1);
/** @internal */
export const UpdateFirewallConfigAction1$outboundSchema = UpdateFirewallConfigAction1$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRateLimitAction$inboundSchema = smartUnion([UpdateFirewallConfigAction1$inboundSchema, z.any()]);
/** @internal */
export const UpdateFirewallConfigRateLimitAction$outboundSchema = smartUnion([UpdateFirewallConfigAction1$outboundSchema, z.any()]);
export function updateFirewallConfigRateLimitActionToJSON(updateFirewallConfigRateLimitAction) {
    return JSON.stringify(UpdateFirewallConfigRateLimitAction$outboundSchema.parse(updateFirewallConfigRateLimitAction));
}
export function updateFirewallConfigRateLimitActionFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRateLimitAction$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRateLimitAction' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRateLimit1$inboundSchema = z.object({
    algo: RateLimitAlgo$inboundSchema,
    window: types.number(),
    limit: types.number(),
    keys: z.array(types.string()),
    action: z.nullable(smartUnion([UpdateFirewallConfigAction1$inboundSchema, z.any()])).optional(),
});
/** @internal */
export const UpdateFirewallConfigRateLimit1$outboundSchema = z.object({
    algo: RateLimitAlgo$outboundSchema,
    window: z.number(),
    limit: z.number(),
    keys: z.array(z.string()),
    action: z.nullable(smartUnion([UpdateFirewallConfigAction1$outboundSchema, z.any()])).optional(),
});
export function updateFirewallConfigRateLimit1ToJSON(updateFirewallConfigRateLimit1) {
    return JSON.stringify(UpdateFirewallConfigRateLimit1$outboundSchema.parse(updateFirewallConfigRateLimit1));
}
export function updateFirewallConfigRateLimit1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRateLimit1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRateLimit1' from JSON`);
}
/** @internal */
export const RequestBodyRateLimit$inboundSchema = smartUnion([
    z.lazy(() => UpdateFirewallConfigRateLimit1$inboundSchema),
    z.any(),
]);
/** @internal */
export const RequestBodyRateLimit$outboundSchema = smartUnion([
    z.lazy(() => UpdateFirewallConfigRateLimit1$outboundSchema),
    z.any(),
]);
export function requestBodyRateLimitToJSON(requestBodyRateLimit) {
    return JSON.stringify(RequestBodyRateLimit$outboundSchema.parse(requestBodyRateLimit));
}
export function requestBodyRateLimitFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RequestBodyRateLimit$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RequestBodyRateLimit' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRedirect1$inboundSchema = z.object({
    location: types.string(),
    permanent: types.boolean(),
});
/** @internal */
export const UpdateFirewallConfigRedirect1$outboundSchema = z.object({
    location: z.string(),
    permanent: z.boolean(),
});
export function updateFirewallConfigRedirect1ToJSON(updateFirewallConfigRedirect1) {
    return JSON.stringify(UpdateFirewallConfigRedirect1$outboundSchema.parse(updateFirewallConfigRedirect1));
}
export function updateFirewallConfigRedirect1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRedirect1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRedirect1' from JSON`);
}
/** @internal */
export const RequestBodyRedirect$inboundSchema = smartUnion([
    z.lazy(() => UpdateFirewallConfigRedirect1$inboundSchema),
    z.any(),
]);
/** @internal */
export const RequestBodyRedirect$outboundSchema = smartUnion([
    z.lazy(() => UpdateFirewallConfigRedirect1$outboundSchema),
    z.any(),
]);
export function requestBodyRedirectToJSON(requestBodyRedirect) {
    return JSON.stringify(RequestBodyRedirect$outboundSchema.parse(requestBodyRedirect));
}
export function requestBodyRedirectFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RequestBodyRedirect$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RequestBodyRedirect' from JSON`);
}
/** @internal */
export const LogHeaders$inboundSchema = smartUnion([types.string(), z.array(types.string())]);
/** @internal */
export const LogHeaders$outboundSchema = smartUnion([z.string(), z.array(z.string())]);
export function logHeadersToJSON(logHeaders) {
    return JSON.stringify(LogHeaders$outboundSchema.parse(logHeaders));
}
export function logHeadersFromJSON(jsonString) {
    return safeParse(jsonString, (x) => LogHeaders$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'LogHeaders' from JSON`);
}
/** @internal */
export const RequestBodyMitigate$inboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest2ValueAction$inboundSchema,
    rateLimit: z.nullable(smartUnion([
        z.lazy(() => UpdateFirewallConfigRateLimit1$inboundSchema),
        z.any(),
    ])).optional(),
    redirect: z.nullable(smartUnion([
        z.lazy(() => UpdateFirewallConfigRedirect1$inboundSchema),
        z.any(),
    ])).optional(),
    actionDuration: z.nullable(types.string()).optional(),
    bypassSystem: z.nullable(types.boolean()).optional(),
    logHeaders: types.optional(smartUnion([types.string(), z.array(types.string())])),
});
/** @internal */
export const RequestBodyMitigate$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityRequest2ValueAction$outboundSchema,
    rateLimit: z.nullable(smartUnion([
        z.lazy(() => UpdateFirewallConfigRateLimit1$outboundSchema),
        z.any(),
    ])).optional(),
    redirect: z.nullable(smartUnion([
        z.lazy(() => UpdateFirewallConfigRedirect1$outboundSchema),
        z.any(),
    ])).optional(),
    actionDuration: z.nullable(z.string()).optional(),
    bypassSystem: z.nullable(z.boolean()).optional(),
    logHeaders: smartUnion([z.string(), z.array(z.string())]).optional(),
});
export function requestBodyMitigateToJSON(requestBodyMitigate) {
    return JSON.stringify(RequestBodyMitigate$outboundSchema.parse(requestBodyMitigate));
}
export function requestBodyMitigateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RequestBodyMitigate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RequestBodyMitigate' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest2Action$inboundSchema = z.object({
    mitigate: types.optional(z.lazy(() => RequestBodyMitigate$inboundSchema)),
});
/** @internal */
export const UpdateFirewallConfigRequestBodySecurityRequest2Action$outboundSchema = z.object({
    mitigate: z.lazy(() => RequestBodyMitigate$outboundSchema).optional(),
});
export function updateFirewallConfigRequestBodySecurityRequest2ActionToJSON(updateFirewallConfigRequestBodySecurityRequest2Action) {
    return JSON.stringify(UpdateFirewallConfigRequestBodySecurityRequest2Action$outboundSchema.parse(updateFirewallConfigRequestBodySecurityRequest2Action));
}
export function updateFirewallConfigRequestBodySecurityRequest2ActionFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBodySecurityRequest2Action$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBodySecurityRequest2Action' from JSON`);
}
/** @internal */
export const RequestBodyValidationErrors$inboundSchema = smartUnion([z.array(types.string()), types.string()]);
/** @internal */
export const RequestBodyValidationErrors$outboundSchema = smartUnion([z.array(z.string()), z.string()]);
export function requestBodyValidationErrorsToJSON(requestBodyValidationErrors) {
    return JSON.stringify(RequestBodyValidationErrors$outboundSchema.parse(requestBodyValidationErrors));
}
export function requestBodyValidationErrorsFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RequestBodyValidationErrors$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RequestBodyValidationErrors' from JSON`);
}
/** @internal */
export const RequestBodyValue$inboundSchema = z.object({
    name: types.string(),
    description: types.optional(types.string()),
    active: types.boolean(),
    conditionGroup: z.array(z.lazy(() => RequestBodyConditionGroup$inboundSchema)),
    action: z.lazy(() => UpdateFirewallConfigRequestBodySecurityRequest2Action$inboundSchema),
    valid: types.optional(types.boolean()),
    validationErrors: types.optional(smartUnion([z.array(types.string()), types.string()])),
});
/** @internal */
export const RequestBodyValue$outboundSchema = z.object({
    name: z.string(),
    description: z.string().optional(),
    active: z.boolean(),
    conditionGroup: z.array(z.lazy(() => RequestBodyConditionGroup$outboundSchema)),
    action: z.lazy(() => UpdateFirewallConfigRequestBodySecurityRequest2Action$outboundSchema),
    valid: z.boolean().optional(),
    validationErrors: smartUnion([z.array(z.string()), z.string()]).optional(),
});
export function requestBodyValueToJSON(requestBodyValue) {
    return JSON.stringify(RequestBodyValue$outboundSchema.parse(requestBodyValue));
}
export function requestBodyValueFromJSON(jsonString) {
    return safeParse(jsonString, (x) => RequestBodyValue$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'RequestBodyValue' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBody2$inboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityAction$inboundSchema,
    id: z.nullable(z.any()).optional(),
    value: z.lazy(() => RequestBodyValue$inboundSchema),
});
/** @internal */
export const UpdateFirewallConfigRequestBody2$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodySecurityAction$outboundSchema,
    id: z.nullable(z.any()).optional(),
    value: z.lazy(() => RequestBodyValue$outboundSchema),
});
export function updateFirewallConfigRequestBody2ToJSON(updateFirewallConfigRequestBody2) {
    return JSON.stringify(UpdateFirewallConfigRequestBody2$outboundSchema.parse(updateFirewallConfigRequestBody2));
}
export function updateFirewallConfigRequestBody2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBody2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBody2' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBodyAction$inboundSchema = z.nativeEnum(UpdateFirewallConfigRequestBodyAction);
/** @internal */
export const UpdateFirewallConfigRequestBodyAction$outboundSchema = UpdateFirewallConfigRequestBodyAction$inboundSchema;
/** @internal */
export const UpdateFirewallConfigRequestBody1$inboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodyAction$inboundSchema,
    id: z.nullable(z.any()).optional(),
    value: types.boolean(),
});
/** @internal */
export const UpdateFirewallConfigRequestBody1$outboundSchema = z.object({
    action: UpdateFirewallConfigRequestBodyAction$outboundSchema,
    id: z.nullable(z.any()).optional(),
    value: z.boolean(),
});
export function updateFirewallConfigRequestBody1ToJSON(updateFirewallConfigRequestBody1) {
    return JSON.stringify(UpdateFirewallConfigRequestBody1$outboundSchema.parse(updateFirewallConfigRequestBody1));
}
export function updateFirewallConfigRequestBody1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBody1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBody1' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequestBody$inboundSchema = smartUnion([
    z.lazy(() => UpdateFirewallConfigRequestBody3$inboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody5$inboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody6$inboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody9$inboundSchema),
    z.lazy(() => RequestBody11$inboundSchema),
    z.lazy(() => RequestBody12$inboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody1$inboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody2$inboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody4$inboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody8$inboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody10$inboundSchema),
    z.lazy(() => RequestBody13$inboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody7$inboundSchema),
]);
/** @internal */
export const UpdateFirewallConfigRequestBody$outboundSchema = smartUnion([
    z.lazy(() => UpdateFirewallConfigRequestBody3$outboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody5$outboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody6$outboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody9$outboundSchema),
    z.lazy(() => RequestBody11$outboundSchema),
    z.lazy(() => RequestBody12$outboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody1$outboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody2$outboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody4$outboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody8$outboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody10$outboundSchema),
    z.lazy(() => RequestBody13$outboundSchema),
    z.lazy(() => UpdateFirewallConfigRequestBody7$outboundSchema),
]);
export function updateFirewallConfigRequestBodyToJSON(updateFirewallConfigRequestBody) {
    return JSON.stringify(UpdateFirewallConfigRequestBody$outboundSchema.parse(updateFirewallConfigRequestBody));
}
export function updateFirewallConfigRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequestBody' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigRequest$inboundSchema = z.object({
    projectId: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
    RequestBody: smartUnion([
        z.lazy(() => UpdateFirewallConfigRequestBody3$inboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody5$inboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody6$inboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody9$inboundSchema),
        z.lazy(() => RequestBody11$inboundSchema),
        z.lazy(() => RequestBody12$inboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody1$inboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody2$inboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody4$inboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody8$inboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody10$inboundSchema),
        z.lazy(() => RequestBody13$inboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody7$inboundSchema),
    ]),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const UpdateFirewallConfigRequest$outboundSchema = z.object({
    projectId: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
    requestBody: smartUnion([
        z.lazy(() => UpdateFirewallConfigRequestBody3$outboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody5$outboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody6$outboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody9$outboundSchema),
        z.lazy(() => RequestBody11$outboundSchema),
        z.lazy(() => RequestBody12$outboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody1$outboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody2$outboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody4$outboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody8$outboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody10$outboundSchema),
        z.lazy(() => RequestBody13$outboundSchema),
        z.lazy(() => UpdateFirewallConfigRequestBody7$outboundSchema),
    ]),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function updateFirewallConfigRequestToJSON(updateFirewallConfigRequest) {
    return JSON.stringify(UpdateFirewallConfigRequest$outboundSchema.parse(updateFirewallConfigRequest));
}
export function updateFirewallConfigRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigRequest' from JSON`);
}
/** @internal */
export const UpdateFirewallConfigResponseBody$inboundSchema = z.object({});
/** @internal */
export const UpdateFirewallConfigResponseBody$outboundSchema = z.object({});
export function updateFirewallConfigResponseBodyToJSON(updateFirewallConfigResponseBody) {
    return JSON.stringify(UpdateFirewallConfigResponseBody$outboundSchema.parse(updateFirewallConfigResponseBody));
}
export function updateFirewallConfigResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateFirewallConfigResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateFirewallConfigResponseBody' from JSON`);
}
//# sourceMappingURL=updatefirewallconfigop.js.map