/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
/** @internal */
export const Revoke$inboundSchema = z
    .object({
    secret: types.string(),
    regenerate: types.boolean(),
});
/** @internal */
export const Revoke$outboundSchema = z.object({
    secret: z.string(),
    regenerate: z.boolean(),
});
export function revokeToJSON(revoke) {
    return JSON.stringify(Revoke$outboundSchema.parse(revoke));
}
export function revokeFromJSON(jsonString) {
    return safeParse(jsonString, (x) => Revoke$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'Revoke' from JSON`);
}
/** @internal */
export const Generate$inboundSchema = z.object({
    secret: types.optional(types.string()),
    note: types.optional(types.string()),
});
/** @internal */
export const Generate$outboundSchema = z.object({
    secret: z.string().optional(),
    note: z.string().optional(),
});
export function generateToJSON(generate) {
    return JSON.stringify(Generate$outboundSchema.parse(generate));
}
export function generateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => Generate$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'Generate' from JSON`);
}
/** @internal */
export const Update$inboundSchema = z
    .object({
    secret: types.string(),
    isEnvVar: types.optional(types.boolean()),
    note: types.optional(types.string()),
});
/** @internal */
export const Update$outboundSchema = z.object({
    secret: z.string(),
    isEnvVar: z.boolean().optional(),
    note: z.string().optional(),
});
export function updateToJSON(update) {
    return JSON.stringify(Update$outboundSchema.parse(update));
}
export function updateFromJSON(jsonString) {
    return safeParse(jsonString, (x) => Update$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'Update' from JSON`);
}
/** @internal */
export const UpdateProjectProtectionBypassRequestBody$inboundSchema = z.object({
    revoke: types.optional(z.lazy(() => Revoke$inboundSchema)),
    generate: types.optional(z.lazy(() => Generate$inboundSchema)),
    update: types.optional(z.lazy(() => Update$inboundSchema)),
});
/** @internal */
export const UpdateProjectProtectionBypassRequestBody$outboundSchema = z.object({
    revoke: z.lazy(() => Revoke$outboundSchema).optional(),
    generate: z.lazy(() => Generate$outboundSchema).optional(),
    update: z.lazy(() => Update$outboundSchema).optional(),
});
export function updateProjectProtectionBypassRequestBodyToJSON(updateProjectProtectionBypassRequestBody) {
    return JSON.stringify(UpdateProjectProtectionBypassRequestBody$outboundSchema.parse(updateProjectProtectionBypassRequestBody));
}
export function updateProjectProtectionBypassRequestBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateProjectProtectionBypassRequestBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateProjectProtectionBypassRequestBody' from JSON`);
}
/** @internal */
export const UpdateProjectProtectionBypassRequest$inboundSchema = z.object({
    idOrName: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
    RequestBody: z.lazy(() => UpdateProjectProtectionBypassRequestBody$inboundSchema),
}).transform((v) => {
    return remap$(v, {
        "RequestBody": "requestBody",
    });
});
/** @internal */
export const UpdateProjectProtectionBypassRequest$outboundSchema = z.object({
    idOrName: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
    requestBody: z.lazy(() => UpdateProjectProtectionBypassRequestBody$outboundSchema),
}).transform((v) => {
    return remap$(v, {
        requestBody: "RequestBody",
    });
});
export function updateProjectProtectionBypassRequestToJSON(updateProjectProtectionBypassRequest) {
    return JSON.stringify(UpdateProjectProtectionBypassRequest$outboundSchema.parse(updateProjectProtectionBypassRequest));
}
export function updateProjectProtectionBypassRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateProjectProtectionBypassRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateProjectProtectionBypassRequest' from JSON`);
}
/** @internal */
export const UpdateProjectProtectionBypassProtectionBypass2$inboundSchema = z.object({
    createdAt: types.number(),
    createdBy: types.string(),
    scope: types.literal("automation-bypass"),
    isEnvVar: types.optional(types.boolean()),
    note: types.optional(types.string()),
});
/** @internal */
export const UpdateProjectProtectionBypassProtectionBypass2$outboundSchema = z.object({
    createdAt: z.number(),
    createdBy: z.string(),
    scope: z.literal("automation-bypass"),
    isEnvVar: z.boolean().optional(),
    note: z.string().optional(),
});
export function updateProjectProtectionBypassProtectionBypass2ToJSON(updateProjectProtectionBypassProtectionBypass2) {
    return JSON.stringify(UpdateProjectProtectionBypassProtectionBypass2$outboundSchema.parse(updateProjectProtectionBypassProtectionBypass2));
}
export function updateProjectProtectionBypassProtectionBypass2FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateProjectProtectionBypassProtectionBypass2$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateProjectProtectionBypassProtectionBypass2' from JSON`);
}
/** @internal */
export const UpdateProjectProtectionBypassProtectionBypass1$inboundSchema = z.object({
    createdAt: types.number(),
    createdBy: types.string(),
    scope: types.literal("integration-automation-bypass"),
    integrationId: types.string(),
    configurationId: types.string(),
});
/** @internal */
export const UpdateProjectProtectionBypassProtectionBypass1$outboundSchema = z.object({
    createdAt: z.number(),
    createdBy: z.string(),
    scope: z.literal("integration-automation-bypass"),
    integrationId: z.string(),
    configurationId: z.string(),
});
export function updateProjectProtectionBypassProtectionBypass1ToJSON(updateProjectProtectionBypassProtectionBypass1) {
    return JSON.stringify(UpdateProjectProtectionBypassProtectionBypass1$outboundSchema.parse(updateProjectProtectionBypassProtectionBypass1));
}
export function updateProjectProtectionBypassProtectionBypass1FromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateProjectProtectionBypassProtectionBypass1$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateProjectProtectionBypassProtectionBypass1' from JSON`);
}
/** @internal */
export const UpdateProjectProtectionBypassProtectionBypass$inboundSchema = z.union([
    z.lazy(() => UpdateProjectProtectionBypassProtectionBypass1$inboundSchema),
    z.lazy(() => UpdateProjectProtectionBypassProtectionBypass2$inboundSchema),
]);
/** @internal */
export const UpdateProjectProtectionBypassProtectionBypass$outboundSchema = z.union([
    z.lazy(() => UpdateProjectProtectionBypassProtectionBypass1$outboundSchema),
    z.lazy(() => UpdateProjectProtectionBypassProtectionBypass2$outboundSchema),
]);
export function updateProjectProtectionBypassProtectionBypassToJSON(updateProjectProtectionBypassProtectionBypass) {
    return JSON.stringify(UpdateProjectProtectionBypassProtectionBypass$outboundSchema.parse(updateProjectProtectionBypassProtectionBypass));
}
export function updateProjectProtectionBypassProtectionBypassFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateProjectProtectionBypassProtectionBypass$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateProjectProtectionBypassProtectionBypass' from JSON`);
}
/** @internal */
export const UpdateProjectProtectionBypassResponseBody$inboundSchema = z.object({
    protectionBypass: types.optional(z.record(z.union([
        z.lazy(() => UpdateProjectProtectionBypassProtectionBypass1$inboundSchema),
        z.lazy(() => UpdateProjectProtectionBypassProtectionBypass2$inboundSchema),
    ]))),
});
/** @internal */
export const UpdateProjectProtectionBypassResponseBody$outboundSchema = z.object({
    protectionBypass: z.record(z.union([
        z.lazy(() => UpdateProjectProtectionBypassProtectionBypass1$outboundSchema),
        z.lazy(() => UpdateProjectProtectionBypassProtectionBypass2$outboundSchema),
    ])).optional(),
});
export function updateProjectProtectionBypassResponseBodyToJSON(updateProjectProtectionBypassResponseBody) {
    return JSON.stringify(UpdateProjectProtectionBypassResponseBody$outboundSchema.parse(updateProjectProtectionBypassResponseBody));
}
export function updateProjectProtectionBypassResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => UpdateProjectProtectionBypassResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'UpdateProjectProtectionBypassResponseBody' from JSON`);
}
//# sourceMappingURL=updateprojectprotectionbypassop.js.map