/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as types from "../types/primitives.js";
/** @internal */
export const WriteFilesRequest$inboundSchema = z.object({
    "x-cwd": types.optional(types.string()),
    sandboxId: types.string(),
    teamId: types.optional(types.string()),
    slug: types.optional(types.string()),
}).transform((v) => {
    return remap$(v, {
        "x-cwd": "xCwd",
    });
});
/** @internal */
export const WriteFilesRequest$outboundSchema = z.object({
    xCwd: z.string().optional(),
    sandboxId: z.string(),
    teamId: z.string().optional(),
    slug: z.string().optional(),
}).transform((v) => {
    return remap$(v, {
        xCwd: "x-cwd",
    });
});
export function writeFilesRequestToJSON(writeFilesRequest) {
    return JSON.stringify(WriteFilesRequest$outboundSchema.parse(writeFilesRequest));
}
export function writeFilesRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => WriteFilesRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'WriteFilesRequest' from JSON`);
}
/** @internal */
export const WriteFilesResponseBody$inboundSchema = z.object({});
/** @internal */
export const WriteFilesResponseBody$outboundSchema = z.object({});
export function writeFilesResponseBodyToJSON(writeFilesResponseBody) {
    return JSON.stringify(WriteFilesResponseBody$outboundSchema.parse(writeFilesResponseBody));
}
export function writeFilesResponseBodyFromJSON(jsonString) {
    return safeParse(jsonString, (x) => WriteFilesResponseBody$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'WriteFilesResponseBody' from JSON`);
}
//# sourceMappingURL=writefilesop.js.map