import { ClientSDK } from "../lib/sdks.js";
import { AccessGroups } from "./accessgroups.js";
import { Aliases } from "./aliases.js";
import { Artifacts } from "./artifacts.js";
import { Authentication } from "./authentication.js";
import { Billing } from "./billing.js";
import { BulkRedirects } from "./bulkredirects.js";
import { Certs } from "./certs.js";
import { Checks } from "./checks.js";
import { ChecksV2 } from "./checksv2.js";
import { Connect } from "./connect.js";
import { Deployments } from "./deployments.js";
import { Dns } from "./dns.js";
import { Domains } from "./domains.js";
import { DomainsRegistrar } from "./domainsregistrar.js";
import { Drains } from "./drains.js";
import { EdgeCache } from "./edgecache.js";
import { EdgeConfig } from "./edgeconfig.js";
import { Environment } from "./environment.js";
import { FeatureFlags } from "./featureflags.js";
import { Integrations } from "./integrations.js";
import { LogDrains } from "./logdrains.js";
import { Logs } from "./logs.js";
import { Marketplace } from "./marketplace.js";
import { ProjectMembers } from "./projectmembers.js";
import { ProjectRoutes } from "./projectroutes.js";
import { Projects } from "./projects.js";
import { RollingRelease } from "./rollingrelease.js";
import { Sandboxes } from "./sandboxes.js";
import { Security } from "./security.js";
import { StaticIps } from "./staticips.js";
import { Teams } from "./teams.js";
import { User } from "./user.js";
import { Webhooks } from "./webhooks.js";
export declare class Vercel extends ClientSDK {
    private _accessGroups?;
    get accessGroups(): AccessGroups;
    private _artifacts?;
    get artifacts(): Artifacts;
    private _billing?;
    get billing(): Billing;
    private _bulkRedirects?;
    get bulkRedirects(): BulkRedirects;
    private _checksV2?;
    get checksV2(): ChecksV2;
    private _checks?;
    get checks(): Checks;
    private _connect?;
    get connect(): Connect;
    private _deployments?;
    get deployments(): Deployments;
    private _integrations?;
    get integrations(): Integrations;
    private _dns?;
    get dns(): Dns;
    private _domainsRegistrar?;
    get domainsRegistrar(): DomainsRegistrar;
    private _domains?;
    get domains(): Domains;
    private _logDrains?;
    get logDrains(): LogDrains;
    private _drains?;
    get drains(): Drains;
    private _edgeCache?;
    get edgeCache(): EdgeCache;
    private _edgeConfig?;
    get edgeConfig(): EdgeConfig;
    private _environment?;
    get environment(): Environment;
    private _user?;
    get user(): User;
    private _featureFlags?;
    get featureFlags(): FeatureFlags;
    private _marketplace?;
    get marketplace(): Marketplace;
    private _authentication?;
    get authentication(): Authentication;
    private _logs?;
    get logs(): Logs;
    private _projectMembers?;
    get projectMembers(): ProjectMembers;
    private _projectRoutes?;
    get projectRoutes(): ProjectRoutes;
    private _projects?;
    get projects(): Projects;
    private _staticIps?;
    get staticIps(): StaticIps;
    private _rollingRelease?;
    get rollingRelease(): RollingRelease;
    private _sandboxes?;
    get sandboxes(): Sandboxes;
    private _security?;
    get security(): Security;
    private _teams?;
    get teams(): Teams;
    private _webhooks?;
    get webhooks(): Webhooks;
    private _aliases?;
    get aliases(): Aliases;
    private _certs?;
    get certs(): Certs;
}
//# sourceMappingURL=sdk.d.ts.map